// Code generated by taurus_go/entity, DO NOT EDIT.

package runtime

import (
	entity "git.zodileap.com/entity/runtime_v1"
	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
)

func (r *AgentSession) createAgentSession(config *DBOpCfg, db *RuntimeDB, params AgentSessionCreate) (*entity.AgentSessionEntity, error) {
	if err := params.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	options, err := r.buildAgentSessionOptions(db, params)
	if err != nil {
		return nil, zerr.Must(err)
	}
	e, err := db.AgentSessions.Create(
		params.UserId.String(),
		params.AgentCode.String(),
		options...,
	)
	if err != nil {
		return nil, RuntimeAgentSessionErr.Create(err)
	}
	return e, nil
}

func (r *AgentSession) buildAgentSessionOptions(db *RuntimeDB, params AgentSessionCreate) ([]func(*entity.AgentSessionEntity), error) {
	var options []func(*entity.AgentSessionEntity)
	if params.Status != nil {
		options = append(options, db.AgentSessions.WithStatus(params.Status.Int16()))
	}

	return options, nil
}

func (r *AgentSession) createAgentSessionDTO(keepOpen bool, e *entity.AgentSessionEntity, db *RuntimeDB) (*AgentSessionDTO, error) {
	if keepOpen {
		return NewAgentSessionDTO(e, db), nil
	}
	return NewAgentSessionDTO(e, db), nil
}

func (r *AgentSession) createAgentSessionsDTO(keepOpen bool, es []*entity.AgentSessionEntity, db *RuntimeDB) (*AgentSessionsDTO, error) {
	if keepOpen {
		return NewAgentSessionsDTO(es, db), nil
	}
	return NewAgentSessionsDTO(es, db), nil
}

func (r *PreviewEndpoint) createPreviewEndpoint(config *DBOpCfg, db *RuntimeDB, params PreviewEndpointCreate) (*entity.PreviewEndpointEntity, error) {
	if err := params.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	options, err := r.buildPreviewEndpointOptions(db, params)
	if err != nil {
		return nil, zerr.Must(err)
	}
	e, err := db.PreviewEndpoints.Create(
		params.SandboxId.Int64(),
		params.Url.String(),
		options...,
	)
	if err != nil {
		return nil, RuntimePreviewEndpointErr.Create(err)
	}
	return e, nil
}

func (r *PreviewEndpoint) buildPreviewEndpointOptions(db *RuntimeDB, params PreviewEndpointCreate) ([]func(*entity.PreviewEndpointEntity), error) {
	var options []func(*entity.PreviewEndpointEntity)
	if params.Status != nil {
		options = append(options, db.PreviewEndpoints.WithStatus(params.Status.Int16()))
	}
	if params.Expiration != nil {
		options = append(options, db.PreviewEndpoints.WithExpiration(params.Expiration.Int32()))
	}

	return options, nil
}

func (r *PreviewEndpoint) createPreviewEndpointDTO(keepOpen bool, e *entity.PreviewEndpointEntity, db *RuntimeDB) (*PreviewEndpointDTO, error) {
	if keepOpen {
		return NewPreviewEndpointDTO(e, db), nil
	}
	return NewPreviewEndpointDTO(e, db), nil
}

func (r *PreviewEndpoint) createPreviewEndpointsDTO(keepOpen bool, es []*entity.PreviewEndpointEntity, db *RuntimeDB) (*PreviewEndpointsDTO, error) {
	if keepOpen {
		return NewPreviewEndpointsDTO(es, db), nil
	}
	return NewPreviewEndpointsDTO(es, db), nil
}

func (r *SandboxInstance) createSandboxInstance(config *DBOpCfg, db *RuntimeDB, params SandboxInstanceCreate) (*entity.SandboxInstanceEntity, error) {
	if err := params.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	options, err := r.buildSandboxInstanceOptions(db, params)
	if err != nil {
		return nil, zerr.Must(err)
	}
	e, err := db.SandboxInstances.Create(
		params.SessionId.Int64(),
		options...,
	)
	if err != nil {
		return nil, RuntimeSandboxInstanceErr.Create(err)
	}
	return e, nil
}

func (r *SandboxInstance) buildSandboxInstanceOptions(db *RuntimeDB, params SandboxInstanceCreate) ([]func(*entity.SandboxInstanceEntity), error) {
	var options []func(*entity.SandboxInstanceEntity)
	if params.ContainerId != nil {
		options = append(options, db.SandboxInstances.WithContainerId(params.ContainerId.String()))
	}
	if params.PreviewUrl != nil {
		options = append(options, db.SandboxInstances.WithPreviewUrl(params.PreviewUrl.String()))
	}
	if params.Status != nil {
		options = append(options, db.SandboxInstances.WithStatus(params.Status.Int16()))
	}

	return options, nil
}

func (r *SandboxInstance) createSandboxInstanceDTO(keepOpen bool, e *entity.SandboxInstanceEntity, db *RuntimeDB) (*SandboxInstanceDTO, error) {
	if keepOpen {
		return NewSandboxInstanceDTO(e, db), nil
	}
	return NewSandboxInstanceDTO(e, db), nil
}

func (r *SandboxInstance) createSandboxInstancesDTO(keepOpen bool, es []*entity.SandboxInstanceEntity, db *RuntimeDB) (*SandboxInstancesDTO, error) {
	if keepOpen {
		return NewSandboxInstancesDTO(es, db), nil
	}
	return NewSandboxInstancesDTO(es, db), nil
}
