import type { AgentWorkflowDefinition } from "./types";

export const DEFAULT_AGENT_WORKFLOWS: AgentWorkflowDefinition[] = [
  {
    id: "wf-agent-full-delivery-v1",
    name: "完整项目开发（结构化信息）",
    description: "需求理解 -> 结构化项目语义 -> 交互契约（Apifox） -> API + Mock + 用例 -> 前端架构 -> 页面实现 -> 测试",
    version: 1,
    shared: false,
    agentKey: "agent",
    promptPrefix:
      "你正在执行“完整项目开发（结构化信息）”工作流：必须先输出结构化项目信息（业务语义、交互契约、界面信息架构、前端实现架构、工程约束），再按步骤实现并补齐测试。",
    graph: {
      nodes: [
        {
          id: "wf-agent-full-delivery-start",
          title: "开始",
          description: "接收项目需求并初始化上下文",
          instruction: "",
          type: "start",
          x: 80,
          y: 160,
        },
        {
          id: "wf-agent-full-delivery-requirements",
          title: "理解项目需求",
          description: "拆解目标、范围、验收标准",
          instruction: "先输出需求拆解、边界条件与可验证的验收标准。",
          type: "skill",
          skillId: "requirements-analyst",
          x: 320,
          y: 160,
        },
        {
          id: "wf-agent-full-delivery-apifox-model",
          title: "构建交互契约",
          description: "整理前后端交互模型并同步 Apifox",
          instruction: "先定义实体、请求模型、响应模型，再通过 Apifox 官方 MCP Server（npx -y apifox-mcp-server@latest）同步到 Apifox。",
          type: "skill",
          skillId: "apifox-model-designer",
          x: 560,
          y: 160,
        },
        {
          id: "wf-agent-full-delivery-api-mock",
          title: "构建 API 与 Mock",
          description: "补齐接口定义、Mock 与测试用例",
          instruction: "生成 API 契约与 Mock 场景，并补齐接口测试用例。",
          type: "action",
          x: 800,
          y: 160,
        },
        {
          id: "wf-agent-full-delivery-frontend-structure",
          title: "设计前端框架",
          description: "定义前端目录结构与模块边界",
          instruction: "输出前端代码结构（目录、模块边界、实现约束）。",
          type: "skill",
          skillId: "frontend-architect",
          x: 1040,
          y: 160,
        },
        {
          id: "wf-agent-full-delivery-pages",
          title: "实现页面布局",
          description: "根据需求和设计图落地页面",
          instruction: "先定义页面元素与菜单结构，再实现页面与交互细节。",
          type: "skill",
          skillId: "frontend-page-builder",
          x: 1280,
          y: 160,
        },
        {
          id: "wf-agent-full-delivery-test",
          title: "项目测试",
          description: "执行测试并输出可验证结果",
          instruction: "执行单测/集成测试并输出失败定位、修复建议与风险清单。",
          type: "action",
          x: 1520,
          y: 160,
        },
      ],
      edges: [
        {
          id: "wf-agent-full-delivery-edge-start-requirements",
          sourceId: "wf-agent-full-delivery-start",
          targetId: "wf-agent-full-delivery-requirements",
          type: "default",
        },
        {
          id: "wf-agent-full-delivery-edge-requirements-apifox-model",
          sourceId: "wf-agent-full-delivery-requirements",
          targetId: "wf-agent-full-delivery-apifox-model",
          type: "default",
        },
        {
          id: "wf-agent-full-delivery-edge-apifox-model-api-mock",
          sourceId: "wf-agent-full-delivery-apifox-model",
          targetId: "wf-agent-full-delivery-api-mock",
          type: "default",
        },
        {
          id: "wf-agent-full-delivery-edge-api-mock-frontend-structure",
          sourceId: "wf-agent-full-delivery-api-mock",
          targetId: "wf-agent-full-delivery-frontend-structure",
          type: "default",
        },
        {
          id: "wf-agent-full-delivery-edge-frontend-structure-pages",
          sourceId: "wf-agent-full-delivery-frontend-structure",
          targetId: "wf-agent-full-delivery-pages",
          type: "default",
        },
        {
          id: "wf-agent-full-delivery-edge-pages-test",
          sourceId: "wf-agent-full-delivery-pages",
          targetId: "wf-agent-full-delivery-test",
          type: "default",
        },
      ],
    },
  },
  {
    id: "wf-agent-frontend-1-v1",
    name: "前端项目-1（Skill 编排）",
    description: "需求分析 -> 数据库设计 -> MCP 写库 -> 接口代码 -> 测试 -> 报告",
    version: 1,
    shared: false,
    agentKey: "agent",
    promptPrefix:
      "你正在执行“前端项目-1（Skill 编排）”工作流：优先遵循技能链路完成需求分析、设计、实现、测试与报告交付。",
    graph: {
      nodes: [
        {
          id: "wf-agent-frontend-1-start",
          title: "开始",
          description: "接收用户需求并初始化执行上下文",
          instruction: "",
          type: "start",
          x: 80,
          y: 160,
        },
        {
          id: "wf-agent-frontend-1-skill-requirements",
          title: "需求分析 Skill",
          description: "拆解目标、约束、验收标准",
          instruction: "先输出可执行任务拆解、边界条件与验收标准。",
          type: "skill",
          skillId: "requirements-analyst",
          x: 320,
          y: 160,
        },
        {
          id: "wf-agent-frontend-1-skill-db",
          title: "数据库设计 Skill",
          description: "生成数据库设计与迁移方案",
          instruction: "输出实体、字段、索引、约束与迁移步骤。",
          type: "skill",
          skillId: "db-designer",
          x: 560,
          y: 160,
        },
        {
          id: "wf-agent-frontend-1-mcp",
          title: "MCP 写入 Postgres",
          description: "调用 MCP 工具执行数据库写入",
          instruction: "在执行写入前先校验风险并确认幂等策略。",
          type: "action",
          x: 800,
          y: 160,
        },
        {
          id: "wf-agent-frontend-1-skill-api",
          title: "接口代码 Skill",
          description: "生成接口与实现代码",
          instruction: "按分层结构生成接口、服务与必要测试骨架。",
          type: "skill",
          skillId: "api-codegen",
          x: 1040,
          y: 160,
        },
        {
          id: "wf-agent-frontend-1-test",
          title: "运行测试工具",
          description: "执行自动化测试并收集结果",
          instruction: "优先执行单元测试，失败时输出定位信息与修复建议。",
          type: "action",
          x: 1280,
          y: 160,
        },
        {
          id: "wf-agent-frontend-1-skill-report",
          title: "报告 Skill",
          description: "汇总输出执行报告",
          instruction: "汇总变更、测试结果、风险与后续建议。",
          type: "skill",
          skillId: "report-builder",
          x: 1520,
          y: 160,
        },
      ],
      edges: [
        {
          id: "wf-agent-frontend-1-edge-start-requirements",
          sourceId: "wf-agent-frontend-1-start",
          targetId: "wf-agent-frontend-1-skill-requirements",
          type: "default",
        },
        {
          id: "wf-agent-frontend-1-edge-requirements-db",
          sourceId: "wf-agent-frontend-1-skill-requirements",
          targetId: "wf-agent-frontend-1-skill-db",
          type: "default",
        },
        {
          id: "wf-agent-frontend-1-edge-db-mcp",
          sourceId: "wf-agent-frontend-1-skill-db",
          targetId: "wf-agent-frontend-1-mcp",
          type: "default",
        },
        {
          id: "wf-agent-frontend-1-edge-mcp-api",
          sourceId: "wf-agent-frontend-1-mcp",
          targetId: "wf-agent-frontend-1-skill-api",
          type: "default",
        },
        {
          id: "wf-agent-frontend-1-edge-api-test",
          sourceId: "wf-agent-frontend-1-skill-api",
          targetId: "wf-agent-frontend-1-test",
          type: "default",
        },
        {
          id: "wf-agent-frontend-1-edge-test-report",
          sourceId: "wf-agent-frontend-1-test",
          targetId: "wf-agent-frontend-1-skill-report",
          type: "default",
        },
      ],
    },
  },
  {
    id: "wf-agent-frontend-2-v1",
    name: "前端项目-2",
    description: "面向复杂交互和状态管理的前端迭代流程",
    version: 1,
    shared: false,
    agentKey: "agent",
    promptPrefix:
      "你正在执行“前端项目-2”工作流：先拆分页面状态和数据流，再落地组件与交互，确保错误处理对用户友好。",
  },
  {
    id: "wf-agent-backend-v1",
    name: "后端项目",
    description: "面向接口、服务与测试联动的后端开发流程",
    version: 1,
    shared: false,
    agentKey: "agent",
    promptPrefix:
      "你正在执行“后端项目”工作流：优先给出 API/Service 分层实现，补齐错误码映射与单元测试，确保可定位错误上下文。",
  },
];
