import type { CodeWorkflowDefinition, WorkflowDefinition } from "./types";

export const DEFAULT_MODEL_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "wf-model-full-v1",
    name: "模型完整流程（0→1→2→2.5→3）",
    description: "输入 -> 生图 -> 结构化 -> 图生模 -> Meshy 兜底 -> DCC MCP 操作（导入/新建/编辑/导出）",
    version: 1,
    shared: false,
    nodes: [
      {
        id: "node-input",
        kind: "input",
        name: "0. 输入",
        enabled: true,
        retryCount: 0,
        params: {},
      },
      {
        id: "node-image-generate",
        kind: "image_generate",
        name: "1. 生图（Gemini）",
        enabled: true,
        retryCount: 1,
        fallbackKind: "structured_constraints",
        params: {
          candidateCount: 4,
        },
      },
      {
        id: "node-structured",
        kind: "structured_constraints",
        name: "1.5 结构化描述",
        enabled: true,
        retryCount: 0,
        params: {},
      },
      {
        id: "node-meshy-i2m",
        kind: "meshy_image_to_3d",
        name: "2. Meshy 图生模",
        enabled: true,
        retryCount: 1,
        fallbackKind: "blender_refine_export",
        params: {
          quality: "balanced",
        },
      },
      {
        id: "node-meshy-refine",
        kind: "meshy_refine",
        name: "2.5 Meshy 兜底细化",
        enabled: true,
        retryCount: 1,
        fallbackKind: "blender_refine_export",
        params: {
          remesh: true,
          retexture: true,
        },
      },
      {
        id: "node-blender-refine",
        kind: "blender_refine_export",
        name: "3. DCC MCP 操作（导入/新建/编辑/按需导出）",
        enabled: true,
        retryCount: 1,
        params: {},
      },
    ],
  },
  {
    id: "wf-model-direct-blender-v1",
    name: "当前 DCC 直接操作",
    description: "跳过前序步骤，直接通过 MCP 对当前会话做导入/新建/编辑/按需导出",
    version: 1,
    shared: false,
    nodes: [
      {
        id: "node-blender-direct",
        kind: "blender_refine_export",
        name: "3. DCC 直接操作（导入/新建/编辑/按需导出）",
        enabled: true,
        retryCount: 1,
        params: {},
      },
    ],
  },
];

export const DEFAULT_CODE_WORKFLOWS: CodeWorkflowDefinition[] = [
  {
    id: "wf-code-frontend-1-v1",
    name: "前端项目-1（Skill 编排）",
    description: "需求分析 -> 数据库设计 -> MCP 写库 -> 接口代码 -> 测试 -> 报告",
    version: 1,
    shared: false,
    agentKey: "code",
    promptPrefix:
      "你正在执行“前端项目-1（Skill 编排）”工作流：优先遵循技能链路完成需求分析、设计、实现、测试与报告交付。",
    graph: {
      nodes: [
        {
          id: "wf-code-frontend-1-start",
          title: "开始",
          description: "接收用户需求并初始化执行上下文",
          instruction: "",
          type: "start",
          x: 80,
          y: 160,
        },
        {
          id: "wf-code-frontend-1-skill-requirements",
          title: "需求分析 Skill",
          description: "拆解目标、约束、验收标准",
          instruction: "先输出可执行任务拆解、边界条件与验收标准。",
          type: "skill",
          skillId: "requirements_analyst",
          skillVersion: "1.0.0",
          x: 320,
          y: 160,
        },
        {
          id: "wf-code-frontend-1-skill-db",
          title: "数据库设计 Skill",
          description: "生成数据库设计与迁移方案",
          instruction: "输出实体、字段、索引、约束与迁移步骤。",
          type: "skill",
          skillId: "db_designer",
          skillVersion: "1.0.0",
          x: 560,
          y: 160,
        },
        {
          id: "wf-code-frontend-1-mcp",
          title: "MCP 写入 Postgres",
          description: "调用 MCP 工具执行数据库写入",
          instruction: "在执行写入前先校验风险并确认幂等策略。",
          type: "action",
          x: 800,
          y: 160,
        },
        {
          id: "wf-code-frontend-1-skill-api",
          title: "接口代码 Skill",
          description: "生成接口与实现代码",
          instruction: "按分层结构生成接口、服务与必要测试骨架。",
          type: "skill",
          skillId: "api_codegen",
          skillVersion: "1.0.0",
          x: 1040,
          y: 160,
        },
        {
          id: "wf-code-frontend-1-test",
          title: "运行测试工具",
          description: "执行自动化测试并收集结果",
          instruction: "优先执行单元测试，失败时输出定位信息与修复建议。",
          type: "action",
          x: 1280,
          y: 160,
        },
        {
          id: "wf-code-frontend-1-skill-report",
          title: "报告 Skill",
          description: "汇总输出执行报告",
          instruction: "汇总变更、测试结果、风险与后续建议。",
          type: "skill",
          skillId: "report_builder",
          skillVersion: "1.0.0",
          x: 1520,
          y: 160,
        },
      ],
      edges: [
        {
          id: "wf-code-frontend-1-edge-start-requirements",
          sourceId: "wf-code-frontend-1-start",
          targetId: "wf-code-frontend-1-skill-requirements",
          type: "default",
        },
        {
          id: "wf-code-frontend-1-edge-requirements-db",
          sourceId: "wf-code-frontend-1-skill-requirements",
          targetId: "wf-code-frontend-1-skill-db",
          type: "default",
        },
        {
          id: "wf-code-frontend-1-edge-db-mcp",
          sourceId: "wf-code-frontend-1-skill-db",
          targetId: "wf-code-frontend-1-mcp",
          type: "default",
        },
        {
          id: "wf-code-frontend-1-edge-mcp-api",
          sourceId: "wf-code-frontend-1-mcp",
          targetId: "wf-code-frontend-1-skill-api",
          type: "default",
        },
        {
          id: "wf-code-frontend-1-edge-api-test",
          sourceId: "wf-code-frontend-1-skill-api",
          targetId: "wf-code-frontend-1-test",
          type: "default",
        },
        {
          id: "wf-code-frontend-1-edge-test-report",
          sourceId: "wf-code-frontend-1-test",
          targetId: "wf-code-frontend-1-skill-report",
          type: "default",
        },
      ],
    },
  },
  {
    id: "wf-code-frontend-2-v1",
    name: "前端项目-2",
    description: "面向复杂交互和状态管理的前端迭代流程",
    version: 1,
    shared: false,
    agentKey: "code",
    promptPrefix:
      "你正在执行“前端项目-2”工作流：先拆分页面状态和数据流，再落地组件与交互，确保错误处理对用户友好。",
  },
  {
    id: "wf-code-backend-v1",
    name: "后端项目",
    description: "面向接口、服务与测试联动的后端开发流程",
    version: 1,
    shared: false,
    agentKey: "code",
    promptPrefix:
      "你正在执行“后端项目”工作流：优先给出 API/Service 分层实现，补齐错误码映射与单元测试，确保可定位错误上下文。",
  },
];
