// Code generated by taurus_go/entity, DO NOT EDIT.

package billing

import zerr "git.zodileap.com/taurus/zodileap_go_zerr"

// BillingSaveErr 数据库billing执行保存操作出现错误
func BillingSaveErr(err error) *zerr.Err {
	return zerr.SaveErr("billing", err)
}

var (
	// BillingOrderInfoErr 数据库Billing中order_info表执行操作出现错误
	BillingOrderInfoErr = zerr.NewEntityError("billing", "order_info")
	// BillingOrderItemErr 数据库Billing中order_item表执行操作出现错误
	BillingOrderItemErr = zerr.NewEntityError("billing", "order_item")
	// BillingSubscriptionErr 数据库Billing中subscription表执行操作出现错误
	BillingSubscriptionErr = zerr.NewEntityError("billing", "subscription")
)
