// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import zerr "git.zodileap.com/taurus/zodileap_go_zerr"

// EnterpriseSaveErr 数据库enterprise执行保存操作出现错误
func EnterpriseSaveErr(err error) *zerr.Err {
	return zerr.SaveErr("enterprise", err)
}

var (
	// EnterpriseEnterpriseErr 数据库Enterprise中enterprise表执行操作出现错误
	EnterpriseEnterpriseErr = zerr.NewEntityError("enterprise", "enterprise")
	// EnterpriseEnterpriseMemberErr 数据库Enterprise中enterprise_member表执行操作出现错误
	EnterpriseEnterpriseMemberErr = zerr.NewEntityError("enterprise", "enterprise_member")
	// EnterpriseEnterpriseRoleErr 数据库Enterprise中enterprise_role表执行操作出现错误
	EnterpriseEnterpriseRoleErr = zerr.NewEntityError("enterprise", "enterprise_role")
)
