// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import (
	entity "git.zodileap.com/entity/enterprise_v1"
	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
	zspecs "git.zodileap.com/taurus/zodileap_go_zspecs"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

func (r *Enterprise) queryEnterprise(db *EnterpriseDB, q *entity.EnterpriseEntityQuery, query EnterpriseQuery, includeDelete bool) (*entity.EnterpriseEntityQuery, error) {
	hasAnyCondition := false
	if err := query.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	if query.Id != nil {
		q = q.Where(db.Enterprises.Id.EQ(query.Id.Int64()))
		hasAnyCondition = true
	}
	if query.Ids != nil {
		Ids := []int64{}
		for _, v := range query.Ids {
			Ids = append(Ids, v.Int64())
		}
		q = q.Where(db.Enterprises.Id.In(Ids...))
		hasAnyCondition = true
	}
	if query.Code != nil {
		q = q.Where(db.Enterprises.Code.EQ(query.Code.String()))
		hasAnyCondition = true
	}
	if query.Codes != nil {
		Codes := []string{}
		for _, v := range query.Codes {
			Codes = append(Codes, v.String())
		}
		q = q.Where(db.Enterprises.Code.In(Codes...))
		hasAnyCondition = true
	}
	if query.Name != nil {
		q = q.Where(db.Enterprises.Name.EQ(query.Name.String()))
		hasAnyCondition = true
	}
	if query.Names != nil {
		Names := []string{}
		for _, v := range query.Names {
			Names = append(Names, v.String())
		}
		q = q.Where(db.Enterprises.Name.In(Names...))
		hasAnyCondition = true
	}
	if query.Status != nil {
		q = q.Where(db.Enterprises.Status.EQ(query.Status.Int16()))
		hasAnyCondition = true
	}
	if query.Statuss != nil {
		Statuss := []int16{}
		for _, v := range query.Statuss {
			Statuss = append(Statuss, v.Int16())
		}
		q = q.Where(db.Enterprises.Status.In(Statuss...))
		hasAnyCondition = true
	}
	if query.Remark != nil {
		q = q.Where(db.Enterprises.Remark.EQ(query.Remark.String()))
		hasAnyCondition = true
	}
	if query.Remarks != nil {
		Remarks := []string{}
		for _, v := range query.Remarks {
			Remarks = append(Remarks, v.String())
		}
		q = q.Where(db.Enterprises.Remark.In(Remarks...))
		hasAnyCondition = true
	}

	// 创建时间开始时间
	if query.CreatedAtStart != nil {
		q = q.Where(db.Enterprises.CreatedAt.GTE(query.CreatedAtStart.Time()))
		hasAnyCondition = true
	}

	// 创建时间结束时间
	if query.CreatedAtEnd != nil {
		q = q.Where(db.Enterprises.CreatedAt.LTE(query.CreatedAtEnd.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间开始时间
	if query.LastAtStart != nil {
		q = q.Where(db.Enterprises.LastAt.GTE(query.LastAtStart.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间结束时间
	if query.LastAtEnd != nil {
		q = q.Where(db.Enterprises.LastAt.LTE(query.LastAtEnd.Time()))
		hasAnyCondition = true
	}

	// 是否已经逻辑删除
	if !includeDelete {
		if hasAnyCondition {
			q.Where(
				entitysql.And,
				db.Enterprises.DeletedAt.IsNull(),
			)
		} else {
			q.Where(
				db.Enterprises.DeletedAt.IsNull(),
			)
		}
	}

	// 排序
	if query.ById != nil {
		switch *query.ById {
		case zspecs.OrderByAsc:
			q.Order(db.Enterprises.ById.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Enterprises.ById.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Enterprises.ById.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Enterprises.ById.NullsLast())
		}
	}
	if query.ByCode != nil {
		switch *query.ByCode {
		case zspecs.OrderByAsc:
			q.Order(db.Enterprises.ByCode.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Enterprises.ByCode.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Enterprises.ByCode.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Enterprises.ByCode.NullsLast())
		}
	}
	if query.ByName != nil {
		switch *query.ByName {
		case zspecs.OrderByAsc:
			q.Order(db.Enterprises.ByName.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Enterprises.ByName.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Enterprises.ByName.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Enterprises.ByName.NullsLast())
		}
	}
	if query.ByStatus != nil {
		switch *query.ByStatus {
		case zspecs.OrderByAsc:
			q.Order(db.Enterprises.ByStatus.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Enterprises.ByStatus.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Enterprises.ByStatus.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Enterprises.ByStatus.NullsLast())
		}
	}
	if query.ByRemark != nil {
		switch *query.ByRemark {
		case zspecs.OrderByAsc:
			q.Order(db.Enterprises.ByRemark.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Enterprises.ByRemark.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Enterprises.ByRemark.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Enterprises.ByRemark.NullsLast())
		}
	}
	if query.ByCreatedAt != nil {
		switch *query.ByCreatedAt {
		case zspecs.OrderByAsc:
			q.Order(db.Enterprises.ByCreatedAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Enterprises.ByCreatedAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Enterprises.ByCreatedAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Enterprises.ByCreatedAt.NullsLast())
		}
	}
	if query.ByLastAt != nil {
		switch *query.ByLastAt {
		case zspecs.OrderByAsc:
			q.Order(db.Enterprises.ByLastAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Enterprises.ByLastAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Enterprises.ByLastAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Enterprises.ByLastAt.NullsLast())
		}
	}

	return q, nil
}
func (r *EnterpriseMember) queryEnterpriseMember(db *EnterpriseDB, q *entity.EnterpriseMemberEntityQuery, query EnterpriseMemberQuery, includeDelete bool) (*entity.EnterpriseMemberEntityQuery, error) {
	hasAnyCondition := false
	if err := query.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	if query.Id != nil {
		q = q.Where(db.EnterpriseMembers.Id.EQ(query.Id.Int64()))
		hasAnyCondition = true
	}
	if query.Ids != nil {
		Ids := []int64{}
		for _, v := range query.Ids {
			Ids = append(Ids, v.Int64())
		}
		q = q.Where(db.EnterpriseMembers.Id.In(Ids...))
		hasAnyCondition = true
	}
	if query.EnterpriseId != nil {
		q = q.Where(db.EnterpriseMembers.EnterpriseId.EQ(query.EnterpriseId.Int64()))
		hasAnyCondition = true
	}
	if query.EnterpriseIds != nil {
		EnterpriseIds := []int64{}
		for _, v := range query.EnterpriseIds {
			EnterpriseIds = append(EnterpriseIds, v.Int64())
		}
		q = q.Where(db.EnterpriseMembers.EnterpriseId.In(EnterpriseIds...))
		hasAnyCondition = true
	}
	if query.UserId != nil {
		q = q.Where(db.EnterpriseMembers.UserId.EQ(query.UserId.String()))
		hasAnyCondition = true
	}
	if query.UserIds != nil {
		UserIds := []string{}
		for _, v := range query.UserIds {
			UserIds = append(UserIds, v.String())
		}
		q = q.Where(db.EnterpriseMembers.UserId.In(UserIds...))
		hasAnyCondition = true
	}
	if query.RoleCode != nil {
		q = q.Where(db.EnterpriseMembers.RoleCode.EQ(query.RoleCode.String()))
		hasAnyCondition = true
	}
	if query.RoleCodes != nil {
		RoleCodes := []string{}
		for _, v := range query.RoleCodes {
			RoleCodes = append(RoleCodes, v.String())
		}
		q = q.Where(db.EnterpriseMembers.RoleCode.In(RoleCodes...))
		hasAnyCondition = true
	}
	if query.Status != nil {
		q = q.Where(db.EnterpriseMembers.Status.EQ(query.Status.Int16()))
		hasAnyCondition = true
	}
	if query.Statuss != nil {
		Statuss := []int16{}
		for _, v := range query.Statuss {
			Statuss = append(Statuss, v.Int16())
		}
		q = q.Where(db.EnterpriseMembers.Status.In(Statuss...))
		hasAnyCondition = true
	}

	// 创建时间开始时间
	if query.CreatedAtStart != nil {
		q = q.Where(db.EnterpriseMembers.CreatedAt.GTE(query.CreatedAtStart.Time()))
		hasAnyCondition = true
	}

	// 创建时间结束时间
	if query.CreatedAtEnd != nil {
		q = q.Where(db.EnterpriseMembers.CreatedAt.LTE(query.CreatedAtEnd.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间开始时间
	if query.LastAtStart != nil {
		q = q.Where(db.EnterpriseMembers.LastAt.GTE(query.LastAtStart.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间结束时间
	if query.LastAtEnd != nil {
		q = q.Where(db.EnterpriseMembers.LastAt.LTE(query.LastAtEnd.Time()))
		hasAnyCondition = true
	}

	// 是否已经逻辑删除
	if !includeDelete {
		if hasAnyCondition {
			q.Where(
				entitysql.And,
				db.EnterpriseMembers.DeletedAt.IsNull(),
			)
		} else {
			q.Where(
				db.EnterpriseMembers.DeletedAt.IsNull(),
			)
		}
	}

	// 排序
	if query.ById != nil {
		switch *query.ById {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseMembers.ById.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseMembers.ById.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseMembers.ById.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseMembers.ById.NullsLast())
		}
	}
	if query.ByEnterpriseId != nil {
		switch *query.ByEnterpriseId {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseMembers.ByEnterpriseId.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseMembers.ByEnterpriseId.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseMembers.ByEnterpriseId.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseMembers.ByEnterpriseId.NullsLast())
		}
	}
	if query.ByUserId != nil {
		switch *query.ByUserId {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseMembers.ByUserId.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseMembers.ByUserId.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseMembers.ByUserId.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseMembers.ByUserId.NullsLast())
		}
	}
	if query.ByRoleCode != nil {
		switch *query.ByRoleCode {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseMembers.ByRoleCode.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseMembers.ByRoleCode.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseMembers.ByRoleCode.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseMembers.ByRoleCode.NullsLast())
		}
	}
	if query.ByStatus != nil {
		switch *query.ByStatus {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseMembers.ByStatus.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseMembers.ByStatus.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseMembers.ByStatus.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseMembers.ByStatus.NullsLast())
		}
	}
	if query.ByCreatedAt != nil {
		switch *query.ByCreatedAt {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseMembers.ByCreatedAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseMembers.ByCreatedAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseMembers.ByCreatedAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseMembers.ByCreatedAt.NullsLast())
		}
	}
	if query.ByLastAt != nil {
		switch *query.ByLastAt {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseMembers.ByLastAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseMembers.ByLastAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseMembers.ByLastAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseMembers.ByLastAt.NullsLast())
		}
	}

	return q, nil
}
func (r *EnterpriseRole) queryEnterpriseRole(db *EnterpriseDB, q *entity.EnterpriseRoleEntityQuery, query EnterpriseRoleQuery, includeDelete bool) (*entity.EnterpriseRoleEntityQuery, error) {
	hasAnyCondition := false
	if err := query.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	if query.Id != nil {
		q = q.Where(db.EnterpriseRoles.Id.EQ(query.Id.Int64()))
		hasAnyCondition = true
	}
	if query.Ids != nil {
		Ids := []int64{}
		for _, v := range query.Ids {
			Ids = append(Ids, v.Int64())
		}
		q = q.Where(db.EnterpriseRoles.Id.In(Ids...))
		hasAnyCondition = true
	}
	if query.EnterpriseId != nil {
		q = q.Where(db.EnterpriseRoles.EnterpriseId.EQ(query.EnterpriseId.Int64()))
		hasAnyCondition = true
	}
	if query.EnterpriseIds != nil {
		EnterpriseIds := []int64{}
		for _, v := range query.EnterpriseIds {
			EnterpriseIds = append(EnterpriseIds, v.Int64())
		}
		q = q.Where(db.EnterpriseRoles.EnterpriseId.In(EnterpriseIds...))
		hasAnyCondition = true
	}
	if query.Code != nil {
		q = q.Where(db.EnterpriseRoles.Code.EQ(query.Code.String()))
		hasAnyCondition = true
	}
	if query.Codes != nil {
		Codes := []string{}
		for _, v := range query.Codes {
			Codes = append(Codes, v.String())
		}
		q = q.Where(db.EnterpriseRoles.Code.In(Codes...))
		hasAnyCondition = true
	}
	if query.Name != nil {
		q = q.Where(db.EnterpriseRoles.Name.EQ(query.Name.String()))
		hasAnyCondition = true
	}
	if query.Names != nil {
		Names := []string{}
		for _, v := range query.Names {
			Names = append(Names, v.String())
		}
		q = q.Where(db.EnterpriseRoles.Name.In(Names...))
		hasAnyCondition = true
	}
	if query.Status != nil {
		q = q.Where(db.EnterpriseRoles.Status.EQ(query.Status.Int16()))
		hasAnyCondition = true
	}
	if query.Statuss != nil {
		Statuss := []int16{}
		for _, v := range query.Statuss {
			Statuss = append(Statuss, v.Int16())
		}
		q = q.Where(db.EnterpriseRoles.Status.In(Statuss...))
		hasAnyCondition = true
	}
	if query.Remark != nil {
		q = q.Where(db.EnterpriseRoles.Remark.EQ(query.Remark.String()))
		hasAnyCondition = true
	}
	if query.Remarks != nil {
		Remarks := []string{}
		for _, v := range query.Remarks {
			Remarks = append(Remarks, v.String())
		}
		q = q.Where(db.EnterpriseRoles.Remark.In(Remarks...))
		hasAnyCondition = true
	}

	// 创建时间开始时间
	if query.CreatedAtStart != nil {
		q = q.Where(db.EnterpriseRoles.CreatedAt.GTE(query.CreatedAtStart.Time()))
		hasAnyCondition = true
	}

	// 创建时间结束时间
	if query.CreatedAtEnd != nil {
		q = q.Where(db.EnterpriseRoles.CreatedAt.LTE(query.CreatedAtEnd.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间开始时间
	if query.LastAtStart != nil {
		q = q.Where(db.EnterpriseRoles.LastAt.GTE(query.LastAtStart.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间结束时间
	if query.LastAtEnd != nil {
		q = q.Where(db.EnterpriseRoles.LastAt.LTE(query.LastAtEnd.Time()))
		hasAnyCondition = true
	}

	// 是否已经逻辑删除
	if !includeDelete {
		if hasAnyCondition {
			q.Where(
				entitysql.And,
				db.EnterpriseRoles.DeletedAt.IsNull(),
			)
		} else {
			q.Where(
				db.EnterpriseRoles.DeletedAt.IsNull(),
			)
		}
	}

	// 排序
	if query.ById != nil {
		switch *query.ById {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ById.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ById.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ById.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ById.NullsLast())
		}
	}
	if query.ByEnterpriseId != nil {
		switch *query.ByEnterpriseId {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ByEnterpriseId.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ByEnterpriseId.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ByEnterpriseId.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ByEnterpriseId.NullsLast())
		}
	}
	if query.ByCode != nil {
		switch *query.ByCode {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ByCode.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ByCode.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ByCode.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ByCode.NullsLast())
		}
	}
	if query.ByName != nil {
		switch *query.ByName {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ByName.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ByName.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ByName.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ByName.NullsLast())
		}
	}
	if query.ByStatus != nil {
		switch *query.ByStatus {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ByStatus.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ByStatus.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ByStatus.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ByStatus.NullsLast())
		}
	}
	if query.ByRemark != nil {
		switch *query.ByRemark {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ByRemark.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ByRemark.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ByRemark.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ByRemark.NullsLast())
		}
	}
	if query.ByCreatedAt != nil {
		switch *query.ByCreatedAt {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ByCreatedAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ByCreatedAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ByCreatedAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ByCreatedAt.NullsLast())
		}
	}
	if query.ByLastAt != nil {
		switch *query.ByLastAt {
		case zspecs.OrderByAsc:
			q.Order(db.EnterpriseRoles.ByLastAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.EnterpriseRoles.ByLastAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.EnterpriseRoles.ByLastAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.EnterpriseRoles.ByLastAt.NullsLast())
		}
	}

	return q, nil
}
