// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"context"

	entity "git.zodileap.com/entity/account_v1"
	tentity "github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/tlog"

	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
)

const dbName = "account"
const agentAccessEntityName = "agent_access"
const agentEntityName = "agent"
const permissionGrantEntityName = "permission_grant"
const userEntityName = "user_info"
const userIdentityEntityName = "user_identity"

type AccountDB struct {
	*entity.Account
}

// 初始化account数据库
func InitAccountDB(sqlConsole bool) (*AccountDB, error) {
	config := tentity.Config{
		SqlConsole: &sqlConsole,
	}
	tentity.SetConfig(config)

	db, err := entity.NewAccount()
	if err != nil {
		return nil, zerr.Err_1004002001.New().Sprintf(err.Error())
	}
	return &AccountDB{db}, nil
}

// 保存改变到数据库。
func (db *AccountDB) Save(ctx context.Context) error {
	err := db.Account.Save(ctx)
	if err == context.DeadlineExceeded {
		// 处理超时错误
		tlog.Print("超时")
	}
	if err != nil {
		return AccountSaveErr(err)
	}
	return nil
}

// 关闭数据库。每次使用完数据库后都需要调用该方法关闭数据库。
func (db *AccountDB) Close() {
	db.Account.Close()
}

// DBOpCfg 数据库操作的相关参数
type DBOpCfg struct {
	Context    *context.Context // 数据库操作的上下文，可以设置超时时间等。
	KeepOpen   bool             // 是否保持数据库连接，如果为 true，则数据库连接不会在函数执行后关闭。
	Instance   *AccountDB       // 数据库连接实例。
	SqlConsole bool             // 是否打印SQL语句。
}

func NewDBOpCfg() *DBOpCfg {
	return &DBOpCfg{}
}

type AgentAccessDTO struct {
	AgentAccess *AgentAccessEntity
	DB          *AccountDB
}

func NewAgentAccessDTO(e *entity.AgentAccessEntity, db *AccountDB) *AgentAccessDTO {
	var instance *AgentAccessEntity
	if e != nil {
		instance = newAgentAccessEntity(e)
	}
	return &AgentAccessDTO{
		AgentAccess: instance,
		DB:          db,
	}
}

type AgentAccesssDTO struct {
	AgentAccesss []*AgentAccessEntity
	DB           *AccountDB
}

func NewAgentAccesssDTO(es []*entity.AgentAccessEntity, db *AccountDB) *AgentAccesssDTO {
	instance := make([]*AgentAccessEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newAgentAccessEntity(e))
	}
	return &AgentAccesssDTO{
		AgentAccesss: instance,
		DB:           db,
	}
}

type AgentDTO struct {
	Agent *AgentEntity
	DB    *AccountDB
}

func NewAgentDTO(e *entity.AgentEntity, db *AccountDB) *AgentDTO {
	var instance *AgentEntity
	if e != nil {
		instance = newAgentEntity(e)
	}
	return &AgentDTO{
		Agent: instance,
		DB:    db,
	}
}

type AgentsDTO struct {
	Agents []*AgentEntity
	DB     *AccountDB
}

func NewAgentsDTO(es []*entity.AgentEntity, db *AccountDB) *AgentsDTO {
	instance := make([]*AgentEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newAgentEntity(e))
	}
	return &AgentsDTO{
		Agents: instance,
		DB:     db,
	}
}

type PermissionGrantDTO struct {
	PermissionGrant *PermissionGrantEntity
	DB              *AccountDB
}

func NewPermissionGrantDTO(e *entity.PermissionGrantEntity, db *AccountDB) *PermissionGrantDTO {
	var instance *PermissionGrantEntity
	if e != nil {
		instance = newPermissionGrantEntity(e)
	}
	return &PermissionGrantDTO{
		PermissionGrant: instance,
		DB:              db,
	}
}

type PermissionGrantsDTO struct {
	PermissionGrants []*PermissionGrantEntity
	DB               *AccountDB
}

func NewPermissionGrantsDTO(es []*entity.PermissionGrantEntity, db *AccountDB) *PermissionGrantsDTO {
	instance := make([]*PermissionGrantEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newPermissionGrantEntity(e))
	}
	return &PermissionGrantsDTO{
		PermissionGrants: instance,
		DB:               db,
	}
}

type UserDTO struct {
	User *UserEntity
	DB   *AccountDB
}

func NewUserDTO(e *entity.UserEntity, db *AccountDB) *UserDTO {
	var instance *UserEntity
	if e != nil {
		instance = newUserEntity(e)
	}
	return &UserDTO{
		User: instance,
		DB:   db,
	}
}

type UsersDTO struct {
	Users []*UserEntity
	DB    *AccountDB
}

func NewUsersDTO(es []*entity.UserEntity, db *AccountDB) *UsersDTO {
	instance := make([]*UserEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newUserEntity(e))
	}
	return &UsersDTO{
		Users: instance,
		DB:    db,
	}
}

type UserIdentityDTO struct {
	UserIdentity *UserIdentityEntity
	DB           *AccountDB
}

func NewUserIdentityDTO(e *entity.UserIdentityEntity, db *AccountDB) *UserIdentityDTO {
	var instance *UserIdentityEntity
	if e != nil {
		instance = newUserIdentityEntity(e)
	}
	return &UserIdentityDTO{
		UserIdentity: instance,
		DB:           db,
	}
}

type UserIdentitysDTO struct {
	UserIdentitys []*UserIdentityEntity
	DB            *AccountDB
}

func NewUserIdentitysDTO(es []*entity.UserIdentityEntity, db *AccountDB) *UserIdentitysDTO {
	instance := make([]*UserIdentityEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newUserIdentityEntity(e))
	}
	return &UserIdentitysDTO{
		UserIdentitys: instance,
		DB:            db,
	}
}
