// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"context"

	entity "git.zodileap.com/entity/account_v1"
	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
	zspecs "git.zodileap.com/taurus/zodileap_go_zspecs"
)

// AgentAccess 用于操作agent_access表的仓储实现
type AgentAccess struct {
}

// NewAgentAccess 创建新的AgentAccessRepository实例
func NewAgentAccess() *AgentAccess {
	return &AgentAccess{}
}

// InitDB 初始化数据库
func (r *AgentAccess) InitDB(config *DBOpCfg) error {
	if err := WithInitDB(config); err != nil {
		return zerr.Must(err)
	}
	return nil
}

// Create 创建一条记录
func (r *AgentAccess) Create(config *DBOpCfg, param AgentAccessCreate) (*AgentAccessDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentAccessDTO, error) {
		if err := r.createRemove(param); err != nil {
			return nil, zerr.Must(err)
		}

		e, err := r.createAgentAccess(config, db, param)
		if err != nil {
			return nil, zerr.Must(err)
		}
		if err = db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createAgentAccessDTO(config.KeepOpen, e, db)
	})
}

// CreateList 创建多条记录
func (r *AgentAccess) CreateList(config *DBOpCfg, params []AgentAccessCreate) (*AgentAccesssDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentAccesssDTO, error) {
		var es []*entity.AgentAccessEntity
		for _, param := range params {
			if err := r.createRemove(param); err != nil {
				return nil, zerr.Must(err)
			}
			e, err := r.createAgentAccess(config, db, param)
			if err != nil {
				return nil, zerr.Must(err)
			}
			es = append(es, e)
		}
		if err := db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createAgentAccesssDTO(config.KeepOpen, es, db)
	})
}

// Get 获取单条记录
func (r *AgentAccess) Get(config *DBOpCfg, query AgentAccessQuery, includeDelete bool) (*AgentAccessDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentAccessDTO, error) {
		q := db.AgentAccesss.Where()
		if _, err := r.queryAgentAccess(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		e, err := q.Single(nctx)
		if err != nil {
			return nil, AccountAgentAccessErr.Query(err)
		}
		return r.createAgentAccessDTO(config.KeepOpen, e, db)
	})
}

// GetList 获取多条记录
func (r *AgentAccess) GetList(config *DBOpCfg, query AgentAccessQuery, includeDelete bool) (*AgentAccesssDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentAccesssDTO, error) {
		q := db.AgentAccesss.Where()
		if _, err := r.queryAgentAccess(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		es, err := q.ToList(nctx)
		if err != nil {
			return nil, AccountAgentAccessErr.Query(err)
		}
		return r.createAgentAccesssDTO(config.KeepOpen, es, db)
	})
}

// Update 更新记录
func (r *AgentAccess) Update(config *DBOpCfg, e *AgentAccessEntity, params AgentAccessUpdate) error {
	if err := params.Validate(); err != nil {
		return zerr.Must(err)
	}
	if params.UserId != nil {
		e.SetUserId(*params.UserId)
	}
	if params.AgentId != nil {
		e.SetAgentId(*params.AgentId)
	}
	if params.AccessType != nil {
		e.SetAccessType(*params.AccessType)
	}
	if params.Duration != nil {
		e.SetDuration(*params.Duration)
	}
	if params.Status != nil {
		e.SetStatus(*params.Status)
	}
	return nil
}

// Delete 逻辑删除 - 设置 DeletedAt 字段
func (r *AgentAccess) Delete(config *DBOpCfg, e *AgentAccessEntity) error {
	e.SetDeletedAt(zspecs.CreateDeletedAt())
	return nil
}

// Remove 物理删除 - 从数据库真实删除记录
func (r *AgentAccess) Remove(config *DBOpCfg, e *AgentAccessEntity) error {
	return config.Instance.Remove(e.entity)
}

// Save 保存更改 - 用于在获取记录并修改后执行数据库保存操作
func (r *AgentAccess) Save(config *DBOpCfg) error {
	return WithSave(config, "agent_access")
}

// remove 在新建前删除已经被标记为删除的记录
func (r *AgentAccess) createRemove(param AgentAccessCreate) error {
	return nil
}

// Agent 用于操作agent表的仓储实现
type Agent struct {
}

// NewAgent 创建新的AgentRepository实例
func NewAgent() *Agent {
	return &Agent{}
}

// InitDB 初始化数据库
func (r *Agent) InitDB(config *DBOpCfg) error {
	if err := WithInitDB(config); err != nil {
		return zerr.Must(err)
	}
	return nil
}

// Create 创建一条记录
func (r *Agent) Create(config *DBOpCfg, param AgentCreate) (*AgentDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentDTO, error) {
		if err := r.createRemove(param); err != nil {
			return nil, zerr.Must(err)
		}

		e, err := r.createAgent(config, db, param)
		if err != nil {
			return nil, zerr.Must(err)
		}
		if err = db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createAgentDTO(config.KeepOpen, e, db)
	})
}

// CreateList 创建多条记录
func (r *Agent) CreateList(config *DBOpCfg, params []AgentCreate) (*AgentsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentsDTO, error) {
		var es []*entity.AgentEntity
		for _, param := range params {
			if err := r.createRemove(param); err != nil {
				return nil, zerr.Must(err)
			}
			e, err := r.createAgent(config, db, param)
			if err != nil {
				return nil, zerr.Must(err)
			}
			es = append(es, e)
		}
		if err := db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createAgentsDTO(config.KeepOpen, es, db)
	})
}

// Get 获取单条记录
func (r *Agent) Get(config *DBOpCfg, query AgentQuery, includeDelete bool) (*AgentDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentDTO, error) {
		q := db.Agents.Where()
		if _, err := r.queryAgent(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		e, err := q.Single(nctx)
		if err != nil {
			return nil, AccountAgentErr.Query(err)
		}
		return r.createAgentDTO(config.KeepOpen, e, db)
	})
}

// GetList 获取多条记录
func (r *Agent) GetList(config *DBOpCfg, query AgentQuery, includeDelete bool) (*AgentsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*AgentsDTO, error) {
		q := db.Agents.Where()
		if _, err := r.queryAgent(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		es, err := q.ToList(nctx)
		if err != nil {
			return nil, AccountAgentErr.Query(err)
		}
		return r.createAgentsDTO(config.KeepOpen, es, db)
	})
}

// Update 更新记录
func (r *Agent) Update(config *DBOpCfg, e *AgentEntity, params AgentUpdate) error {
	if err := params.Validate(); err != nil {
		return zerr.Must(err)
	}
	if params.Code != nil {
		e.SetCode(*params.Code)
	}
	if params.Name != nil {
		e.SetName(*params.Name)
	}
	if params.Version != nil {
		e.SetVersion(*params.Version)
	}
	if params.Status != nil {
		e.SetStatus(*params.Status)
	}
	if params.Remark != nil {
		e.SetRemark(*params.Remark)
	}
	return nil
}

// Delete 逻辑删除 - 设置 DeletedAt 字段
func (r *Agent) Delete(config *DBOpCfg, e *AgentEntity) error {
	e.SetDeletedAt(zspecs.CreateDeletedAt())
	return nil
}

// Remove 物理删除 - 从数据库真实删除记录
func (r *Agent) Remove(config *DBOpCfg, e *AgentEntity) error {
	return config.Instance.Remove(e.entity)
}

// Save 保存更改 - 用于在获取记录并修改后执行数据库保存操作
func (r *Agent) Save(config *DBOpCfg) error {
	return WithSave(config, "agent")
}

// remove 在新建前删除已经被标记为删除的记录
func (r *Agent) createRemove(param AgentCreate) error {
	return nil
}

// User 用于操作user_info表的仓储实现
type User struct {
}

// NewUser 创建新的UserRepository实例
func NewUser() *User {
	return &User{}
}

// InitDB 初始化数据库
func (r *User) InitDB(config *DBOpCfg) error {
	if err := WithInitDB(config); err != nil {
		return zerr.Must(err)
	}
	return nil
}

// Create 创建一条记录
func (r *User) Create(config *DBOpCfg, param UserCreate) (*UserDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*UserDTO, error) {
		if err := r.createRemove(param); err != nil {
			return nil, zerr.Must(err)
		}

		e, err := r.createUser(config, db, param)
		if err != nil {
			return nil, zerr.Must(err)
		}
		if err = db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createUserDTO(config.KeepOpen, e, db)
	})
}

// CreateList 创建多条记录
func (r *User) CreateList(config *DBOpCfg, params []UserCreate) (*UsersDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*UsersDTO, error) {
		var es []*entity.UserEntity
		for _, param := range params {
			if err := r.createRemove(param); err != nil {
				return nil, zerr.Must(err)
			}
			e, err := r.createUser(config, db, param)
			if err != nil {
				return nil, zerr.Must(err)
			}
			es = append(es, e)
		}
		if err := db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createUsersDTO(config.KeepOpen, es, db)
	})
}

// Get 获取单条记录
func (r *User) Get(config *DBOpCfg, query UserQuery, includeDelete bool) (*UserDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*UserDTO, error) {
		q := db.Users.Where()
		if _, err := r.queryUser(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		e, err := q.Single(nctx)
		if err != nil {
			return nil, AccountUserErr.Query(err)
		}
		return r.createUserDTO(config.KeepOpen, e, db)
	})
}

// GetList 获取多条记录
func (r *User) GetList(config *DBOpCfg, query UserQuery, includeDelete bool) (*UsersDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AccountDB) (*UsersDTO, error) {
		q := db.Users.Where()
		if _, err := r.queryUser(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		es, err := q.ToList(nctx)
		if err != nil {
			return nil, AccountUserErr.Query(err)
		}
		return r.createUsersDTO(config.KeepOpen, es, db)
	})
}

// Update 更新记录
func (r *User) Update(config *DBOpCfg, e *UserEntity, params UserUpdate) error {
	if err := params.Validate(); err != nil {
		return zerr.Must(err)
	}
	if params.Name != nil {
		e.SetName(*params.Name)
	}
	if params.Email != nil {
		e.SetEmail(*params.Email)
	}
	if params.Phone != nil {
		e.SetPhone(*params.Phone)
	}
	if params.Password != nil {
		e.SetPassword(*params.Password)
	}
	if params.Status != nil {
		e.SetStatus(*params.Status)
	}
	return nil
}

// Delete 逻辑删除 - 设置 DeletedAt 字段
func (r *User) Delete(config *DBOpCfg, e *UserEntity) error {
	e.SetDeletedAt(zspecs.CreateDeletedAt())
	return nil
}

// Remove 物理删除 - 从数据库真实删除记录
func (r *User) Remove(config *DBOpCfg, e *UserEntity) error {
	return config.Instance.Remove(e.entity)
}

// Save 保存更改 - 用于在获取记录并修改后执行数据库保存操作
func (r *User) Save(config *DBOpCfg) error {
	return WithSave(config, "user_info")
}

// remove 在新建前删除已经被标记为删除的记录
func (r *User) createRemove(param UserCreate) error {
	return nil
}
