// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	entity "git.zodileap.com/entity/account_v1"
	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
	zspecs "git.zodileap.com/taurus/zodileap_go_zspecs"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

func (r *AgentAccess) queryAgentAccess(db *AccountDB, q *entity.AgentAccessEntityQuery, query AgentAccessQuery, includeDelete bool) (*entity.AgentAccessEntityQuery, error) {
	hasAnyCondition := false
	if err := query.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	if query.Id != nil {
		q = q.Where(db.AgentAccesss.Id.EQ(query.Id.Int64()))
		hasAnyCondition = true
	}
	if query.Ids != nil {
		Ids := []int64{}
		for _, v := range query.Ids {
			Ids = append(Ids, v.Int64())
		}
		q = q.Where(db.AgentAccesss.Id.In(Ids...))
		hasAnyCondition = true
	}
	if query.UserId != nil {
		q = q.Where(db.AgentAccesss.UserId.EQ(query.UserId.String()))
		hasAnyCondition = true
	}
	if query.UserIds != nil {
		UserIds := []string{}
		for _, v := range query.UserIds {
			UserIds = append(UserIds, v.String())
		}
		q = q.Where(db.AgentAccesss.UserId.In(UserIds...))
		hasAnyCondition = true
	}
	if query.AgentId != nil {
		q = q.Where(db.AgentAccesss.AgentId.EQ(query.AgentId.Int64()))
		hasAnyCondition = true
	}
	if query.AgentIds != nil {
		AgentIds := []int64{}
		for _, v := range query.AgentIds {
			AgentIds = append(AgentIds, v.Int64())
		}
		q = q.Where(db.AgentAccesss.AgentId.In(AgentIds...))
		hasAnyCondition = true
	}
	if query.AccessType != nil {
		q = q.Where(db.AgentAccesss.AccessType.EQ(query.AccessType.Int16()))
		hasAnyCondition = true
	}
	if query.AccessTypes != nil {
		AccessTypes := []int16{}
		for _, v := range query.AccessTypes {
			AccessTypes = append(AccessTypes, v.Int16())
		}
		q = q.Where(db.AgentAccesss.AccessType.In(AccessTypes...))
		hasAnyCondition = true
	}
	if query.Duration != nil {
		q = q.Where(db.AgentAccesss.Duration.EQ(query.Duration.Int32()))
		hasAnyCondition = true
	}
	if query.Durations != nil {
		Durations := []int32{}
		for _, v := range query.Durations {
			Durations = append(Durations, v.Int32())
		}
		q = q.Where(db.AgentAccesss.Duration.In(Durations...))
		hasAnyCondition = true
	}
	if query.Status != nil {
		q = q.Where(db.AgentAccesss.Status.EQ(query.Status.Int16()))
		hasAnyCondition = true
	}
	if query.Statuss != nil {
		Statuss := []int16{}
		for _, v := range query.Statuss {
			Statuss = append(Statuss, v.Int16())
		}
		q = q.Where(db.AgentAccesss.Status.In(Statuss...))
		hasAnyCondition = true
	}

	// 创建时间开始时间
	if query.CreatedAtStart != nil {
		q = q.Where(db.AgentAccesss.CreatedAt.GTE(query.CreatedAtStart.Time()))
		hasAnyCondition = true
	}

	// 创建时间结束时间
	if query.CreatedAtEnd != nil {
		q = q.Where(db.AgentAccesss.CreatedAt.LTE(query.CreatedAtEnd.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间开始时间
	if query.LastAtStart != nil {
		q = q.Where(db.AgentAccesss.LastAt.GTE(query.LastAtStart.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间结束时间
	if query.LastAtEnd != nil {
		q = q.Where(db.AgentAccesss.LastAt.LTE(query.LastAtEnd.Time()))
		hasAnyCondition = true
	}

	// 是否已经逻辑删除
	if !includeDelete {
		if hasAnyCondition {
			q.Where(
				entitysql.And,
				db.AgentAccesss.DeletedAt.IsNull(),
			)
		} else {
			q.Where(
				db.AgentAccesss.DeletedAt.IsNull(),
			)
		}
	}

	// 排序
	if query.ById != nil {
		switch *query.ById {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ById.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ById.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ById.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ById.NullsLast())
		}
	}
	if query.ByUserId != nil {
		switch *query.ByUserId {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ByUserId.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ByUserId.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ByUserId.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ByUserId.NullsLast())
		}
	}
	if query.ByAgentId != nil {
		switch *query.ByAgentId {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ByAgentId.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ByAgentId.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ByAgentId.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ByAgentId.NullsLast())
		}
	}
	if query.ByAccessType != nil {
		switch *query.ByAccessType {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ByAccessType.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ByAccessType.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ByAccessType.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ByAccessType.NullsLast())
		}
	}
	if query.ByDuration != nil {
		switch *query.ByDuration {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ByDuration.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ByDuration.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ByDuration.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ByDuration.NullsLast())
		}
	}
	if query.ByStatus != nil {
		switch *query.ByStatus {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ByStatus.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ByStatus.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ByStatus.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ByStatus.NullsLast())
		}
	}
	if query.ByCreatedAt != nil {
		switch *query.ByCreatedAt {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ByCreatedAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ByCreatedAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ByCreatedAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ByCreatedAt.NullsLast())
		}
	}
	if query.ByLastAt != nil {
		switch *query.ByLastAt {
		case zspecs.OrderByAsc:
			q.Order(db.AgentAccesss.ByLastAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.AgentAccesss.ByLastAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.AgentAccesss.ByLastAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.AgentAccesss.ByLastAt.NullsLast())
		}
	}

	return q, nil
}
func (r *Agent) queryAgent(db *AccountDB, q *entity.AgentEntityQuery, query AgentQuery, includeDelete bool) (*entity.AgentEntityQuery, error) {
	hasAnyCondition := false
	if err := query.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	if query.Id != nil {
		q = q.Where(db.Agents.Id.EQ(query.Id.Int64()))
		hasAnyCondition = true
	}
	if query.Ids != nil {
		Ids := []int64{}
		for _, v := range query.Ids {
			Ids = append(Ids, v.Int64())
		}
		q = q.Where(db.Agents.Id.In(Ids...))
		hasAnyCondition = true
	}
	if query.Code != nil {
		q = q.Where(db.Agents.Code.EQ(query.Code.String()))
		hasAnyCondition = true
	}
	if query.Codes != nil {
		Codes := []string{}
		for _, v := range query.Codes {
			Codes = append(Codes, v.String())
		}
		q = q.Where(db.Agents.Code.In(Codes...))
		hasAnyCondition = true
	}
	if query.Name != nil {
		q = q.Where(db.Agents.Name.EQ(query.Name.String()))
		hasAnyCondition = true
	}
	if query.Names != nil {
		Names := []string{}
		for _, v := range query.Names {
			Names = append(Names, v.String())
		}
		q = q.Where(db.Agents.Name.In(Names...))
		hasAnyCondition = true
	}
	if query.Version != nil {
		q = q.Where(db.Agents.Version.EQ(query.Version.String()))
		hasAnyCondition = true
	}
	if query.Versions != nil {
		Versions := []string{}
		for _, v := range query.Versions {
			Versions = append(Versions, v.String())
		}
		q = q.Where(db.Agents.Version.In(Versions...))
		hasAnyCondition = true
	}
	if query.Status != nil {
		q = q.Where(db.Agents.Status.EQ(query.Status.Int16()))
		hasAnyCondition = true
	}
	if query.Statuss != nil {
		Statuss := []int16{}
		for _, v := range query.Statuss {
			Statuss = append(Statuss, v.Int16())
		}
		q = q.Where(db.Agents.Status.In(Statuss...))
		hasAnyCondition = true
	}
	if query.Remark != nil {
		q = q.Where(db.Agents.Remark.EQ(query.Remark.String()))
		hasAnyCondition = true
	}
	if query.Remarks != nil {
		Remarks := []string{}
		for _, v := range query.Remarks {
			Remarks = append(Remarks, v.String())
		}
		q = q.Where(db.Agents.Remark.In(Remarks...))
		hasAnyCondition = true
	}

	// 创建时间开始时间
	if query.CreatedAtStart != nil {
		q = q.Where(db.Agents.CreatedAt.GTE(query.CreatedAtStart.Time()))
		hasAnyCondition = true
	}

	// 创建时间结束时间
	if query.CreatedAtEnd != nil {
		q = q.Where(db.Agents.CreatedAt.LTE(query.CreatedAtEnd.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间开始时间
	if query.LastAtStart != nil {
		q = q.Where(db.Agents.LastAt.GTE(query.LastAtStart.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间结束时间
	if query.LastAtEnd != nil {
		q = q.Where(db.Agents.LastAt.LTE(query.LastAtEnd.Time()))
		hasAnyCondition = true
	}

	// 是否已经逻辑删除
	if !includeDelete {
		if hasAnyCondition {
			q.Where(
				entitysql.And,
				db.Agents.DeletedAt.IsNull(),
			)
		} else {
			q.Where(
				db.Agents.DeletedAt.IsNull(),
			)
		}
	}

	// 排序
	if query.ById != nil {
		switch *query.ById {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ById.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ById.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ById.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ById.NullsLast())
		}
	}
	if query.ByCode != nil {
		switch *query.ByCode {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ByCode.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ByCode.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ByCode.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ByCode.NullsLast())
		}
	}
	if query.ByName != nil {
		switch *query.ByName {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ByName.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ByName.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ByName.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ByName.NullsLast())
		}
	}
	if query.ByVersion != nil {
		switch *query.ByVersion {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ByVersion.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ByVersion.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ByVersion.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ByVersion.NullsLast())
		}
	}
	if query.ByStatus != nil {
		switch *query.ByStatus {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ByStatus.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ByStatus.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ByStatus.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ByStatus.NullsLast())
		}
	}
	if query.ByRemark != nil {
		switch *query.ByRemark {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ByRemark.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ByRemark.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ByRemark.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ByRemark.NullsLast())
		}
	}
	if query.ByCreatedAt != nil {
		switch *query.ByCreatedAt {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ByCreatedAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ByCreatedAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ByCreatedAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ByCreatedAt.NullsLast())
		}
	}
	if query.ByLastAt != nil {
		switch *query.ByLastAt {
		case zspecs.OrderByAsc:
			q.Order(db.Agents.ByLastAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Agents.ByLastAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Agents.ByLastAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Agents.ByLastAt.NullsLast())
		}
	}

	return q, nil
}
func (r *User) queryUser(db *AccountDB, q *entity.UserEntityQuery, query UserQuery, includeDelete bool) (*entity.UserEntityQuery, error) {
	hasAnyCondition := false
	if err := query.Validate(); err != nil {
		return nil, zerr.Must(err)
	}
	if query.Id != nil {
		q = q.Where(db.Users.Id.EQ(query.Id.String()))
		hasAnyCondition = true
	}
	if query.Ids != nil {
		Ids := []string{}
		for _, v := range query.Ids {
			Ids = append(Ids, v.String())
		}
		q = q.Where(db.Users.Id.In(Ids...))
		hasAnyCondition = true
	}
	if query.Name != nil {
		q = q.Where(db.Users.Name.EQ(query.Name.String()))
		hasAnyCondition = true
	}
	if query.Names != nil {
		Names := []string{}
		for _, v := range query.Names {
			Names = append(Names, v.String())
		}
		q = q.Where(db.Users.Name.In(Names...))
		hasAnyCondition = true
	}
	if query.Email != nil {
		q = q.Where(db.Users.Email.EQ(query.Email.String()))
		hasAnyCondition = true
	}
	if query.Emails != nil {
		Emails := []string{}
		for _, v := range query.Emails {
			Emails = append(Emails, v.String())
		}
		q = q.Where(db.Users.Email.In(Emails...))
		hasAnyCondition = true
	}
	if query.Phone != nil {
		q = q.Where(db.Users.Phone.EQ(query.Phone.String()))
		hasAnyCondition = true
	}
	if query.Phones != nil {
		Phones := []string{}
		for _, v := range query.Phones {
			Phones = append(Phones, v.String())
		}
		q = q.Where(db.Users.Phone.In(Phones...))
		hasAnyCondition = true
	}
	if query.Password != nil {
		q = q.Where(db.Users.Password.EQ(query.Password.String()))
		hasAnyCondition = true
	}
	if query.Passwords != nil {
		Passwords := []string{}
		for _, v := range query.Passwords {
			Passwords = append(Passwords, v.String())
		}
		q = q.Where(db.Users.Password.In(Passwords...))
		hasAnyCondition = true
	}
	if query.Status != nil {
		q = q.Where(db.Users.Status.EQ(query.Status.Int16()))
		hasAnyCondition = true
	}
	if query.Statuss != nil {
		Statuss := []int16{}
		for _, v := range query.Statuss {
			Statuss = append(Statuss, v.Int16())
		}
		q = q.Where(db.Users.Status.In(Statuss...))
		hasAnyCondition = true
	}

	// 创建时间开始时间
	if query.CreatedAtStart != nil {
		q = q.Where(db.Users.CreatedAt.GTE(query.CreatedAtStart.Time()))
		hasAnyCondition = true
	}

	// 创建时间结束时间
	if query.CreatedAtEnd != nil {
		q = q.Where(db.Users.CreatedAt.LTE(query.CreatedAtEnd.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间开始时间
	if query.LastAtStart != nil {
		q = q.Where(db.Users.LastAt.GTE(query.LastAtStart.Time()))
		hasAnyCondition = true
	}

	// 最后更新时间结束时间
	if query.LastAtEnd != nil {
		q = q.Where(db.Users.LastAt.LTE(query.LastAtEnd.Time()))
		hasAnyCondition = true
	}

	// 是否已经逻辑删除
	if !includeDelete {
		if hasAnyCondition {
			q.Where(
				entitysql.And,
				db.Users.DeletedAt.IsNull(),
			)
		} else {
			q.Where(
				db.Users.DeletedAt.IsNull(),
			)
		}
	}

	// 排序
	if query.ById != nil {
		switch *query.ById {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ById.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ById.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ById.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ById.NullsLast())
		}
	}
	if query.ByName != nil {
		switch *query.ByName {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ByName.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ByName.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ByName.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ByName.NullsLast())
		}
	}
	if query.ByEmail != nil {
		switch *query.ByEmail {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ByEmail.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ByEmail.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ByEmail.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ByEmail.NullsLast())
		}
	}
	if query.ByPhone != nil {
		switch *query.ByPhone {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ByPhone.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ByPhone.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ByPhone.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ByPhone.NullsLast())
		}
	}
	if query.ByPassword != nil {
		switch *query.ByPassword {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ByPassword.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ByPassword.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ByPassword.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ByPassword.NullsLast())
		}
	}
	if query.ByStatus != nil {
		switch *query.ByStatus {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ByStatus.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ByStatus.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ByStatus.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ByStatus.NullsLast())
		}
	}
	if query.ByCreatedAt != nil {
		switch *query.ByCreatedAt {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ByCreatedAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ByCreatedAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ByCreatedAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ByCreatedAt.NullsLast())
		}
	}
	if query.ByLastAt != nil {
		switch *query.ByLastAt {
		case zspecs.OrderByAsc:
			q.Order(db.Users.ByLastAt.Asc())
		case zspecs.OrderByDesc:
			q.Order(db.Users.ByLastAt.Desc())
		case zspecs.OrderByNullsFirst:
			q.Order(db.Users.ByLastAt.NullsFirst())
		case zspecs.OrderByNullsLast:
			q.Order(db.Users.ByLastAt.NullsLast())
		}
	}

	return q, nil
}
