// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"encoding/json"
	"strconv"
	"time"

	entity "git.zodileap.com/entity/account_v1"

	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
	zspecs "git.zodileap.com/taurus/zodileap_go_zspecs"
)

// 用户智能体授权实例
type AgentAccessEntity struct {
	entity *entity.AgentAccessEntity
}

func newAgentAccessEntity(entity *entity.AgentAccessEntity) *AgentAccessEntity {
	return &AgentAccessEntity{entity: entity}
}

func (e *AgentAccessEntity) MarshalJSON() ([]byte, error) {
	type tempJSON struct {
		Id         string     `json:"id"`
		UserId     string     `json:"user_id"`
		AgentId    string     `json:"agent_id"`
		AccessType *int16     `json:"access_type"`
		Duration   *int32     `json:"duration"`
		Status     *int16     `json:"status"`
		CreatedAt  *time.Time `json:"created_at"`
		LastAt     *time.Time `json:"last_at"`
		DeletedAt  *time.Time `json:"deleted_at,omitempty"`
	}
	Id := strconv.FormatInt(e.entity.Id.Get(), 10)
	AgentId := strconv.FormatInt(e.entity.AgentId.Get(), 10)
	temp := tempJSON{
		Id:         Id,
		UserId:     e.entity.UserId.Get(),
		AgentId:    AgentId,
		AccessType: e.entity.AccessType.Get(),
		Duration:   e.entity.Duration.Get(),
		Status:     e.entity.Status.Get(),
		CreatedAt:  e.entity.CreatedAt.Get(),
		LastAt:     e.entity.LastAt.Get(),
		DeletedAt:  e.entity.DeletedAt.Get(),
	}

	return json.Marshal(temp)
}

func (e *AgentAccessEntity) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, e.entity)
}
func (e *AgentAccessEntity) Id() zspecs.Id {
	v := e.entity.Id.Get()

	specV := zspecs.NewId(v)
	return *specV

}
func (e *AgentAccessEntity) SetId(v zspecs.Id) {
	e.entity.Id.Set(v.Int64())
}

func (e *AgentAccessEntity) UserId() zspecs.UserId {
	v := e.entity.UserId.Get()

	specV := zspecs.NewUserId(v)
	return *specV

}
func (e *AgentAccessEntity) SetUserId(v zspecs.UserId) {
	e.entity.UserId.Set(v.String())
}

func (e *AgentAccessEntity) AgentId() zspecs.Id {
	v := e.entity.AgentId.Get()

	specV := zspecs.NewId(v)
	return *specV

}
func (e *AgentAccessEntity) SetAgentId(v zspecs.Id) {
	e.entity.AgentId.Set(v.Int64())
}

func (e *AgentAccessEntity) AccessType() *zspecs.Status {
	v := e.entity.AccessType.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewStatus(*v)
	return specV

}
func (e *AgentAccessEntity) SetAccessType(v zspecs.Status) {
	e.entity.AccessType.Set(v.Int16())
}

func (e *AgentAccessEntity) Duration() *zspecs.Duration {
	v := e.entity.Duration.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewDuration(*v)
	return specV

}
func (e *AgentAccessEntity) SetDuration(v zspecs.Duration) {
	e.entity.Duration.Set(v.Int32())
}

func (e *AgentAccessEntity) Status() *zspecs.Status {
	v := e.entity.Status.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewStatus(*v)
	return specV

}
func (e *AgentAccessEntity) SetStatus(v zspecs.Status) {
	e.entity.Status.Set(v.Int16())
}

func (e *AgentAccessEntity) CreatedAt() *zspecs.CreatedAt {
	v := e.entity.CreatedAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewCreatedAt(*v)
	return specV

}
func (e *AgentAccessEntity) SetCreatedAt(v zspecs.CreatedAt) {
	e.entity.CreatedAt.Set(v.Time())
}

func (e *AgentAccessEntity) LastAt() *zspecs.LastAt {
	v := e.entity.LastAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewLastAt(*v)
	return specV

}
func (e *AgentAccessEntity) SetLastAt(v zspecs.LastAt) {
	e.entity.LastAt.Set(v.Time())
}

func (e *AgentAccessEntity) DeletedAt() *zspecs.DeletedAt {
	v := e.entity.DeletedAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewDeletedAt(*v)
	return specV

}
func (e *AgentAccessEntity) SetDeletedAt(v zspecs.DeletedAt) {
	e.entity.DeletedAt.Set(v.Time())
}

// 创建单条用户智能体授权
type AgentAccessCreate struct {
	UserId     zspecs.UserId    `json:"userId" binding:"required"`  // 用户Id (必填)
	AgentId    zspecs.Id        `json:"agentId" binding:"required"` // 智能体Id (必填)
	AccessType *zspecs.Status   `json:"accessType"`                 // 授权类型 (自动填充)
	Duration   *zspecs.Duration `json:"duration"`                   // 有效时长 (自动填充)
	Status     *zspecs.Status   `json:"status"`                     // 状态 (自动填充)
}

// 验证必填字段
func (e *AgentAccessCreate) Validate() error {
	if v, msg := e.UserId.Validate(); !v {
		return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "UserId", e.UserId, msg).SetStatusCodeMsg("UserId", e.UserId, msg)
	}
	if v, msg := e.AgentId.Validate(); !v {
		return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "AgentId", e.AgentId, msg).SetStatusCodeMsg("AgentId", e.AgentId, msg)
	}
	if e.AccessType != nil {
		if v, msg := e.AccessType.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "AccessType", e.AccessType, msg).SetStatusCodeMsg("AccessType", e.AccessType, msg)
		}
	}
	if e.Duration != nil {
		if v, msg := e.Duration.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "Duration", e.Duration, msg).SetStatusCodeMsg("Duration", e.Duration, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "Status", e.Status, msg).SetStatusCodeMsg("Status", e.Status, msg)
		}
	}
	return nil
}

// 查询用户智能体授权
type AgentAccessQuery struct {
	Id             *zspecs.Id        `json:"id" form:"id"`                         // 主键Id
	Ids            []zspecs.Id       `json:"ids" form:"ids"`                       // 主键Id
	ById           *zspecs.OrderBy   `json:"byId" form:"byId"`                     // 按照主键Id排序
	UserId         *zspecs.UserId    `json:"userId" form:"userId"`                 // 用户Id
	UserIds        []zspecs.UserId   `json:"userIds" form:"userIds"`               // 用户Id
	ByUserId       *zspecs.OrderBy   `json:"byUserId" form:"byUserId"`             // 按照用户Id排序
	AgentId        *zspecs.Id        `json:"agentId" form:"agentId"`               // 智能体Id
	AgentIds       []zspecs.Id       `json:"agentIds" form:"agentIds"`             // 智能体Id
	ByAgentId      *zspecs.OrderBy   `json:"byAgentId" form:"byAgentId"`           // 按照智能体Id排序
	AccessType     *zspecs.Status    `json:"accessType" form:"accessType"`         // 授权类型
	AccessTypes    []zspecs.Status   `json:"accessTypes" form:"accessTypes"`       // 授权类型
	ByAccessType   *zspecs.OrderBy   `json:"byAccessType" form:"byAccessType"`     // 按照授权类型排序
	Duration       *zspecs.Duration  `json:"duration" form:"duration"`             // 有效时长
	Durations      []zspecs.Duration `json:"durations" form:"durations"`           // 有效时长
	ByDuration     *zspecs.OrderBy   `json:"byDuration" form:"byDuration"`         // 按照有效时长排序
	Status         *zspecs.Status    `json:"status" form:"status"`                 // 状态
	Statuss        []zspecs.Status   `json:"statuss" form:"statuss"`               // 状态
	ByStatus       *zspecs.OrderBy   `json:"byStatus" form:"byStatus"`             // 按照状态排序
	ByCreatedAt    *zspecs.OrderBy   `json:"byCreatedAt" form:"byCreatedAt"`       // 按照创建数据时间排序
	ByLastAt       *zspecs.OrderBy   `json:"byLastAt" form:"byLastAt"`             // 按照更新数据时间排序
	ByDeletedAt    *zspecs.OrderBy   `json:"byDeletedAt" form:"byDeletedAt"`       // 按照删除数据时间（逻辑删除）排序
	CreatedAtStart *zspecs.CreatedAt `json:"createdAtStart" form:"createdAtStart"` // 创建时间起始
	CreatedAtEnd   *zspecs.CreatedAt `json:"createdAtEnd" form:"createdAtEnd"`     // 创建时间结束
	LastAtStart    *zspecs.LastAt    `json:"lastAtStart" form:"lastAtStart"`       // 最后更新时间起始
	LastAtEnd      *zspecs.LastAt    `json:"lastAtEnd" form:"lastAtEnd"`           // 最后更新时间结束
}

// 验证查询条件
func (e *AgentAccessQuery) Validate() error {
	if e.Id != nil {
		if v, msg := e.Id.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "Id", e.Id, msg)
		}
	}
	if e.UserId != nil {
		if v, msg := e.UserId.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "UserId", e.UserId, msg)
		}
	}
	if e.AgentId != nil {
		if v, msg := e.AgentId.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "AgentId", e.AgentId, msg)
		}
	}
	if e.AccessType != nil {
		if v, msg := e.AccessType.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "AccessType", e.AccessType, msg)
		}
	}
	if e.Duration != nil {
		if v, msg := e.Duration.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "Duration", e.Duration, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "Status", e.Status, msg)
		}
	}
	if e.CreatedAtStart != nil {
		if v, msg := e.CreatedAtStart.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "CreatedAtStart", e.CreatedAtStart, msg)
		}
	}
	if e.CreatedAtEnd != nil {
		if v, msg := e.CreatedAtEnd.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "CreatedAtEnd", e.CreatedAtEnd, msg)
		}
	}
	if e.LastAtStart != nil {
		if v, msg := e.LastAtStart.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "LastAtStart", e.LastAtStart, msg)
		}
	}
	if e.LastAtEnd != nil {
		if v, msg := e.LastAtEnd.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "LastAtEnd", e.LastAtEnd, msg)
		}
	}
	return nil
}

// 更新用户智能体授权
type AgentAccessUpdate struct {
	UserId     *zspecs.UserId   `json:"userId"`     // 用户Id
	AgentId    *zspecs.Id       `json:"agentId"`    // 智能体Id
	AccessType *zspecs.Status   `json:"accessType"` // 授权类型
	Duration   *zspecs.Duration `json:"duration"`   // 有效时长
	Status     *zspecs.Status   `json:"status"`     // 状态
}

// 验证更新字段
func (e *AgentAccessUpdate) Validate() error {
	if e.UserId != nil {
		if v, msg := e.UserId.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "UserId", e.UserId, msg)
		}
	}
	if e.AgentId != nil {
		if v, msg := e.AgentId.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "AgentId", e.AgentId, msg)
		}
	}
	if e.AccessType != nil {
		if v, msg := e.AccessType.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "AccessType", e.AccessType, msg)
		}
	}
	if e.Duration != nil {
		if v, msg := e.Duration.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "Duration", e.Duration, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent_access", "Status", e.Status, msg)
		}
	}
	return nil
}

// 智能体基础信息实例
type AgentEntity struct {
	entity *entity.AgentEntity
}

func newAgentEntity(entity *entity.AgentEntity) *AgentEntity {
	return &AgentEntity{entity: entity}
}

func (e *AgentEntity) MarshalJSON() ([]byte, error) {
	type tempJSON struct {
		Id        string     `json:"id"`
		Code      string     `json:"code"`
		Name      string     `json:"name"`
		Version   *string    `json:"version"`
		Status    *int16     `json:"status"`
		Remark    *string    `json:"remark"`
		CreatedAt *time.Time `json:"created_at"`
		LastAt    *time.Time `json:"last_at"`
		DeletedAt *time.Time `json:"deleted_at,omitempty"`
	}
	Id := strconv.FormatInt(e.entity.Id.Get(), 10)
	temp := tempJSON{
		Id:        Id,
		Code:      e.entity.Code.Get(),
		Name:      e.entity.Name.Get(),
		Version:   e.entity.Version.Get(),
		Status:    e.entity.Status.Get(),
		Remark:    e.entity.Remark.Get(),
		CreatedAt: e.entity.CreatedAt.Get(),
		LastAt:    e.entity.LastAt.Get(),
		DeletedAt: e.entity.DeletedAt.Get(),
	}

	return json.Marshal(temp)
}

func (e *AgentEntity) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, e.entity)
}
func (e *AgentEntity) Id() zspecs.Id {
	v := e.entity.Id.Get()

	specV := zspecs.NewId(v)
	return *specV

}
func (e *AgentEntity) SetId(v zspecs.Id) {
	e.entity.Id.Set(v.Int64())
}

func (e *AgentEntity) Code() zspecs.Code {
	v := e.entity.Code.Get()

	specV := zspecs.NewCode(v)
	return *specV

}
func (e *AgentEntity) SetCode(v zspecs.Code) {
	e.entity.Code.Set(v.String())
}

func (e *AgentEntity) Name() zspecs.Name {
	v := e.entity.Name.Get()

	specV := zspecs.NewName(v)
	return *specV

}
func (e *AgentEntity) SetName(v zspecs.Name) {
	e.entity.Name.Set(v.String())
}

func (e *AgentEntity) Version() *zspecs.Version {
	v := e.entity.Version.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewVersion(*v)
	return specV

}
func (e *AgentEntity) SetVersion(v zspecs.Version) {
	e.entity.Version.Set(v.String())
}

func (e *AgentEntity) Status() *zspecs.Status {
	v := e.entity.Status.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewStatus(*v)
	return specV

}
func (e *AgentEntity) SetStatus(v zspecs.Status) {
	e.entity.Status.Set(v.Int16())
}

func (e *AgentEntity) Remark() *zspecs.Remark {
	v := e.entity.Remark.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewRemark(*v)
	return specV

}
func (e *AgentEntity) SetRemark(v zspecs.Remark) {
	e.entity.Remark.Set(v.String())
}

func (e *AgentEntity) CreatedAt() *zspecs.CreatedAt {
	v := e.entity.CreatedAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewCreatedAt(*v)
	return specV

}
func (e *AgentEntity) SetCreatedAt(v zspecs.CreatedAt) {
	e.entity.CreatedAt.Set(v.Time())
}

func (e *AgentEntity) LastAt() *zspecs.LastAt {
	v := e.entity.LastAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewLastAt(*v)
	return specV

}
func (e *AgentEntity) SetLastAt(v zspecs.LastAt) {
	e.entity.LastAt.Set(v.Time())
}

func (e *AgentEntity) DeletedAt() *zspecs.DeletedAt {
	v := e.entity.DeletedAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewDeletedAt(*v)
	return specV

}
func (e *AgentEntity) SetDeletedAt(v zspecs.DeletedAt) {
	e.entity.DeletedAt.Set(v.Time())
}

// 创建单条智能体基础信息
type AgentCreate struct {
	Code    zspecs.Code     `json:"code" binding:"required"` // 智能体编码 (必填)
	Name    zspecs.Name     `json:"name" binding:"required"` // 智能体名称 (必填)
	Version *zspecs.Version `json:"version"`                 // 版本 (可选)
	Status  *zspecs.Status  `json:"status"`                  // 状态 (自动填充)
	Remark  *zspecs.Remark  `json:"remark"`                  // 备注 (可选)
}

// 验证必填字段
func (e *AgentCreate) Validate() error {
	if v, msg := e.Code.Validate(); !v {
		return zerr.Err_1004002005.New().Sprintf("account", "agent", "Code", e.Code, msg).SetStatusCodeMsg("Code", e.Code, msg)
	}
	if v, msg := e.Name.Validate(); !v {
		return zerr.Err_1004002005.New().Sprintf("account", "agent", "Name", e.Name, msg).SetStatusCodeMsg("Name", e.Name, msg)
	}
	if e.Version != nil {
		if v, msg := e.Version.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Version", e.Version, msg).SetStatusCodeMsg("Version", e.Version, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Status", e.Status, msg).SetStatusCodeMsg("Status", e.Status, msg)
		}
	}
	if e.Remark != nil {
		if v, msg := e.Remark.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Remark", e.Remark, msg).SetStatusCodeMsg("Remark", e.Remark, msg)
		}
	}
	return nil
}

// 查询智能体基础信息
type AgentQuery struct {
	Id             *zspecs.Id        `json:"id" form:"id"`                         // 主键Id
	Ids            []zspecs.Id       `json:"ids" form:"ids"`                       // 主键Id
	ById           *zspecs.OrderBy   `json:"byId" form:"byId"`                     // 按照主键Id排序
	Code           *zspecs.Code      `json:"code" form:"code"`                     // 智能体编码
	Codes          []zspecs.Code     `json:"codes" form:"codes"`                   // 智能体编码
	ByCode         *zspecs.OrderBy   `json:"byCode" form:"byCode"`                 // 按照智能体编码排序
	Name           *zspecs.Name      `json:"name" form:"name"`                     // 智能体名称
	Names          []zspecs.Name     `json:"names" form:"names"`                   // 智能体名称
	ByName         *zspecs.OrderBy   `json:"byName" form:"byName"`                 // 按照智能体名称排序
	Version        *zspecs.Version   `json:"version" form:"version"`               // 版本
	Versions       []zspecs.Version  `json:"versions" form:"versions"`             // 版本
	ByVersion      *zspecs.OrderBy   `json:"byVersion" form:"byVersion"`           // 按照版本排序
	Status         *zspecs.Status    `json:"status" form:"status"`                 // 状态
	Statuss        []zspecs.Status   `json:"statuss" form:"statuss"`               // 状态
	ByStatus       *zspecs.OrderBy   `json:"byStatus" form:"byStatus"`             // 按照状态排序
	Remark         *zspecs.Remark    `json:"remark" form:"remark"`                 // 备注
	Remarks        []zspecs.Remark   `json:"remarks" form:"remarks"`               // 备注
	ByRemark       *zspecs.OrderBy   `json:"byRemark" form:"byRemark"`             // 按照备注排序
	ByCreatedAt    *zspecs.OrderBy   `json:"byCreatedAt" form:"byCreatedAt"`       // 按照创建数据时间排序
	ByLastAt       *zspecs.OrderBy   `json:"byLastAt" form:"byLastAt"`             // 按照更新数据时间排序
	ByDeletedAt    *zspecs.OrderBy   `json:"byDeletedAt" form:"byDeletedAt"`       // 按照删除数据时间（逻辑删除）排序
	CreatedAtStart *zspecs.CreatedAt `json:"createdAtStart" form:"createdAtStart"` // 创建时间起始
	CreatedAtEnd   *zspecs.CreatedAt `json:"createdAtEnd" form:"createdAtEnd"`     // 创建时间结束
	LastAtStart    *zspecs.LastAt    `json:"lastAtStart" form:"lastAtStart"`       // 最后更新时间起始
	LastAtEnd      *zspecs.LastAt    `json:"lastAtEnd" form:"lastAtEnd"`           // 最后更新时间结束
}

// 验证查询条件
func (e *AgentQuery) Validate() error {
	if e.Id != nil {
		if v, msg := e.Id.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Id", e.Id, msg)
		}
	}
	if e.Code != nil {
		if v, msg := e.Code.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Code", e.Code, msg)
		}
	}
	if e.Name != nil {
		if v, msg := e.Name.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Name", e.Name, msg)
		}
	}
	if e.Version != nil {
		if v, msg := e.Version.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Version", e.Version, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Status", e.Status, msg)
		}
	}
	if e.Remark != nil {
		if v, msg := e.Remark.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Remark", e.Remark, msg)
		}
	}
	if e.CreatedAtStart != nil {
		if v, msg := e.CreatedAtStart.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "CreatedAtStart", e.CreatedAtStart, msg)
		}
	}
	if e.CreatedAtEnd != nil {
		if v, msg := e.CreatedAtEnd.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "CreatedAtEnd", e.CreatedAtEnd, msg)
		}
	}
	if e.LastAtStart != nil {
		if v, msg := e.LastAtStart.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "LastAtStart", e.LastAtStart, msg)
		}
	}
	if e.LastAtEnd != nil {
		if v, msg := e.LastAtEnd.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "LastAtEnd", e.LastAtEnd, msg)
		}
	}
	return nil
}

// 更新智能体基础信息
type AgentUpdate struct {
	Code    *zspecs.Code    `json:"code"`    // 智能体编码
	Name    *zspecs.Name    `json:"name"`    // 智能体名称
	Version *zspecs.Version `json:"version"` // 版本
	Status  *zspecs.Status  `json:"status"`  // 状态
	Remark  *zspecs.Remark  `json:"remark"`  // 备注
}

// 验证更新字段
func (e *AgentUpdate) Validate() error {
	if e.Code != nil {
		if v, msg := e.Code.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Code", e.Code, msg)
		}
	}
	if e.Name != nil {
		if v, msg := e.Name.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Name", e.Name, msg)
		}
	}
	if e.Version != nil {
		if v, msg := e.Version.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Version", e.Version, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Status", e.Status, msg)
		}
	}
	if e.Remark != nil {
		if v, msg := e.Remark.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "agent", "Remark", e.Remark, msg)
		}
	}
	return nil
}

// 平台用户实例
type UserEntity struct {
	entity *entity.UserEntity
}

func newUserEntity(entity *entity.UserEntity) *UserEntity {
	return &UserEntity{entity: entity}
}

func (e *UserEntity) MarshalJSON() ([]byte, error) {
	type tempJSON struct {
		Id        string     `json:"id"`
		Name      string     `json:"name"`
		Email     *string    `json:"email"`
		Phone     *string    `json:"phone"`
		Password  *string    `json:"password"`
		Status    *int16     `json:"status"`
		CreatedAt *time.Time `json:"created_at"`
		LastAt    *time.Time `json:"last_at"`
		DeletedAt *time.Time `json:"deleted_at,omitempty"`
	}
	temp := tempJSON{
		Id:        e.entity.Id.Get(),
		Name:      e.entity.Name.Get(),
		Email:     e.entity.Email.Get(),
		Phone:     e.entity.Phone.Get(),
		Password:  e.entity.Password.Get(),
		Status:    e.entity.Status.Get(),
		CreatedAt: e.entity.CreatedAt.Get(),
		LastAt:    e.entity.LastAt.Get(),
		DeletedAt: e.entity.DeletedAt.Get(),
	}

	return json.Marshal(temp)
}

func (e *UserEntity) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, e.entity)
}
func (e *UserEntity) Id() zspecs.UserId {
	v := e.entity.Id.Get()

	specV := zspecs.NewUserId(v)
	return *specV

}
func (e *UserEntity) SetId(v zspecs.UserId) {
	e.entity.Id.Set(v.String())
}

func (e *UserEntity) Name() zspecs.UserName {
	v := e.entity.Name.Get()

	specV := zspecs.NewUserName(v)
	return *specV

}
func (e *UserEntity) SetName(v zspecs.UserName) {
	e.entity.Name.Set(v.String())
}

func (e *UserEntity) Email() *zspecs.Email {
	v := e.entity.Email.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewEmail(*v)
	return specV

}
func (e *UserEntity) SetEmail(v zspecs.Email) {
	e.entity.Email.Set(v.String())
}

func (e *UserEntity) Phone() *zspecs.Phone {
	v := e.entity.Phone.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewPhone(*v)
	return specV

}
func (e *UserEntity) SetPhone(v zspecs.Phone) {
	e.entity.Phone.Set(v.String())
}

func (e *UserEntity) Password() *zspecs.Password {
	v := e.entity.Password.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewPassword(*v)
	return specV

}
func (e *UserEntity) SetPassword(v zspecs.Password) {
	e.entity.Password.Set(v.String())
}

func (e *UserEntity) Status() *zspecs.Status {
	v := e.entity.Status.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewStatus(*v)
	return specV

}
func (e *UserEntity) SetStatus(v zspecs.Status) {
	e.entity.Status.Set(v.Int16())
}

func (e *UserEntity) CreatedAt() *zspecs.CreatedAt {
	v := e.entity.CreatedAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewCreatedAt(*v)
	return specV

}
func (e *UserEntity) SetCreatedAt(v zspecs.CreatedAt) {
	e.entity.CreatedAt.Set(v.Time())
}

func (e *UserEntity) LastAt() *zspecs.LastAt {
	v := e.entity.LastAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewLastAt(*v)
	return specV

}
func (e *UserEntity) SetLastAt(v zspecs.LastAt) {
	e.entity.LastAt.Set(v.Time())
}

func (e *UserEntity) DeletedAt() *zspecs.DeletedAt {
	v := e.entity.DeletedAt.Get()

	if v == nil {
		return nil
	}

	specV := zspecs.NewDeletedAt(*v)
	return specV

}
func (e *UserEntity) SetDeletedAt(v zspecs.DeletedAt) {
	e.entity.DeletedAt.Set(v.Time())
}

// 创建单条平台用户
type UserCreate struct {
	Id       zspecs.UserId    `json:"id" binding:"required"`   // 用户唯一标识 (必填)
	Name     zspecs.UserName  `json:"name" binding:"required"` // 用户名称 (必填)
	Email    *zspecs.Email    `json:"email"`                   // 邮箱 (可选)
	Phone    *zspecs.Phone    `json:"phone"`                   // 手机号 (可选)
	Password *zspecs.Password `json:"password"`                // 登录密码 (可选)
	Status   *zspecs.Status   `json:"status"`                  // 状态 (自动填充)
}

// 验证必填字段
func (e *UserCreate) Validate() error {
	if v, msg := e.Id.Validate(); !v {
		return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Id", e.Id, msg).SetStatusCodeMsg("Id", e.Id, msg)
	}
	if v, msg := e.Name.Validate(); !v {
		return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Name", e.Name, msg).SetStatusCodeMsg("Name", e.Name, msg)
	}
	if e.Email != nil {
		if v, msg := e.Email.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Email", e.Email, msg).SetStatusCodeMsg("Email", e.Email, msg)
		}
	}
	if e.Phone != nil {
		if v, msg := e.Phone.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Phone", e.Phone, msg).SetStatusCodeMsg("Phone", e.Phone, msg)
		}
	}
	if e.Password != nil {
		if v, msg := e.Password.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Password", e.Password, msg).SetStatusCodeMsg("Password", e.Password, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Status", e.Status, msg).SetStatusCodeMsg("Status", e.Status, msg)
		}
	}
	return nil
}

// 查询平台用户
type UserQuery struct {
	Id             *zspecs.UserId    `json:"id" form:"id"`                         // 用户唯一标识
	Ids            []zspecs.UserId   `json:"ids" form:"ids"`                       // 用户唯一标识
	ById           *zspecs.OrderBy   `json:"byId" form:"byId"`                     // 按照用户唯一标识排序
	Name           *zspecs.UserName  `json:"name" form:"name"`                     // 用户名称
	Names          []zspecs.UserName `json:"names" form:"names"`                   // 用户名称
	ByName         *zspecs.OrderBy   `json:"byName" form:"byName"`                 // 按照用户名称排序
	Email          *zspecs.Email     `json:"email" form:"email"`                   // 邮箱
	Emails         []zspecs.Email    `json:"emails" form:"emails"`                 // 邮箱
	ByEmail        *zspecs.OrderBy   `json:"byEmail" form:"byEmail"`               // 按照邮箱排序
	Phone          *zspecs.Phone     `json:"phone" form:"phone"`                   // 手机号
	Phones         []zspecs.Phone    `json:"phones" form:"phones"`                 // 手机号
	ByPhone        *zspecs.OrderBy   `json:"byPhone" form:"byPhone"`               // 按照手机号排序
	Password       *zspecs.Password  `json:"password" form:"password"`             // 登录密码
	Passwords      []zspecs.Password `json:"passwords" form:"passwords"`           // 登录密码
	ByPassword     *zspecs.OrderBy   `json:"byPassword" form:"byPassword"`         // 按照登录密码排序
	Status         *zspecs.Status    `json:"status" form:"status"`                 // 状态
	Statuss        []zspecs.Status   `json:"statuss" form:"statuss"`               // 状态
	ByStatus       *zspecs.OrderBy   `json:"byStatus" form:"byStatus"`             // 按照状态排序
	ByCreatedAt    *zspecs.OrderBy   `json:"byCreatedAt" form:"byCreatedAt"`       // 按照创建数据时间排序
	ByLastAt       *zspecs.OrderBy   `json:"byLastAt" form:"byLastAt"`             // 按照更新数据时间排序
	ByDeletedAt    *zspecs.OrderBy   `json:"byDeletedAt" form:"byDeletedAt"`       // 按照删除数据时间（逻辑删除）排序
	CreatedAtStart *zspecs.CreatedAt `json:"createdAtStart" form:"createdAtStart"` // 创建时间起始
	CreatedAtEnd   *zspecs.CreatedAt `json:"createdAtEnd" form:"createdAtEnd"`     // 创建时间结束
	LastAtStart    *zspecs.LastAt    `json:"lastAtStart" form:"lastAtStart"`       // 最后更新时间起始
	LastAtEnd      *zspecs.LastAt    `json:"lastAtEnd" form:"lastAtEnd"`           // 最后更新时间结束
}

// 验证查询条件
func (e *UserQuery) Validate() error {
	if e.Id != nil {
		if v, msg := e.Id.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Id", e.Id, msg)
		}
	}
	if e.Name != nil {
		if v, msg := e.Name.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Name", e.Name, msg)
		}
	}
	if e.Email != nil {
		if v, msg := e.Email.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Email", e.Email, msg)
		}
	}
	if e.Phone != nil {
		if v, msg := e.Phone.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Phone", e.Phone, msg)
		}
	}
	if e.Password != nil {
		if v, msg := e.Password.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Password", e.Password, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Status", e.Status, msg)
		}
	}
	if e.CreatedAtStart != nil {
		if v, msg := e.CreatedAtStart.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "CreatedAtStart", e.CreatedAtStart, msg)
		}
	}
	if e.CreatedAtEnd != nil {
		if v, msg := e.CreatedAtEnd.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "CreatedAtEnd", e.CreatedAtEnd, msg)
		}
	}
	if e.LastAtStart != nil {
		if v, msg := e.LastAtStart.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "LastAtStart", e.LastAtStart, msg)
		}
	}
	if e.LastAtEnd != nil {
		if v, msg := e.LastAtEnd.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "LastAtEnd", e.LastAtEnd, msg)
		}
	}
	return nil
}

// 更新平台用户
type UserUpdate struct {
	Name     *zspecs.UserName `json:"name"`     // 用户名称
	Email    *zspecs.Email    `json:"email"`    // 邮箱
	Phone    *zspecs.Phone    `json:"phone"`    // 手机号
	Password *zspecs.Password `json:"password"` // 登录密码
	Status   *zspecs.Status   `json:"status"`   // 状态
}

// 验证更新字段
func (e *UserUpdate) Validate() error {
	if e.Name != nil {
		if v, msg := e.Name.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Name", e.Name, msg)
		}
	}
	if e.Email != nil {
		if v, msg := e.Email.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Email", e.Email, msg)
		}
	}
	if e.Phone != nil {
		if v, msg := e.Phone.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Phone", e.Phone, msg)
		}
	}
	if e.Password != nil {
		if v, msg := e.Password.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Password", e.Password, msg)
		}
	}
	if e.Status != nil {
		if v, msg := e.Status.Validate(); !v {
			return zerr.Err_1004002005.New().Sprintf("account", "user_info", "Status", e.Status, msg)
		}
	}
	return nil
}

// 辅助函数：将int64切片转换为string切片
func convertInt64SliceToString1D(slice []int64) []string {
	if slice == nil {
		return nil
	}
	result := make([]string, len(slice))
	for i, v := range slice {
		result[i] = strconv.FormatInt(v, 10)
	}
	return result
}

func convertInt64SliceToString2D(slice [][]int64) [][]string {
	if slice == nil {
		return nil
	}
	result := make([][]string, len(slice))
	for i, v := range slice {
		result[i] = convertInt64SliceToString1D(v)
	}
	return result
}

func convertInt64SliceToString3D(slice [][][]int64) [][][]string {
	if slice == nil {
		return nil
	}
	result := make([][][]string, len(slice))
	for i, v := range slice {
		result[i] = convertInt64SliceToString2D(v)
	}
	return result
}
