// Code generated by taurus_go/entity, DO NOT EDIT.

package agent_code

import (
	"context"

	"git.zodileap.com/entity/agent_code_v1/component_asset"
	"git.zodileap.com/entity/agent_code_v1/internal"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// ComponentAssetEntityDelete is the delete action for the ComponentAssetEntity.
type ComponentAssetEntityDelete struct {
	config     *internal.Dialect
	es         []*ComponentAssetEntity
	predicates []entitysql.PredicateFunc
}

// newComponentAssetEntityDelete creates a new ComponentAssetEntityDelete.
func newComponentAssetEntityDelete(c *internal.Dialect, es ...*ComponentAssetEntity) *ComponentAssetEntityDelete {
	return &ComponentAssetEntityDelete{
		config: c,
		es:     es,
	}
}

// Where adds a predicate to the delete action.
func (o *ComponentAssetEntityDelete) Where(predicates ...entitysql.PredicateFunc) *ComponentAssetEntityDelete {
	o.predicates = append(o.predicates, predicates...)
	return o
}

func (o *ComponentAssetEntityDelete) delete(ctx context.Context, tx dialect.Tx) error {
	return o.sqlDelete(ctx, tx)
}

func (o *ComponentAssetEntityDelete) sqlDelete(ctx context.Context, tx dialect.Tx) error {
	var (
		spec, err = o.deleteSpec()
		affected  = int64(0)
	)
	if err != nil {
		return err
	}
	spec.Affected = &affected
	if err := entitysql.NewDelete(ctx, tx, spec); err != nil {
		return err
	}
	for _, e := range o.es {
		if err := e.setState(entity.Detached); err != nil {
			return err
		}
	}
	return nil
}

func (o *ComponentAssetEntityDelete) deleteSpec() (*entitysql.DeleteSpec, error) {
	spec := entitysql.NewDeleteSpec(component_asset.Entity)
	if ps := o.predicates; len(ps) > 0 {
		spec.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	predId := &component_asset.PredId{}
	if o.predicates == nil {
		o.predicates = make([]entitysql.PredicateFunc, 0, len(o.es))
	}
	for i, e := range o.es {
		if i >= 1 {
			o.predicates = append(o.predicates, entitysql.Or)
		}
		o.predicates = append(o.predicates, predId.EQ(e.Id.Get()))
	}
	if ps := o.predicates; len(ps) > 0 {
		spec.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	return spec, nil
}
