// Code generated by taurus_go/entity, DO NOT EDIT.

package agent_code

import (
	"context"
	"time"

	"git.zodileap.com/entity/agent_code_v1/internal"
	"git.zodileap.com/entity/agent_code_v1/module_asset"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// moduleassetentityBuilder is a builder for the ModuleAssetEntity entity.
//
// The builder is used to create, update, and delete ModuleAssetEntity entities.
type moduleassetentityBuilder struct {
	config    *moduleassetentityConfig
	tracker   entity.Tracker
	Id        module_asset.PredId        // Id 主键Id
	OwnerId   module_asset.PredOwnerId   // OwnerId 所属用户Id
	Name      module_asset.PredName      // Name 模块名称
	Path      module_asset.PredPath      // Path 源码路径
	Version   module_asset.PredVersion   // Version 版本
	Status    module_asset.PredStatus    // Status 状态
	Remark    module_asset.PredRemark    // Remark 备注
	CreatedAt module_asset.PredCreatedAt // CreatedAt 创建数据时间
	LastAt    module_asset.PredLastAt    // LastAt 更新数据时间
	DeletedAt module_asset.PredDeletedAt // DeletedAt 删除数据时间（逻辑删除）
	// ById configures the query to sort results based on the 'id' field of the entity.
	// Sorting entities in ascending order by default.
	ById module_asset.ById
	// ByOwnerId configures the query to sort results based on the 'owner_id' field of the entity.
	// Sorting entities in ascending order by default.
	ByOwnerId module_asset.ByOwnerId
	// ByName configures the query to sort results based on the 'name' field of the entity.
	// Sorting entities in ascending order by default.
	ByName module_asset.ByName
	// ByPath configures the query to sort results based on the 'path' field of the entity.
	// Sorting entities in ascending order by default.
	ByPath module_asset.ByPath
	// ByVersion configures the query to sort results based on the 'version' field of the entity.
	// Sorting entities in ascending order by default.
	ByVersion module_asset.ByVersion
	// ByStatus configures the query to sort results based on the 'status' field of the entity.
	// Sorting entities in ascending order by default.
	ByStatus module_asset.ByStatus
	// ByRemark configures the query to sort results based on the 'remark' field of the entity.
	// Sorting entities in ascending order by default.
	ByRemark module_asset.ByRemark
	// ByCreatedAt configures the query to sort results based on the 'created_at' field of the entity.
	// Sorting entities in ascending order by default.
	ByCreatedAt module_asset.ByCreatedAt
	// ByLastAt configures the query to sort results based on the 'last_at' field of the entity.
	// Sorting entities in ascending order by default.
	ByLastAt module_asset.ByLastAt
	// ByDeletedAt configures the query to sort results based on the 'deleted_at' field of the entity.
	// Sorting entities in ascending order by default.
	ByDeletedAt module_asset.ByDeletedAt
}

// newModuleAssetEntityBuilder creates a new ModuleAssetEntityBuilder .
func newModuleAssetEntityBuilder(c *moduleassetentityConfig, t entity.Tracker) *moduleassetentityBuilder {
	return &moduleassetentityBuilder{
		config:  c,
		tracker: t,
	}
}

// Create creates a new UserEntity，and add it to the tracker.
// Required parameters are fields that have no default value but are required,
// and options are fields that can be left empty by calling WithFieldName.
func (b *moduleassetentityBuilder) Create(name string, options ...func(*ModuleAssetEntity)) (*ModuleAssetEntity, error) {
	e := b.config.New()
	switch t := e.(type) {
	case *ModuleAssetEntity:
		return t.create(name, options...)
	default:
		return nil, entity.Err_0100030006
	}
}

func (b *moduleassetentityBuilder) Remove(e *ModuleAssetEntity) error {
	if e.config.Mutation == nil {
		return nil
	}
	return e.remove()
}

// First returns the first ModuleAssetEntity.
func (s *moduleassetentityBuilder) First(ctx context.Context) (*ModuleAssetEntity, error) {
	query := s.initQuery()
	return query.First(ctx)
}

func (s *moduleassetentityBuilder) ToList(ctx context.Context) ([]*ModuleAssetEntity, error) {
	query := s.initQuery()
	return query.ToList(ctx)
}

func (s *moduleassetentityBuilder) Include(rels ...moduleassetentityRel) *ModuleAssetEntityQuery {
	query := s.initQuery()
	return query.Include(rels...)
}

func (s *moduleassetentityBuilder) Order(o ...module_asset.OrderTerm) *ModuleAssetEntityQuery {
	query := s.initQuery()
	return query.Order(o...)
}

func (s *moduleassetentityBuilder) Where(conditions ...entitysql.PredicateFunc) *ModuleAssetEntityQuery {
	query := s.initQuery()
	return query.Where(conditions...)
}

// WithId sets the "id" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithId(id int64) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.Id.Set(id)
	}
}

// WithOwnerId sets the "owner_id" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithOwnerId(ownerid string) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.OwnerId.Set(ownerid)
	}
}

// WithPath sets the "path" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithPath(path string) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.Path.Set(path)
	}
}

// WithVersion sets the "version" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithVersion(version string) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.Version.Set(version)
	}
}

// WithStatus sets the "status" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithStatus(status int16) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.Status.Set(status)
	}
}

// WithRemark sets the "remark" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithRemark(remark string) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.Remark.Set(remark)
	}
}

// WithCreatedAt sets the "created_at" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithCreatedAt(createdat time.Time) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.CreatedAt.Set(createdat)
	}
}

// WithLastAt sets the "last_at" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithLastAt(lastat time.Time) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.LastAt.Set(lastat)
	}
}

// WithDeletedAt sets the "deleted_at" field of the ModuleAssetEntity.
func (s *moduleassetentityBuilder) WithDeletedAt(deletedat time.Time) func(*ModuleAssetEntity) {
	return func(e *ModuleAssetEntity) {
		e.DeletedAt.Set(deletedat)
	}
}

// Exec executes all the moduleassetentityMutations for the ModuleAssetEntity.
func (s *moduleassetentityBuilder) Exec(ctx context.Context, tx dialect.Tx) error {
	if len(s.config.moduleassetentityMutations.Addeds) > 0 {
		e := s.config.moduleassetentityMutations.Get(entity.Added)
		n := newModuleAssetEntityCreate(s.config.Dialect, e...)
		if err := n.create(ctx, tx); err != nil {
			return err
		}
	}
	if len(s.config.moduleassetentityMutations.Modifieds) > 0 {
		e := s.config.moduleassetentityMutations.Get(entity.Modified)
		n := newModuleAssetEntityUpdate(s.config.Dialect, e...)
		if err := n.update(ctx, tx); err != nil {
			return err
		}
	}
	if len(s.config.moduleassetentityMutations.Deleteds) > 0 {
		e := s.config.moduleassetentityMutations.Get(entity.Deleted)
		n := newModuleAssetEntityDelete(s.config.Dialect, e...)
		if err := n.delete(ctx, tx); err != nil {
			return err
		}
	}
	return nil
}

func (s *moduleassetentityBuilder) initQuery() *ModuleAssetEntityQuery {
	return newModuleAssetEntityQuery(s.config.Dialect, s.tracker, s.config.moduleassetentityMutations)
}

// moduleassetentityMutations is a collection of ModuleAssetEntity mutation.
type moduleassetentityMutations struct {
	Detacheds  map[string]*ModuleAssetEntity
	Unchangeds map[string]*ModuleAssetEntity
	Deleteds   map[string]*ModuleAssetEntity
	Modifieds  map[string]*ModuleAssetEntity
	Addeds     map[string]*ModuleAssetEntity
}

// newModuleAssetEntityMutations creates a new mutations.
func newModuleAssetEntityMutations() *moduleassetentityMutations {
	return &moduleassetentityMutations{
		Detacheds:  make(map[string]*ModuleAssetEntity),
		Unchangeds: make(map[string]*ModuleAssetEntity),
		Deleteds:   make(map[string]*ModuleAssetEntity),
		Modifieds:  make(map[string]*ModuleAssetEntity),
		Addeds:     make(map[string]*ModuleAssetEntity),
	}
}

// Get returns all the ModuleAssetEntity in the specified state.
func (ms *moduleassetentityMutations) Get(state entity.EntityState) []*ModuleAssetEntity {
	switch state {
	case entity.Detached:
		s := make([]*ModuleAssetEntity, 0, len(ms.Detacheds))
		for _, m := range ms.Detacheds {
			s = append(s, m)
		}
		return s
	case entity.Unchanged:
		s := make([]*ModuleAssetEntity, 0, len(ms.Unchangeds))
		for _, m := range ms.Unchangeds {
			s = append(s, m)
		}
		return s
	case entity.Deleted:
		s := make([]*ModuleAssetEntity, 0, len(ms.Deleteds))
		for _, m := range ms.Deleteds {
			s = append(s, m)
		}
		return s
	case entity.Modified:
		s := make([]*ModuleAssetEntity, 0, len(ms.Modifieds))
		for _, m := range ms.Modifieds {
			s = append(s, m)
		}
		return s
	case entity.Added:
		s := make([]*ModuleAssetEntity, 0, len(ms.Addeds))
		for _, m := range ms.Addeds {
			s = append(s, m)
		}
		return s
	}
	return nil
}

// SetEntityState sets the state of the entity.
func (ms *moduleassetentityMutations) SetEntityState(e *ModuleAssetEntity, state entity.EntityState) error {
	m := e.config.Mutation
	ms.set(e, state)
	if err := internal.SetEntityState(m, state); err != nil {
		return err
	}
	return nil
}

// ChangeEntityState attempts to set the desired entity state,
// but will not do so if the conditions are not met.
func (ms *moduleassetentityMutations) ChangeEntityState(m *entity.Mutation, state entity.EntityState) {
	e := ms.getEntity(m)
	ms.set(e, state)
	if err := internal.SetEntityState(m, state); err != nil {
		return
	}
}

// getEntity returns the entity in the specified state.
func (ms *moduleassetentityMutations) getEntity(m *entity.Mutation) *ModuleAssetEntity {
	key := m.Key()
	switch m.State() {
	case entity.Detached:
		return ms.Detacheds[key]
	case entity.Unchanged:
		return ms.Unchangeds[key]
	case entity.Deleted:
		return ms.Deleteds[key]
	case entity.Modified:
		return ms.Modifieds[key]
	case entity.Added:
		return ms.Addeds[key]
	}
	return nil
}

// Set sets the entity in the specified state.
func (ms *moduleassetentityMutations) set(e *ModuleAssetEntity, state entity.EntityState) {
	m := e.config.Mutation
	key := m.Key()
	switch m.State() {
	case entity.Detached:
		delete(ms.Detacheds, key)
	case entity.Unchanged:
		delete(ms.Unchangeds, key)
	case entity.Deleted:
		delete(ms.Deleteds, key)
	case entity.Modified:
		delete(ms.Modifieds, key)
	case entity.Added:
		delete(ms.Addeds, key)
	}
	if state >= 0 {
		switch state {
		case entity.Detached:
			ms.Detacheds[key] = e
		case entity.Unchanged:
			ms.Unchangeds[key] = e
		case entity.Deleted:
			ms.Deleteds[key] = e
		case entity.Modified:
			ms.Modifieds[key] = e
		case entity.Added:
			ms.Addeds[key] = e
		}
	}
}
