// Code generated by taurus_go/entity, DO NOT EDIT.

package agent_3d

import (
	"fmt"
	"time"

	"git.zodileap.com/entity/agent_3d_v1/dcc_binding"
	"git.zodileap.com/entity/agent_3d_v1/internal"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// DCC软件绑定
type DccBindingEntity struct {
	internal.Entity `json:"-"`
	config          *dccbindingentityConfig
	Id              *dccBinding_Id             `json:"id"`                   // Id 主键Id
	UserId          *dccBinding_UserId         `json:"user_id"`              // UserId 用户Id
	Software        *dccBinding_Software       `json:"software"`             // Software 软件标识
	Version         *dccBinding_Version        `json:"version"`              // Version 软件版本
	ExecutablePath  *dccBinding_ExecutablePath `json:"executable_path"`      // ExecutablePath 可执行文件路径
	Status          *dccBinding_Status         `json:"status"`               // Status 状态
	CreatedAt       *dccBinding_CreatedAt      `json:"created_at"`           // CreatedAt 创建数据时间
	LastAt          *dccBinding_LastAt         `json:"last_at"`              // LastAt 更新数据时间
	DeletedAt       *dccBinding_DeletedAt      `json:"deleted_at,omitempty"` // DeletedAt 删除数据时间（逻辑删除）
}

// dccbindingentityConfig holds the configuration for the DccBindingEntity.
type dccbindingentityConfig struct {
	internal.EntityConfig
	*internal.Dialect
	*entity.Mutation
	*dccbindingentityMutations
	name string
}

func newDccBindingEntityConfig(c *internal.Dialect) *dccbindingentityConfig {
	return &dccbindingentityConfig{
		Dialect:                   c,
		dccbindingentityMutations: newDccBindingEntityMutations(),
		name:                      "dcc_binding",
	}
}

// New creates a new DccBindingEntity, but does not add tracking.
func (c *dccbindingentityConfig) New() internal.Entity {
	b := entity.NewMutation(entity.Detached)
	e := &DccBindingEntity{
		config: &dccbindingentityConfig{
			Mutation:                  b,
			Dialect:                   c.Dialect,
			dccbindingentityMutations: c.dccbindingentityMutations,
		},
	}
	e.setState(entity.Detached)
	e.Id = newDccBinding_Id(e.config)
	e.UserId = newDccBinding_UserId(e.config)
	e.Software = newDccBinding_Software(e.config)
	e.Version = newDccBinding_Version(e.config)
	e.ExecutablePath = newDccBinding_ExecutablePath(e.config)
	e.Status = newDccBinding_Status(e.config)
	e.CreatedAt = newDccBinding_CreatedAt(e.config)
	e.LastAt = newDccBinding_LastAt(e.config)
	e.DeletedAt = newDccBinding_DeletedAt(e.config)
	return e
}

func (c *dccbindingentityConfig) Desc() internal.EntityConfigDesc {
	return internal.EntityConfigDesc{
		Name: c.name,
	}
}

// String implements the fmt.Stringer interface.
func (e *DccBindingEntity) String() string {
	return fmt.Sprintf("{ Id: %v, UserId: %v, Software: %v, Version: %v, ExecutablePath: %v, Status: %v, CreatedAt: %v, LastAt: %v, DeletedAt: %v}",
		e.Id,
		e.UserId,
		e.Software,
		e.Version,
		e.ExecutablePath,
		e.Status,
		e.CreatedAt,
		e.LastAt,
		e.DeletedAt,
	)
}

// State returns the state of the DccBindingEntity.
func (e *DccBindingEntity) State() entity.EntityState {
	return e.config.State()
}

// remove removes the DccBindingEntity from the database.
func (e *DccBindingEntity) remove() error {
	return e.setState(entity.Deleted)
}

// create creates a new DccBindingEntity and adds tracking.
func (e *DccBindingEntity) create(user_id string, software string, options ...func(*DccBindingEntity)) (*DccBindingEntity, error) {
	e.setState(entity.Added)
	e.UserId.Set(user_id)
	e.Software.Set(software)
	for _, option := range options {
		option(e)
	}
	return e, nil
}

// setUnchanged sets the state of the DccBindingEntity to unchanged.
func (e *DccBindingEntity) setUnchanged() error {
	return e.setState(entity.Unchanged)
}

// setState sets the state of the DccBindingEntity.
func (e *DccBindingEntity) setState(state entity.EntityState) error {
	return e.config.dccbindingentityMutations.SetEntityState(e, state)
}

// scan scans the database for the DccBindingEntity.
func (e *DccBindingEntity) scan(fields []entitysql.ScannerField) []any {
	if len(fields) == 0 {
		args := make([]any, len(dcc_binding.Columns))
		for i, c := range dcc_binding.Columns {
			switch c.String() {
			case dcc_binding.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case dcc_binding.FieldUserId.Name.String():
				v := e.UserId
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldSoftware.Name.String():
				v := e.Software
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldVersion.Name.String():
				v := e.Version
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldExecutablePath.Name.String():
				v := e.ExecutablePath
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case dcc_binding.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case dcc_binding.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case dcc_binding.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	} else {
		args := make([]any, len(fields))
		for i := range fields {
			switch fields[i].String() {
			case dcc_binding.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case dcc_binding.FieldUserId.Name.String():
				v := e.UserId
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldSoftware.Name.String():
				v := e.Software
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldVersion.Name.String():
				v := e.Version
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldExecutablePath.Name.String():
				v := e.ExecutablePath
				v.Set(*new(string))
				args[i] = v
			case dcc_binding.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case dcc_binding.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case dcc_binding.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case dcc_binding.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	}
}

func (e *DccBindingEntity) createRel(buidler *entitysql.ScannerBuilder, scanner *internal.QueryScanner) {
	switch scanner.Config.Desc().Name {
	}
}

func mergeDccBindingEntity(es []*DccBindingEntity, e *DccBindingEntity) []*DccBindingEntity {
	if e == nil {
		return es
	}
	if len(es) == 0 {
		es = append(es, e)
	} else {
		v := es[len(es)-1]

		if v.Id.Get() == e.Id.Get() {
		} else {
			es = append(es, e)
		}
	}
	return es
}
