// Code generated by taurus_go/entity, DO NOT EDIT.

package agent_3d

import (
	"context"

	"git.zodileap.com/entity/agent_3d_v1/internal"
	"git.zodileap.com/entity/agent_3d_v1/model_task"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// ModelTaskEntityQuery is the query action for the ModelTaskEntity.
type ModelTaskEntityQuery struct {
	config       *modeltaskentityConfig
	ctx          *entitysql.QueryContext
	predicates   []entitysql.PredicateFunc
	rels         []modeltaskentityRel
	order        []model_task.OrderTerm
	scanner      []*internal.QueryScanner
	scannerTotal int
}

// First returns the first result of the query.
func (o *ModelTaskEntityQuery) First(ctx context.Context) (*ModelTaskEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// newModelTaskEntityQuery creates a new ModelTaskEntityQuery.
func newModelTaskEntityQuery(c *internal.Dialect, t entity.Tracker, ms *modeltaskentityMutations) *ModelTaskEntityQuery {
	return &ModelTaskEntityQuery{
		config: &modeltaskentityConfig{
			Dialect:                  c,
			modeltaskentityMutations: ms,
		},
		ctx:          &entitysql.QueryContext{},
		predicates:   []entitysql.PredicateFunc{},
		rels:         []modeltaskentityRel{},
		order:        []model_task.OrderTerm{},
		scanner:      []*internal.QueryScanner{},
		scannerTotal: 0,
	}
}

func (o *ModelTaskEntityQuery) Where(predicates ...entitysql.PredicateFunc) *ModelTaskEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *ModelTaskEntityQuery) Limit(limit int) *ModelTaskEntityQuery {
	o.ctx.Limit = &limit
	return o
}

func (o *ModelTaskEntityQuery) Order(term ...model_task.OrderTerm) *ModelTaskEntityQuery {
	o.order = append(o.order, term...)
	return o
}

func (o *ModelTaskEntityQuery) Include(rels ...modeltaskentityRel) *ModelTaskEntityQuery {
	o.rels = append(o.rels, rels...)
	return o
}

// ToList returns the list of results of the query.
func (o *ModelTaskEntityQuery) ToList(ctx context.Context) ([]*ModelTaskEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *ModelTaskEntityQuery) Single(ctx context.Context) (*ModelTaskEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *ModelTaskEntityQuery) sqlSingle(ctx context.Context) (*ModelTaskEntity, error) {
	var (
		spec = o.querySpec()
		res  *ModelTaskEntity
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *ModelTaskEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan(fields)...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}
			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = e
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	if res != nil {
		if err := res.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		r.reset()
	}
	return res, nil
}

func (o *ModelTaskEntityQuery) sqlAll(ctx context.Context) ([]*ModelTaskEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*ModelTaskEntity{}
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *ModelTaskEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan([]entitysql.ScannerField{})...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}

			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = mergeModelTaskEntity(res, e)
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		rel := r
		rel.reset()
	}
	return res, nil
}

func (o *ModelTaskEntityQuery) querySpec() *entitysql.QuerySpec {
	s := entitysql.NewQuerySpec(model_task.Entity, model_task.Columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s = entitysql.NewQuerySpec(model_task.Entity, fields)
	}
	for i := range s.Entity.Columns {
		switch model_task.Columns[i] {
		case model_task.FieldId.Name:
			var a *modelTask_Id = new(modelTask_Id)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldId.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case model_task.FieldUserId.Name:
			var a *modelTask_UserId = new(modelTask_UserId)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldUserId.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case model_task.FieldPrompt.Name:
			var a *modelTask_Prompt = new(modelTask_Prompt)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldPrompt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case model_task.FieldStatus.Name:
			var a *modelTask_Status = new(modelTask_Status)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldStatus.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case model_task.FieldResultPath.Name:
			var a *modelTask_ResultPath = new(modelTask_ResultPath)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldResultPath.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case model_task.FieldCreatedAt.Name:
			var a *modelTask_CreatedAt = new(modelTask_CreatedAt)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldCreatedAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case model_task.FieldLastAt.Name:
			var a *modelTask_LastAt = new(modelTask_LastAt)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldLastAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case model_task.FieldDeletedAt.Name:
			var a *modelTask_DeletedAt = new(modelTask_DeletedAt)
			fieldSpace := entitysql.NewFieldSpec(model_task.FieldDeletedAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		}
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	if rs := o.rels; len(rs) > 0 {
		s.Rels = make([]entitysql.Relation, 0, len(rs))
		s.Orders = append(s.Orders, model_task.ByPrimary)
		for _, r := range rs {
			rel := r
			s.Rels = append(s.Rels, func(s *entitysql.Selector) {
				o.scanner = o.addRels(s, s.Table(), rel, o.scanner)
			})
		}
	}
	for _, o := range o.order {
		s.Orders = append(s.Orders, func(order *entitysql.Order) {
			o.Apply(order)
		})
	}
	return s
}

func (o *ModelTaskEntityQuery) addRels(s *entitysql.Selector, t *entitysql.SelectTable, rel rel, scanner []*internal.QueryScanner) []*internal.QueryScanner {
	desc, children, config := rel.Desc()
	join := entitysql.AddRelBySelector(s, t, desc)
	_, tableNum := join.GetAs()
	qs := internal.QueryScanner{Config: config, Children: []*internal.QueryScanner{}, TableNum: tableNum}
	scanner = append(scanner, &qs)
	o.scannerTotal++
	if len(children) > 0 {
		for _, c := range children {
			qs.Children = o.addRels(s, join, c, qs.Children)
		}
	}
	return scanner
}
