// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import (
	"context"

	"git.zodileap.com/entity/enterprise_v1/enterprise_role"
	"git.zodileap.com/entity/enterprise_v1/internal"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// EnterpriseRoleEntityCreate is the create action for the EnterpriseRoleEntity.
type EnterpriseRoleEntityCreate struct {
	config *internal.Dialect
	es     []*EnterpriseRoleEntity
}

// newEnterpriseRoleEntityCreate creates a new EnterpriseRoleEntityCreate.
func newEnterpriseRoleEntityCreate(c *internal.Dialect, es ...*EnterpriseRoleEntity) *EnterpriseRoleEntityCreate {
	return &EnterpriseRoleEntityCreate{
		config: c,
		es:     es,
	}
}

// create executes the create action.
func (o *EnterpriseRoleEntityCreate) create(ctx context.Context, tx dialect.Tx) error {
	return o.sqlCreate(ctx, tx)
}

// sqlCreate executes the SQL create action.
func (o *EnterpriseRoleEntityCreate) sqlCreate(ctx context.Context, tx dialect.Tx) error {
	var (
		spec, err = o.createSpec()
		res       = o.es
		cursor    = 0
	)
	if err != nil {
		return err
	}
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := res[cursor]
		cursor++
		args := e.scan(fields)
		if err := rows.Scan(args...); err != nil {
			return err
		} else {
			res = append(res, e)
			return e.setUnchanged()
		}
	}
	return entitysql.NewCreate(ctx, tx, spec)
}

// createSpec creates the create action spec. It checks for required fields and sets the returning fields.
func (o *EnterpriseRoleEntityCreate) createSpec() (*entitysql.CreateSpec, error) {
	returning := []entitysql.FieldName{
		enterprise_role.FieldId.Name,
		enterprise_role.FieldStatus.Name,
		enterprise_role.FieldCreatedAt.Name,
		enterprise_role.FieldLastAt.Name,
		enterprise_role.FieldDeletedAt.Name,
	}
	entity := enterprise_role.Entity
	columns := enterprise_role.Columns
	spec := entitysql.NewCreateSpec(entity, columns)
	spec.Fields = make([][]*entitysql.FieldSpec, 0, len(o.es))
	for _, e := range o.es {
		fields := make([]*entitysql.FieldSpec, 0, len(enterprise_role.Columns))
		for j := range enterprise_role.Columns {
			switch enterprise_role.Columns[j] {
			case enterprise_role.FieldId.Name:
				v, err := e.Id.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldId.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Id.SqlFormatParam()
				fieldSpace.Default = true
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldEnterpriseId.Name:
				v, err := e.EnterpriseId.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				if err := spec.CheckRequired(o.config.Driver.Dialect(), enterprise_role.FieldEnterpriseId.Name, e.EnterpriseId); err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldEnterpriseId.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.EnterpriseId.SqlFormatParam()
				fieldSpace.Default = false
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldCode.Name:
				v, err := e.Code.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				if err := spec.CheckRequired(o.config.Driver.Dialect(), enterprise_role.FieldCode.Name, e.Code); err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldCode.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Code.SqlFormatParam()
				fieldSpace.Default = false
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldName.Name:
				v, err := e.Name.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				if err := spec.CheckRequired(o.config.Driver.Dialect(), enterprise_role.FieldName.Name, e.Name); err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldName.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Name.SqlFormatParam()
				fieldSpace.Default = false
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldStatus.Name:
				v, err := e.Status.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldStatus.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Status.SqlFormatParam()
				fieldSpace.Default = true
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldRemark.Name:
				v, err := e.Remark.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldRemark.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Remark.SqlFormatParam()
				fieldSpace.Default = false
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldCreatedAt.Name:
				v, err := e.CreatedAt.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldCreatedAt.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.CreatedAt.SqlFormatParam()
				fieldSpace.Default = true
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldLastAt.Name:
				v, err := e.LastAt.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldLastAt.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.LastAt.SqlFormatParam()
				fieldSpace.Default = true
				fields = append(fields, &fieldSpace)
			case enterprise_role.FieldDeletedAt.Name:
				v, err := e.DeletedAt.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(enterprise_role.FieldDeletedAt.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.DeletedAt.SqlFormatParam()
				fieldSpace.Default = true
				fields = append(fields, &fieldSpace)
			}
		}
		spec.Fields = append(spec.Fields, fields)
	}
	spec.Returning = returning
	return spec, nil
}
