// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import (
	"time"

	"git.zodileap.com/entity/enterprise_v1/enterprise_role"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/field"
)

// enterpriseRole_Id is Id field
type enterpriseRole_Id struct {
	field.IntStorage[int64]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_Id creates a new enterpriseRole_Id
func newEnterpriseRole_Id(c *enterpriseroleentityConfig) *enterpriseRole_Id {
	t := &enterpriseRole_Id{}
	t.config = c
	return t
}

// Set sets the value of Id field
func (t *enterpriseRole_Id) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldId.Name.String())
	}
}

// Get gets the value of Id field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *enterpriseRole_Id) Get() int64 {
	return *t.IntStorage.Get()
}

// enterpriseRole_EnterpriseId is EnterpriseId field
type enterpriseRole_EnterpriseId struct {
	field.IntStorage[int64]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_EnterpriseId creates a new enterpriseRole_EnterpriseId
func newEnterpriseRole_EnterpriseId(c *enterpriseroleentityConfig) *enterpriseRole_EnterpriseId {
	t := &enterpriseRole_EnterpriseId{}
	t.config = c
	return t
}

// Set sets the value of EnterpriseId field
func (t *enterpriseRole_EnterpriseId) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldEnterpriseId.Name.String())
	}
}

// Get gets the value of EnterpriseId field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *enterpriseRole_EnterpriseId) Get() int64 {
	return *t.IntStorage.Get()
}

// enterpriseRole_Code is Code field
type enterpriseRole_Code struct {
	field.StringStorage[string]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_Code creates a new enterpriseRole_Code
func newEnterpriseRole_Code(c *enterpriseroleentityConfig) *enterpriseRole_Code {
	t := &enterpriseRole_Code{}
	t.config = c
	return t
}

// Set sets the value of Code field
func (t *enterpriseRole_Code) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldCode.Name.String())
	}
}

// Get gets the value of Code field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *enterpriseRole_Code) Get() string {
	return *t.StringStorage.Get()
}

// enterpriseRole_Name is Name field
type enterpriseRole_Name struct {
	field.StringStorage[string]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_Name creates a new enterpriseRole_Name
func newEnterpriseRole_Name(c *enterpriseroleentityConfig) *enterpriseRole_Name {
	t := &enterpriseRole_Name{}
	t.config = c
	return t
}

// Set sets the value of Name field
func (t *enterpriseRole_Name) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldName.Name.String())
	}
}

// Get gets the value of Name field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *enterpriseRole_Name) Get() string {
	return *t.StringStorage.Get()
}

// enterpriseRole_Status is Status field
type enterpriseRole_Status struct {
	field.IntStorage[int16]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_Status creates a new enterpriseRole_Status
func newEnterpriseRole_Status(c *enterpriseroleentityConfig) *enterpriseRole_Status {
	t := &enterpriseRole_Status{}
	t.config = c
	return t
}

// Set sets the value of Status field
func (t *enterpriseRole_Status) Set(v int16) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldStatus.Name.String())
	}
}

// Get gets the value of Status field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *enterpriseRole_Status) Get() *int16 {
	return t.IntStorage.Get()
}

// enterpriseRole_Remark is Remark field
type enterpriseRole_Remark struct {
	field.StringStorage[string]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_Remark creates a new enterpriseRole_Remark
func newEnterpriseRole_Remark(c *enterpriseroleentityConfig) *enterpriseRole_Remark {
	t := &enterpriseRole_Remark{}
	t.config = c
	return t
}

// Set sets the value of Remark field
func (t *enterpriseRole_Remark) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldRemark.Name.String())
	}
}

// Get gets the value of Remark field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *enterpriseRole_Remark) Get() *string {
	return t.StringStorage.Get()
}

// enterpriseRole_CreatedAt is CreatedAt field
type enterpriseRole_CreatedAt struct {
	field.TimestampStorage[time.Time]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_CreatedAt creates a new enterpriseRole_CreatedAt
func newEnterpriseRole_CreatedAt(c *enterpriseroleentityConfig) *enterpriseRole_CreatedAt {
	t := &enterpriseRole_CreatedAt{}
	t.config = c
	return t
}

// Set sets the value of CreatedAt field
func (t *enterpriseRole_CreatedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldCreatedAt.Name.String())
	}
}

// Get gets the value of CreatedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *enterpriseRole_CreatedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// enterpriseRole_LastAt is LastAt field
type enterpriseRole_LastAt struct {
	field.TimestampStorage[time.Time]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_LastAt creates a new enterpriseRole_LastAt
func newEnterpriseRole_LastAt(c *enterpriseroleentityConfig) *enterpriseRole_LastAt {
	t := &enterpriseRole_LastAt{}
	t.config = c
	return t
}

// Set sets the value of LastAt field
func (t *enterpriseRole_LastAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldLastAt.Name.String())
	}
}

// Get gets the value of LastAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *enterpriseRole_LastAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// enterpriseRole_DeletedAt is DeletedAt field
type enterpriseRole_DeletedAt struct {
	field.TimestampStorage[time.Time]
	config *enterpriseroleentityConfig
}

// newenterpriseRole_DeletedAt creates a new enterpriseRole_DeletedAt
func newEnterpriseRole_DeletedAt(c *enterpriseroleentityConfig) *enterpriseRole_DeletedAt {
	t := &enterpriseRole_DeletedAt{}
	t.config = c
	return t
}

// Set sets the value of DeletedAt field
func (t *enterpriseRole_DeletedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.enterpriseroleentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(enterprise_role.FieldDeletedAt.Name.String())
	}
}

// Get gets the value of DeletedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *enterpriseRole_DeletedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}
