// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import (
	"context"

	"git.zodileap.com/entity/enterprise_v1/enterprise"
	"git.zodileap.com/entity/enterprise_v1/internal"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// EnterpriseEntityQuery is the query action for the EnterpriseEntity.
type EnterpriseEntityQuery struct {
	config       *enterpriseentityConfig
	ctx          *entitysql.QueryContext
	predicates   []entitysql.PredicateFunc
	rels         []enterpriseentityRel
	order        []enterprise.OrderTerm
	scanner      []*internal.QueryScanner
	scannerTotal int
}

// First returns the first result of the query.
func (o *EnterpriseEntityQuery) First(ctx context.Context) (*EnterpriseEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// newEnterpriseEntityQuery creates a new EnterpriseEntityQuery.
func newEnterpriseEntityQuery(c *internal.Dialect, t entity.Tracker, ms *enterpriseentityMutations) *EnterpriseEntityQuery {
	return &EnterpriseEntityQuery{
		config: &enterpriseentityConfig{
			Dialect:                   c,
			enterpriseentityMutations: ms,
		},
		ctx:          &entitysql.QueryContext{},
		predicates:   []entitysql.PredicateFunc{},
		rels:         []enterpriseentityRel{},
		order:        []enterprise.OrderTerm{},
		scanner:      []*internal.QueryScanner{},
		scannerTotal: 0,
	}
}

func (o *EnterpriseEntityQuery) Where(predicates ...entitysql.PredicateFunc) *EnterpriseEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *EnterpriseEntityQuery) Limit(limit int) *EnterpriseEntityQuery {
	o.ctx.Limit = &limit
	return o
}

func (o *EnterpriseEntityQuery) Order(term ...enterprise.OrderTerm) *EnterpriseEntityQuery {
	o.order = append(o.order, term...)
	return o
}

func (o *EnterpriseEntityQuery) Include(rels ...enterpriseentityRel) *EnterpriseEntityQuery {
	o.rels = append(o.rels, rels...)
	return o
}

// ToList returns the list of results of the query.
func (o *EnterpriseEntityQuery) ToList(ctx context.Context) ([]*EnterpriseEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *EnterpriseEntityQuery) Single(ctx context.Context) (*EnterpriseEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *EnterpriseEntityQuery) sqlSingle(ctx context.Context) (*EnterpriseEntity, error) {
	var (
		spec = o.querySpec()
		res  *EnterpriseEntity
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *EnterpriseEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan(fields)...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}
			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = e
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	if res != nil {
		if err := res.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		r.reset()
	}
	return res, nil
}

func (o *EnterpriseEntityQuery) sqlAll(ctx context.Context) ([]*EnterpriseEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*EnterpriseEntity{}
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *EnterpriseEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan([]entitysql.ScannerField{})...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}

			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = mergeEnterpriseEntity(res, e)
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		rel := r
		rel.reset()
	}
	return res, nil
}

func (o *EnterpriseEntityQuery) querySpec() *entitysql.QuerySpec {
	s := entitysql.NewQuerySpec(enterprise.Entity, enterprise.Columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s = entitysql.NewQuerySpec(enterprise.Entity, fields)
	}
	for i := range s.Entity.Columns {
		switch enterprise.Columns[i] {
		case enterprise.FieldId.Name:
			var a *enterprise_Id = new(enterprise_Id)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldId.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case enterprise.FieldCode.Name:
			var a *enterprise_Code = new(enterprise_Code)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldCode.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case enterprise.FieldName.Name:
			var a *enterprise_Name = new(enterprise_Name)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldName.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case enterprise.FieldStatus.Name:
			var a *enterprise_Status = new(enterprise_Status)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldStatus.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case enterprise.FieldRemark.Name:
			var a *enterprise_Remark = new(enterprise_Remark)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldRemark.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case enterprise.FieldCreatedAt.Name:
			var a *enterprise_CreatedAt = new(enterprise_CreatedAt)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldCreatedAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case enterprise.FieldLastAt.Name:
			var a *enterprise_LastAt = new(enterprise_LastAt)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldLastAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case enterprise.FieldDeletedAt.Name:
			var a *enterprise_DeletedAt = new(enterprise_DeletedAt)
			fieldSpace := entitysql.NewFieldSpec(enterprise.FieldDeletedAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		}
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	if rs := o.rels; len(rs) > 0 {
		s.Rels = make([]entitysql.Relation, 0, len(rs))
		s.Orders = append(s.Orders, enterprise.ByPrimary)
		for _, r := range rs {
			rel := r
			s.Rels = append(s.Rels, func(s *entitysql.Selector) {
				o.scanner = o.addRels(s, s.Table(), rel, o.scanner)
			})
		}
	}
	for _, o := range o.order {
		s.Orders = append(s.Orders, func(order *entitysql.Order) {
			o.Apply(order)
		})
	}
	return s
}

func (o *EnterpriseEntityQuery) addRels(s *entitysql.Selector, t *entitysql.SelectTable, rel rel, scanner []*internal.QueryScanner) []*internal.QueryScanner {
	desc, children, config := rel.Desc()
	join := entitysql.AddRelBySelector(s, t, desc)
	_, tableNum := join.GetAs()
	qs := internal.QueryScanner{Config: config, Children: []*internal.QueryScanner{}, TableNum: tableNum}
	scanner = append(scanner, &qs)
	o.scannerTotal++
	if len(children) > 0 {
		for _, c := range children {
			qs.Children = o.addRels(s, join, c, qs.Children)
		}
	}
	return scanner
}
