// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import (
	"git.zodileap.com/entity/enterprise_v1/internal"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

type enterpriseentityRelation struct {
	Config   internal.EntityConfig
	relation entitysql.RelationDesc
	children []rel
}

func newEnterpriseentityRelation(config internal.EntityConfig, desc entitysql.RelationDesc) *enterpriseentityRelation {
	return &enterpriseentityRelation{
		Config:   config,
		relation: desc,
		children: []rel{},
	}
}

func (r *enterpriseentityRelation) Where(predicates ...entitysql.PredicateFunc) *enterpriseentityRelation {
	r.relation.Predicates = append(r.relation.Predicates, predicates...)
	return r
}

func (r *enterpriseentityRelation) Include(rels ...enterpriseentityRel) *enterpriseentityRelation {
	// Create a slice of type Rel with the same length as r.children
	newRels := make([]rel, len(rels))
	for i, r := range rels {
		// Convert each enterpriseentityRel to Rel and store it in the new slice
		newRels[i] = rel(r)
	}
	r.children = append(r.children, newRels...)
	return r
}

func (r *enterpriseentityRelation) Desc() (entitysql.RelationDesc, []rel, internal.EntityConfig) {
	return r.relation, r.children, r.Config
}

func (r *enterpriseentityRelation) reset() {
	for _, child := range r.children {
		child.reset()
	}
	r.relation.Reset()
	r.children = []rel{}
}
