// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import (
	"fmt"
	"time"

	"git.zodileap.com/entity/enterprise_v1/enterprise_member"
	"git.zodileap.com/entity/enterprise_v1/internal"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// 企业成员
type EnterpriseMemberEntity struct {
	internal.Entity `json:"-"`
	config          *enterprisememberentityConfig
	Id              *enterpriseMember_Id           `json:"id"`                   // Id 主键Id
	EnterpriseId    *enterpriseMember_EnterpriseId `json:"enterprise_id"`        // EnterpriseId 企业Id
	UserId          *enterpriseMember_UserId       `json:"user_id"`              // UserId 用户Id
	RoleCode        *enterpriseMember_RoleCode     `json:"role_code"`            // RoleCode 角色编码
	Status          *enterpriseMember_Status       `json:"status"`               // Status 状态
	CreatedAt       *enterpriseMember_CreatedAt    `json:"created_at"`           // CreatedAt 创建数据时间
	LastAt          *enterpriseMember_LastAt       `json:"last_at"`              // LastAt 更新数据时间
	DeletedAt       *enterpriseMember_DeletedAt    `json:"deleted_at,omitempty"` // DeletedAt 删除数据时间（逻辑删除）
}

// enterprisememberentityConfig holds the configuration for the EnterpriseMemberEntity.
type enterprisememberentityConfig struct {
	internal.EntityConfig
	*internal.Dialect
	*entity.Mutation
	*enterprisememberentityMutations
	name string
}

func newEnterpriseMemberEntityConfig(c *internal.Dialect) *enterprisememberentityConfig {
	return &enterprisememberentityConfig{
		Dialect:                         c,
		enterprisememberentityMutations: newEnterpriseMemberEntityMutations(),
		name:                            "enterprise_member",
	}
}

// New creates a new EnterpriseMemberEntity, but does not add tracking.
func (c *enterprisememberentityConfig) New() internal.Entity {
	b := entity.NewMutation(entity.Detached)
	e := &EnterpriseMemberEntity{
		config: &enterprisememberentityConfig{
			Mutation:                        b,
			Dialect:                         c.Dialect,
			enterprisememberentityMutations: c.enterprisememberentityMutations,
		},
	}
	e.setState(entity.Detached)
	e.Id = newEnterpriseMember_Id(e.config)
	e.EnterpriseId = newEnterpriseMember_EnterpriseId(e.config)
	e.UserId = newEnterpriseMember_UserId(e.config)
	e.RoleCode = newEnterpriseMember_RoleCode(e.config)
	e.Status = newEnterpriseMember_Status(e.config)
	e.CreatedAt = newEnterpriseMember_CreatedAt(e.config)
	e.LastAt = newEnterpriseMember_LastAt(e.config)
	e.DeletedAt = newEnterpriseMember_DeletedAt(e.config)
	return e
}

func (c *enterprisememberentityConfig) Desc() internal.EntityConfigDesc {
	return internal.EntityConfigDesc{
		Name: c.name,
	}
}

// String implements the fmt.Stringer interface.
func (e *EnterpriseMemberEntity) String() string {
	return fmt.Sprintf("{ Id: %v, EnterpriseId: %v, UserId: %v, RoleCode: %v, Status: %v, CreatedAt: %v, LastAt: %v, DeletedAt: %v}",
		e.Id,
		e.EnterpriseId,
		e.UserId,
		e.RoleCode,
		e.Status,
		e.CreatedAt,
		e.LastAt,
		e.DeletedAt,
	)
}

// State returns the state of the EnterpriseMemberEntity.
func (e *EnterpriseMemberEntity) State() entity.EntityState {
	return e.config.State()
}

// remove removes the EnterpriseMemberEntity from the database.
func (e *EnterpriseMemberEntity) remove() error {
	return e.setState(entity.Deleted)
}

// create creates a new EnterpriseMemberEntity and adds tracking.
func (e *EnterpriseMemberEntity) create(enterprise_id int64, user_id string, options ...func(*EnterpriseMemberEntity)) (*EnterpriseMemberEntity, error) {
	e.setState(entity.Added)
	e.EnterpriseId.Set(enterprise_id)
	e.UserId.Set(user_id)
	for _, option := range options {
		option(e)
	}
	return e, nil
}

// setUnchanged sets the state of the EnterpriseMemberEntity to unchanged.
func (e *EnterpriseMemberEntity) setUnchanged() error {
	return e.setState(entity.Unchanged)
}

// setState sets the state of the EnterpriseMemberEntity.
func (e *EnterpriseMemberEntity) setState(state entity.EntityState) error {
	return e.config.enterprisememberentityMutations.SetEntityState(e, state)
}

// scan scans the database for the EnterpriseMemberEntity.
func (e *EnterpriseMemberEntity) scan(fields []entitysql.ScannerField) []any {
	if len(fields) == 0 {
		args := make([]any, len(enterprise_member.Columns))
		for i, c := range enterprise_member.Columns {
			switch c.String() {
			case enterprise_member.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case enterprise_member.FieldEnterpriseId.Name.String():
				v := e.EnterpriseId
				v.Set(*new(int64))
				args[i] = v
			case enterprise_member.FieldUserId.Name.String():
				v := e.UserId
				v.Set(*new(string))
				args[i] = v
			case enterprise_member.FieldRoleCode.Name.String():
				v := e.RoleCode
				v.Set(*new(string))
				args[i] = v
			case enterprise_member.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case enterprise_member.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case enterprise_member.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case enterprise_member.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	} else {
		args := make([]any, len(fields))
		for i := range fields {
			switch fields[i].String() {
			case enterprise_member.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case enterprise_member.FieldEnterpriseId.Name.String():
				v := e.EnterpriseId
				v.Set(*new(int64))
				args[i] = v
			case enterprise_member.FieldUserId.Name.String():
				v := e.UserId
				v.Set(*new(string))
				args[i] = v
			case enterprise_member.FieldRoleCode.Name.String():
				v := e.RoleCode
				v.Set(*new(string))
				args[i] = v
			case enterprise_member.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case enterprise_member.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case enterprise_member.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case enterprise_member.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	}
}

func (e *EnterpriseMemberEntity) createRel(buidler *entitysql.ScannerBuilder, scanner *internal.QueryScanner) {
	switch scanner.Config.Desc().Name {
	}
}

func mergeEnterpriseMemberEntity(es []*EnterpriseMemberEntity, e *EnterpriseMemberEntity) []*EnterpriseMemberEntity {
	if e == nil {
		return es
	}
	if len(es) == 0 {
		es = append(es, e)
	} else {
		v := es[len(es)-1]

		if v.Id.Get() == e.Id.Get() {
		} else {
			es = append(es, e)
		}
	}
	return es
}
