// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise

import (
	"git.zodileap.com/entity/enterprise_v1/internal"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

type rel interface {
	Desc() (entitysql.RelationDesc, []rel, internal.EntityConfig)
	reset()
}

type enterpriseentityRel interface {
	rel
}

type enterprisememberentityRel interface {
	rel
}

type enterpriseroleentityRel interface {
	rel
}
