// Code generated by taurus_go/entity, DO NOT EDIT.

package agent_access

import (
	"github.com/zodileap/taurus_go/entity/entitysql"
)

const (
	Entity = "agent_access"
)

var (
	FieldId = entitysql.Field{
		Name:     "id",
		Primary:  1,
		Default:  true,
		Required: true,
	}
	FieldUserId = entitysql.Field{
		Name:     "user_id",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldAgentId = entitysql.Field{
		Name:     "agent_id",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldAccessType = entitysql.Field{
		Name:     "access_type",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldDuration = entitysql.Field{
		Name:     "duration",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldStatus = entitysql.Field{
		Name:     "status",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldCreatedAt = entitysql.Field{
		Name:     "created_at",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldLastAt = entitysql.Field{
		Name:     "last_at",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldDeletedAt = entitysql.Field{
		Name:     "deleted_at",
		Primary:  0,
		Default:  true,
		Required: false,
	}
)

var (
	Columns = []entitysql.FieldName{
		FieldId.Name,
		FieldUserId.Name,
		FieldAgentId.Name,
		FieldAccessType.Name,
		FieldDuration.Name,
		FieldStatus.Name,
		FieldCreatedAt.Name,
		FieldLastAt.Name,
		FieldDeletedAt.Name,
	}
)
