import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

// 描述：
//
//   - 读取 Desktop 源码文件，用于会话“工作流/技能”选择弹窗回归测试。
//
// Params:
//
//   - relativePath: 基于 apps/desktop 的相对路径。
//
// Returns:
//
//   - UTF-8 文本内容。
function readDesktopSource(relativePath) {
  const absolutePath = path.resolve(process.cwd(), relativePath);
  return fs.readFileSync(absolutePath, "utf8");
}

test("TestSessionPageShouldProvideWorkflowAndSkillSelectorModal", () => {
  const sessionSource = [
    readDesktopSource("src/widgets/session/page.tsx"),
    readDesktopSource("src/widgets/session/prompt-utils.ts"),
    readDesktopSource("src/widgets/session/run-segment.tsx"),
  ].join("\n");
  const styleSource = readDesktopSource("src/styles.css");

  // 描述：
  //
  //   - 会话页应加载已安装技能并支持本地持久化“工作流/技能”选择，且只保留统一智能体持久化键。
  assert.match(sessionSource, /listAgentSkills/);
  assert.match(sessionSource, /listMcpOverview/);
  assert.match(sessionSource, /AGENT_EXECUTION_SELECTION_KEY/);
  assert.match(sessionSource, /AGENT_SKILL_SELECTED_KEY/);
  assert.doesNotMatch(sessionSource, /MODEL_SKILL_SELECTED_KEY/);
  assert.match(sessionSource, /type SessionExecutionSelection =/);
  assert.match(sessionSource, /readSessionExecutionSelection\(/);
  assert.match(sessionSource, /writeSessionExecutionSelection\(/);
  assert.match(sessionSource, /EMPTY_SESSION_EXECUTION_SELECTION/);
  assert.match(sessionSource, /buildWorkflowExecutionSelection\(/);
  assert.match(sessionSource, /buildSkillExecutionSelection\(/);
  assert.match(sessionSource, /readSelectedSkillIds/);
  assert.match(sessionSource, /buildSessionSkillPrompt/);
  assert.match(sessionSource, /resolveAgentSessionSelectedAiProvider/);
  assert.match(sessionSource, /rememberAgentSessionSelectedAiProvider/);
  assert.match(sessionSource, /resolveAgentSessionSelectedDccSoftware/);
  assert.match(sessionSource, /rememberAgentSessionSelectedDccSoftware/);
  assert.match(sessionSource, /getProjectWorkspaceCapabilityManifest/);
  assert.match(sessionSource, /isProjectWorkspaceCapabilityEnabled/);
  assert.match(sessionSource, /listAgentWorkflowOverview\(\)\.registered/);
  assert.doesNotMatch(sessionSource, /listAgentWorkflows\(\)/);
  assert.match(sessionSource, /const DCC_MODELING_SKILL_ID = "dcc-modeling";/);
  assert.match(sessionSource, /const QUICK_START_CODE_WORKFLOW_ID = "wf-agent-full-delivery-v1";/);
  assert.match(sessionSource, /interface SessionQuickStartPreset/);
  assert.match(sessionSource, /interface PendingDccSelectionState/);
  assert.match(sessionSource, /selectionMode: "single" \| "cross";/);
  assert.match(sessionSource, /resolvedCrossDccSoftwares\?: string\[\];/);
  assert.match(sessionSource, /resolveAvailableDccSoftwareOptions\(/);
  assert.match(sessionSource, /resolveExplicitDccSoftwares\(/);
  assert.match(sessionSource, /hasCrossDccIntent\(/);
  assert.match(sessionSource, /const DCC_CROSS_SOFTWARE_INTENT_KEYWORDS = resolveDesktopTextVariants\(DESKTOP_TEXT_VARIANT_GROUPS\.dccCrossSoftwareIntent\);/);
  assert.match(sessionSource, /const AGENT_BRIDGE_STAGE_HINT_KEYWORDS = resolveDesktopTextVariants\(DESKTOP_TEXT_VARIANT_GROUPS\.agentBridgeStageHints\);/);
  assert.match(sessionSource, /const AGENT_TIMEOUT_HINT_KEYWORDS = resolveDesktopTextVariants\(DESKTOP_TEXT_VARIANT_GROUPS\.agentTimeoutHints\);/);
  assert.match(sessionSource, /buildDccRoutingPromptBlock\(/);
  assert.match(sessionSource, /const \[selectedProvider, setSelectedProvider\] = useState<string>\(\s*\(\) => resolveAgentSessionSelectedAiProvider\(sessionId\),\s*\)/s);
  assert.match(sessionSource, /const \[selectedDccSoftware, setSelectedDccSoftware\] = useState<string>\(/);
  assert.match(sessionSource, /const \[pendingDccSelection, setPendingDccSelection\] = useState<PendingDccSelectionState \| null>\(null\);/);
  assert.match(sessionSource, /const activeWorkspaceEnabledCapabilities = useMemo<ProjectWorkspaceCapabilityId\[\]>/);
  assert.doesNotMatch(sessionSource, /selectedWorkflowMissingRequiredCapabilities/);
  assert.match(sessionSource, /const activeUsesDccModelingSkill = useMemo\(/);
  assert.match(sessionSource, /getAgentWorkflowById\(selectedWorkflowId\)/);
  assert.match(sessionSource, /const sessionQuickStartPresets = useMemo<SessionQuickStartPreset/);
  assert.match(sessionSource, /title: t\("前端项目开发"\)/);
  assert.match(sessionSource, /handleApplyQuickStartPreset/);
  assert.match(sessionSource, /const \[availableSkillsLoaded, setAvailableSkillsLoaded\] = useState\(false\);/);
  assert.match(sessionSource, /setAvailableSkillsLoaded\(true\);/);
  assert.match(sessionSource, /if \(!availableSkillsLoaded\) \{\s*const message = t\("技能列表加载中\.\.\."\);/s);
  assert.match(sessionSource, /if \(!nextWorkflowId \|\| !registeredWorkflowIdSet\.has\(nextWorkflowId\)\) \{\s*const message = t\("当前未注册“\{\{title\}\}”所需工作流，请先注册后再试。", \{ title: preset\.title \}\);/s);
  assert.match(sessionSource, /const missingSkillIds = nextSkillIds\.filter\(\(item\) => !registeredSkillIdSet\.has\(item\)\);/);
  assert.match(sessionSource, /if \(missingSkillIds\.length > 0\) \{\s*const message = t\("当前未注册“\{\{title\}\}”所需技能，请先注册后再试。", \{ title: preset\.title \}\);/s);
  assert.match(sessionSource, /setExecutionSelection\(buildSkillExecutionSelection\(nextSkillIds\)\);/);
  assert.match(sessionSource, /setExecutionSelection\(buildWorkflowExecutionSelection\(nextWorkflowId\)\);/);
  assert.match(sessionSource, /setInput\(preset\.prompt\);/);
  assert.match(sessionSource, /setStatus\(t\("已选择“\{\{title\}\}”预设，可继续补充需求后发送。", \{ title: preset\.title \}\)\);/);

  // 描述：
  //
  //   - 空会话顶部应提供快速开始卡片，输入区仍通过 AriSelect 完成 AI 选择与“工作流/技能”触发。
  assert.match(sessionSource, /className="desk-session-quick-start-heading"/);
  assert.match(sessionSource, /<AriTypography variant="h4" bold value=\{t\("快速开始"\)\} \/>/);
  assert.match(sessionSource, /className="desk-session-quick-start-grid"/);
  assert.match(sessionSource, /className="desk-session-empty-card desk-session-quick-start-card"/);
  assert.match(sessionSource, /role="button"/);
  assert.match(sessionSource, /tabIndex=\{0\}/);
  assert.match(sessionSource, /onKeyDown=\{\(event\) => \{\s*handleQuickStartPresetCardKeyDown\(event, preset\);/s);
  assert.doesNotMatch(sessionSource, /className="desk-session-quick-start-icon"/);
  assert.doesNotMatch(sessionSource, /label=\{t\("使用预设"\)\}/);
  assert.doesNotMatch(sessionSource, /title: t\("写代码"\)/);
  assert.doesNotMatch(sessionSource, /resolvedSessionUiConfig\.emptyStatePrimary/);
  assert.doesNotMatch(sessionSource, /resolvedSessionUiConfig\.emptyStateSecondary/);
  assert.match(sessionSource, /<AriSelect/);
  assert.match(sessionSource, /handleChangeProvider/);
  assert.match(sessionSource, /setSelectedProvider\(resolveAgentSessionSelectedAiProvider\(sessionId\)\);/);
  assert.match(sessionSource, /function applySessionAiSelection\(/);
  assert.match(sessionSource, /rememberAgentSessionSelectedAiProvider\(sessionId, normalizedProvider\);/);
  assert.match(sessionSource, /if \(normalizedProvider && availableAiKeys\.some\(\(item\) => item\.provider === normalizedProvider\)\) \{\s*return;\s*\}/s);
  assert.match(sessionSource, /workflowSkillSelectOptions/);
  assert.match(sessionSource, /value="workflow_skill"/);
  assert.match(sessionSource, /openOnTriggerClick=\{false\}/);
  assert.match(sessionSource, /onTriggerClick=\{\(\) => \{/);
  assert.match(sessionSource, /handleOpenWorkflowSkillModal\(\);/);
  assert.match(sessionSource, /bordered=\{false\}/);
  assert.match(sessionSource, /className="desk-prompt-toolbar-select desk-prompt-toolbar-select-provider"/);
  assert.match(sessionSource, /className="desk-prompt-toolbar-select desk-prompt-toolbar-select-strategy"/);
  assert.doesNotMatch(sessionSource, /className="desk-prompt-toolbar-select desk-prompt-toolbar-select-strategy"[\s\S]*size="md"/);
  assert.doesNotMatch(sessionSource, /className="desk-prompt-toolbar-select desk-prompt-toolbar-select-strategy"[\s\S]*size="sm"/);
  assert.doesNotMatch(sessionSource, /placeholder="选择 AI"[\s\S]*?searchable/s);
  assert.doesNotMatch(sessionSource, /label=\{workflowSkillSelectorLabel\}/);
  assert.doesNotMatch(sessionSource, /onClick=\{handleOpenWorkflowSkillModal\}/);
  assert.match(sessionSource, /title=\{t\("选择执行策略"\)\}/);
  assert.match(sessionSource, /title=\{t\("选择执行策略"\)\}[\s\S]*?<AriButton[\s\S]*?label=\{t\("确定"\)\}[\s\S]*?onClick=\{handleConfirmWorkflowSkillModal\}/s);
  assert.doesNotMatch(sessionSource, /title=\{t\("选择执行策略"\)\}[\s\S]*?<AriButton[\s\S]*?color="brand"[\s\S]*?label=\{t\("确定"\)\}[\s\S]*?onClick=\{handleConfirmWorkflowSkillModal\}/s);
  assert.match(sessionSource, /import \{ DeskEmptyState \} from "\.\.\/settings-primitives";/);
  assert.match(sessionSource, /value=\{t\("模式"\)\}/);
  assert.match(sessionSource, /value=\{t\("不使用流程"\)\}/);
  assert.match(sessionSource, /value=\{t\("工作流"\)\}/);
  assert.match(sessionSource, /value=\{t\("技能"\)\}/);
  assert.match(sessionSource, /<AriTypography variant="body" bold value=\{t\("不使用流程"\)\} \/>/);
  assert.match(sessionSource, /<AriTypography variant="body" bold value=\{item\.label\} \/>/);
  assert.match(sessionSource, /<AriTypography variant="body" bold value=\{item\.title\} \/>/);
  assert.match(sessionSource, /workflowMenuItems\.length > 0 \? \(/);
  assert.match(sessionSource, /availableSkills\.length > 0 \? \(/);
  assert.match(sessionSource, /<DeskEmptyState\s*title=\{t\("暂无可选工作流"\)\}\s*description=\{t\("请先注册工作流后再选择。"\)\}\s*\/>/s);
  assert.match(sessionSource, /<DeskEmptyState\s*title=\{t\("暂无可用技能"\)\}\s*description=\{t\("请先注册技能后再选择。"\)\}\s*titleVariant="body"\s*titleBold\s*\/>/s);
  assert.doesNotMatch(sessionSource, /emptyMessage=\{t\("暂无可选工作流"\)\}/);
  assert.doesNotMatch(sessionSource, /emptyMessage=\{t\("暂无可用技能"\)\}/);
  assert.match(sessionSource, /<AriList/);
  assert.match(sessionSource, /<AriList[\s\S]*?className="desk-session-strategy-list"[\s\S]*?size="sm"/s);
  assert.match(sessionSource, /<AriListItem/);
  assert.doesNotMatch(sessionSource, /actions=\{\[/);
  assert.doesNotMatch(sessionSource, /key="execution-none-type"/);
  assert.doesNotMatch(sessionSource, /key=\{`\$\{item\.key\}-type`\}/);
  assert.doesNotMatch(sessionSource, /key=\{`\$\{item\.id\}-origin`\}/);
  assert.match(sessionSource, /extra=/);
  assert.doesNotMatch(sessionSource, /value="工作流\/技能"/);
  assert.match(sessionSource, /handleConfirmWorkflowSkillModal/);
  assert.match(sessionSource, /handleSelectDraftExecutionNone/);
  assert.match(sessionSource, /handleToggleDraftSkill/);
  assert.match(sessionSource, /return Array\.from\(new Set\(normalized\)\)\.slice\(0, 1\);/);
  assert.match(sessionSource, /const nextSkillIds = draftSkillIds\.includes\(skillId\) \? \[\] : \[skillId\];/);
  assert.match(sessionSource, /setDraftExecutionSelection\(buildSkillExecutionSelection\(nextSkillIds\)\);/);
  assert.match(sessionSource, /const nextSkillIds = draftSkillIds\.slice\(0, 1\);/);
  assert.match(sessionSource, /setExecutionSelection\(buildSkillExecutionSelection\(nextSkillIds\)\);/);
  assert.match(sessionSource, /setExecutionSelection\(buildWorkflowExecutionSelection\(nextWorkflowId \|\| workflows\[0\]\?\.id \|\| ""\)\);/);
  assert.match(sessionSource, /setDraftExecutionSelection\(buildWorkflowExecutionSelection\(item\.key\)\);/);
  assert.doesNotMatch(sessionSource, /setSelectedSkillIds\(nextSkillIds\);\s*setSelectedWorkflowId\(""\);/s);
  assert.doesNotMatch(sessionSource, /setSelectedSkillIds\(\[\]\);\s*setSelectedWorkflowId\(nextWorkflowId\);/s);
  assert.doesNotMatch(sessionSource, /setDraftWorkflowId\(item\.key\);\s*setDraftSkillIds\(\[\]\);/s);
  assert.match(sessionSource, /const initialStreamText = "";/);
  assert.match(sessionSource, /mapAgentTextStreamToRunSegment\(/);
  assert.match(sessionSource, /resolveAssistantRunStageByAgentTextStream\(/);
  assert.match(sessionSource, /function buildAssistantHeartbeatSegment\(/);
  assert.match(sessionSource, /translateDesktopText\("等待工具返回本步结果…"\)/);
  assert.match(sessionSource, /setAssistantRunMetaMap\(normalizedRunMetaMap\);/);
  assert.match(sessionSource, /const \[expandedRunSegmentDetailMap, setExpandedRunSegmentDetailMap\] = useState<Record<string, boolean>>\(\{\}\);/);
  assert.match(sessionSource, /function isApprovalPendingSegment\(/);
  assert.match(sessionSource, /const runSnapshot = getSessionRunState\(normalizedAgentKey, sessionId\);/);
  assert.match(sessionSource, /data: item\.data && typeof item\.data === "object"/);
  assert.match(sessionSource, /upsertSessionRunState\(\{/);
  assert.match(sessionSource, /removeSessionRunState\(normalizedAgentKey, sessionId\);/);
  assert.match(sessionSource, /const shouldResolvePendingInteractiveSegment = incomingSegmentKind === STREAM_KINDS\.TOOL_CALL_FINISHED/);
  assert.match(sessionSource, /const hasPendingInteractiveSegment = baseSegments\.some\(/);
  assert.match(sessionSource, /if \(!isApprovalPendingSegment\(item\) && !isUserInputPendingSegment\(item\)\) \{\s*return \{ \.\.\.item, status: "finished" as const \};\s*\}/s);
  assert.match(sessionSource, /if \(!shouldResolvePendingInteractiveSegment\) \{\s*return item;\s*\}/s);
  assert.match(sessionSource, /const runningMessageIds = Object\.entries\(assistantRunMetaMap\)/);
  assert.match(sessionSource, /const orderedMessageIds = preferredMessageId && runningMessageIds\.includes\(preferredMessageId\)/);
  assert.match(sessionSource, /const pendingApproval = Boolean\(/);
  assert.match(sessionSource, /currentMeta\.segments\.some\(\(item\) => item\.status === "running" && isApprovalPendingSegment\(item\)\)/);
  assert.doesNotMatch(sessionSource, /ASSISTANT_RUN_HEARTBEAT_STALE_LIMIT/);
  assert.doesNotMatch(sessionSource, /执行超时：长时间未收到/);
  assert.match(sessionSource, /const agentStreamSeenKeysRef = useRef<Set<string>>\(new Set\(\)\);/);
  assert.match(sessionSource, /function buildWorkflowCompletionSummary\(/);
  assert.match(sessionSource, /function collectWorkflowStageSummaryItems\(/);
  assert.match(sessionSource, /function buildWorkflowExecutionSummaryPrompt\(/);
  assert.match(sessionSource, /function resolveFinalAssistantRunSummary\(/);
  assert.match(sessionSource, /function stripWorkflowStageAutoCompletionPlaceholder\(/);
  assert.match(sessionSource, /function isWorkflowStageAutoCompletionLeadLine\(/);
  assert.match(sessionSource, /const requestWorkflowExecutionSummary = async \(/);
  assert.match(sessionSource, /const workflowSummaryResult = workflowCompletionDigest\s*\?\s*await requestWorkflowExecutionSummary\(/s);
  assert.match(sessionSource, /finishAssistantRunMessage\(\s*streamMessageId,\s*"finished",\s*workflowSummaryResult\.summary,\s*workflowSummaryResult\.summarySource,\s*\)/s);
  assert.match(sessionSource, /const finalSummary = resolveFinalAssistantRunSummary\(/);
  assert.doesNotMatch(sessionSource, /finishAssistantRunMessage\(streamMessageId, "finished", t\("执行过程已完成。"\)\);/);
  assert.match(sessionSource, /const hasPendingWorkflowStages = \(\) => \{/);
  assert.match(sessionSource, /if \(streamMessageIdRef\.current\) \{\s*const failedAssistantReply = t\("执行失败：\{\{reason\}\}", \{ reason \}\);\s*setStreamingAssistantTarget\(t\("执行失败：\{\{reason\}\}", \{ reason \}\)\);\s*finishAssistantRunMessage\(\s*streamMessageIdRef\.current,\s*"failed",\s*failedAssistantReply,\s*"failure",\s*\);/s);
  assert.match(sessionSource, /if \(payload\.kind === STREAM_KINDS\.STARTED\) \{\s*(?:agentLlmDeltaBufferRef\.current = "";\s*)?(?:setSessionAiResponseRaw\(""\);\s*)?setStreamingAssistantTarget\(t\("正在准备执行\.\.\."\)\);/s);
  assert.match(sessionSource, /if \(payload\.kind === STREAM_KINDS\.LLM_STARTED\) \{\s*(?:agentLlmDeltaBufferRef\.current = "";\s*)?(?:setSessionAiResponseRaw\(""\);\s*)?setStreamingAssistantTarget\(t\("正在生成执行结果…"\)\);/s);
  assert.match(sessionSource, /if \(payload\.kind === STREAM_KINDS\.LLM_FINISHED\) \{/);
  assert.match(sessionSource, /function buildAssistantHeartbeatDisplayText\(/);
  assert.match(sessionSource, /function resolvePlanningDisplayText\(/);
  assert.match(sessionSource, /if \(payload\.kind === STREAM_KINDS\.PLANNING\) \{\s*const planningText = resolvePlanningDisplayText\(payload\);/s);
  assert.match(sessionSource, /if \(payload\.kind === STREAM_KINDS\.HEARTBEAT\) \{\s*assistantRunHeartbeatCountRef\.current \+= 1;/s);
  assert.match(sessionSource, /setStreamingAssistantTarget\(heartbeatText,\s*\{\s*immediate: assistantRunHeartbeatCountRef\.current > 1,\s*\}\);/s);
  assert.match(sessionSource, /if \(\s*payload\.kind === STREAM_KINDS\.DELTA[\s\S]*payload\.kind === STREAM_KINDS\.STARTED[\s\S]*payload\.kind === STREAM_KINDS\.LLM_STARTED[\s\S]*payload\.kind === STREAM_KINDS\.LLM_FINISHED[\s\S]*return null;\s*\}/s);
  assert.match(sessionSource, /buildSessionContextPrompt\(/);
  assert.match(sessionSource, /const \[executionSelection, setExecutionSelection\] = useState<SessionExecutionSelection>\(\(\) =>/);
  assert.match(sessionSource, /const \[draftExecutionSelection, setDraftExecutionSelection\] = useState<SessionExecutionSelection>\(/);
  assert.match(sessionSource, /if \(executionSelection\.kind === "skill"\) \{\s*setDraftExecutionSelection\(buildSkillExecutionSelection\(activeSelectedSkillIds\)\);/s);
  assert.match(sessionSource, /if \(executionSelection\.kind === "workflow"\) \{\s*setDraftExecutionSelection\(buildWorkflowExecutionSelection\(activeSelectedWorkflowId\)\);/s);
  assert.match(sessionSource, /setDraftExecutionSelection\(EMPTY_SESSION_EXECUTION_SELECTION\);/);
  assert.match(sessionSource, /setDraftExecutionSelection\(buildWorkflowExecutionSelection\(item\.key\)\);/);
  assert.doesNotMatch(sessionSource, /setDraftWorkflowId\(item\.key\);\s*setDraftSkillIds\(\[\]\);/s);
  assert.doesNotMatch(sessionSource, /setDraftWorkflowId\(""\);/);
  assert.match(sessionSource, /setExecutionSelection\(EMPTY_SESSION_EXECUTION_SELECTION\);/);
  assert.match(sessionSource, /\{uiHint \? \(/);
  assert.doesNotMatch(sessionSource, /\{uiHint \|\| compactActionSlotStatus \? \(/);
  assert.match(sessionSource, /handleCopyMessageContent/);
  assert.match(sessionSource, /handleRetryAssistantMessage/);
  assert.match(sessionSource, /handleEditUserMessage/);
  assert.doesNotMatch(sessionSource, /hoveredRetryTooltipMessageId/);
  assert.match(sessionSource, /replaceAssistantMessageId\?: string/);
  assert.match(sessionSource, /const workflowRootStreamMessageId = String\(options\?\.replaceAssistantMessageId \|\| ""\)\.trim\(\)\s*\|\|\s*`assistant-stream-\$\{Date\.now\(\)\}`;/);
  assert.match(sessionSource, /const streamMessageId = workflowRootStreamMessageId;/);
  assert.match(sessionSource, /const stageContextMessageId = hasWorkflowStages\s*\?\s*`\$\{streamMessageId\}-stage-\$\{currentStageIndex \+ 1\}`\s*:\s*streamMessageId;/s);
  assert.match(sessionSource, /contextMessages\?: MessageItem\[\];/);
  assert.match(sessionSource, /displayMessages\?: MessageItem\[\];/);
  assert.match(sessionSource, /displayMessages: MessageItem\[\];/);
  assert.match(sessionSource, /const currentDisplayMessages = messagesRef\.current;/);
  assert.match(sessionSource, /const currentContextMessages = agentContextMessagesRef\.current;/);
  assert.match(sessionSource, /const baseDisplayMessages = options\?\.displayMessages \|\| currentDisplayMessages;/);
  assert.match(sessionSource, /const baseContextMessages = options\?\.contextMessages\?\.length/);
  assert.match(sessionSource, /: currentContextMessages\.length > 0/);
  assert.match(sessionSource, /: buildPromptContextMessages\(\s*baseDisplayMessages,\s*assistantRunMetaMapRef\.current,\s*\)/s);
  assert.match(sessionSource, /const dccPreflight = await resolveDccPreflight\(\s*normalizedContent,\s*baseDisplayMessages,\s*baseContextMessages,\s*effectiveUsesDccModelingSkill,\s*options,\s*\);/s);
  assert.match(sessionSource, /if \(dccPreflight\.blocked\) \{\s*return;\s*\}/s);
  assert.match(sessionSource, /dccPreflight\.promptBlock/);
  assert.match(sessionSource, /function buildSessionContextPrompt\(/);
  assert.match(sessionSource, /workspacePath\?: string/);
  assert.match(sessionSource, /projectProfile\?: ProjectWorkspaceProfile \| null/);
  assert.match(sessionSource, /enabledCapabilities: ProjectWorkspaceCapabilityId\[] = \[\],/);
  assert.match(sessionSource, /runtimeInfo\?: DesktopRuntimeInfo \| null,/);
  assert.match(sessionSource, /const projectKnowledgeEnabled = enabledCapabilities\.includes\("project-knowledge"\);/);
  assert.match(sessionSource, /translateDesktopText\("路径：\{\{path\}\}", \{ path: normalizedWorkspacePath \}\)/);
  assert.match(sessionSource, /buildSessionContextPrompt\(\s*nextContextMessages,\s*normalizedContent,\s*undefined,\s*latestProjectProfile,\s*activeWorkspaceEnabledCapabilities,\s*sessionMemoryRef\.current,\s*runtimeInfo,\s*\)/s);
  assert.match(sessionSource, /buildSessionContextPrompt\(\s*nextContextMessages,\s*normalizedContent,\s*String\(activeWorkspace\?\.path \|\| ""\)\.trim\(\) \|\| undefined,\s*latestProjectProfile,\s*activeWorkspaceEnabledCapabilities,\s*sessionMemoryRef\.current,\s*runtimeInfo,\s*\)/s);
  assert.match(sessionSource, /translateDesktopText\("系统：\{\{system\}\}"/);
  assert.match(sessionSource, /translateDesktopText\("命令约束：\{\{constraint\}\}"/);
  assert.doesNotMatch(sessionSource, /当前工作流缺少必需的项目能力/);
  assert.match(sessionSource, /getProjectWorkspaceProfile\(activeWorkspace\.id\)/);
  assert.match(sessionSource, /workdir: String\(activeWorkspace\?\.path \|\| ""\)\.trim\(\) \|\| undefined,/);
  assert.match(sessionSource, /function pruneAssistantRetryTail\(/);
  assert.match(sessionSource, /const PLANNING_META_PREFIX = "__libra_planning__:";/);
  assert.match(sessionSource, /const INITIAL_THINKING_SEGMENT_ROLE = "initial_thinking";/);
  assert.match(sessionSource, /function normalizeApprovalToolName\(/);
  assert.match(sessionSource, /function resolvePlanningMeta\(/);
  assert.match(sessionSource, /function isInitialThinkingSegment\(/);
  assert.match(sessionSource, /function isThinkingPlaceholderSegment\(/);
  assert.match(sessionSource, /function isRoundDescriptionSegment\(/);
  assert.match(sessionSource, /function normalizeAssistantRunSegments\(/);
  assert.match(sessionSource, /function resolveRunningIndicatorText\(/);
  assert.match(sessionSource, /function isGenericRunningIndicatorText\(/);
  assert.match(sessionSource, /function resolveRecoveredAssistantMessageText\(/);
  assert.match(sessionSource, /isInitialThinkingSegment\(current\.segments\[0\]\)\s*&& !isInitialThinkingSegment\(segment\)/);
  assert.match(sessionSource, /const dedupedSegments = sanitizedSegments\.reduce<AssistantRunSegment\[\]>\(\(accumulator, item\) => \{/);
  assert.match(sessionSource, /const preservedSegments = accumulator\.filter\(\(entry\) => !isRoundDescriptionSegment\(entry\)\);/);
  assert.match(sessionSource, /const meaningfulSegments = dedupedSegments\.filter\(\(item\) => !isThinkingPlaceholderSegment\(item\)\);/);
  assert.match(sessionSource, /const latestThinkingSegment = \[\.\.\.dedupedSegments\]\.reverse\(\)\.find\(\(item\) => isThinkingPlaceholderSegment\(item\)\);/);
  assert.match(sessionSource, /segments:\s*normalizeAssistantRunSegments\(\[\.\.\.normalizedSegments,\s*segment\]\),/);
  assert.match(sessionSource, /if \(segmentRole === INITIAL_THINKING_SEGMENT_ROLE \|\| isThinkingPlaceholderSegment\(segment\)\)/);
  assert.match(sessionSource, /const WORKFLOW_STAGE_DIVIDER_SEGMENT_ROLE = "workflow_stage_divider";/);
  assert.match(sessionSource, /function isWorkflowStageDividerSegment\(segment: AssistantRunSegment\): boolean \{/);
  assert.match(sessionSource, /if \(segmentRole === WORKFLOW_STAGE_DIVIDER_SEGMENT_ROLE \|\| isWorkflowStageDividerSegment\(segment\)\) \{/);
  assert.match(sessionSource, /groups\.push\(\{\s*key: `run-group-\$\{groups\.length\}-default`,\s*title: "",\s*kind: "default",/s);
  assert.match(sessionSource, /\.filter\(\(group\) => group\.kind === "divider" \|\| group\.steps\.length > 0\);/);
  assert.match(sessionSource, /const \[sessionApprovedToolNames, setSessionApprovedToolNames\] = useState<string\[\]>\(\[\]\);/);
  assert.match(sessionSource, /const \[workflowPhaseCursor, setWorkflowPhaseCursor\] = useState<SessionWorkflowPhaseCursorSnapshot \| null>\(null\);/);
  assert.match(sessionSource, /const sessionApprovedToolNameSetRef = useRef<Set<string>>\(new Set\(\)\);/);
  assert.match(sessionSource, /const workflowPhaseCursorRef = useRef<SessionWorkflowPhaseCursorSnapshot \| null>\(null\);/);
  assert.match(sessionSource, /const messagesRef = useRef<MessageItem\[\]>\(\[\]\);/);
  assert.match(sessionSource, /const sendingRef = useRef\(false\);/);
  assert.match(sessionSource, /messagesRef\.current = messages;/);
  assert.match(sessionSource, /sendingRef\.current = sending;/);
  assert.match(sessionSource, /sessionApprovedToolNames: normalizedSessionApprovedToolNames,/);
  assert.match(sessionSource, /workflowPhaseCursor: workflowPhaseCursorRef\.current,/);
  assert.match(sessionSource, /workflowPhaseCursorRef\.current = workflowPhaseCursor;/);
  assert.match(sessionSource, /setWorkflowPhaseCursor\(restoredWorkflowPhaseCursor\);/);
  assert.match(sessionSource, /payload\.kind === STREAM_KINDS\.REQUIRE_APPROVAL/);
  assert.match(sessionSource, /const approvalToolName = String\(data\?\.tool_name \|\| ""\)\.trim\(\) \|\| translateDesktopText\("高危操作"\);/);
  assert.match(sessionSource, /step: translateDesktopText\("正在请求执行 \{\{tool\}\}", \{ tool: approvalToolName \}\)/);
  assert.match(sessionSource, /const incomingErrorCode = segment\.data && typeof segment\.data\.__error_code === "string"/);
  assert.match(sessionSource, /const isHumanRefusedError = incomingSegmentKind === STREAM_KINDS\.ERROR/);
  assert.match(sessionSource, /step: t\("已拒绝 \{\{tool\}\} 的执行请求。", \{ tool: toolName \|\| t\("该工具"\) \}\)/);
  assert.match(sessionSource, /__step_type: "approval_decision"/);
  assert.match(sessionSource, /approval_decision: "rejected"/);
  assert.match(sessionSource, /approval_decision: options\?\.decision \|\| \(status === "failed" \? "rejected" : "approved"\)/);
  assert.match(sessionSource, /sessionApprovedToolNameSetRef\.current\.has\(toolName\)/);
  assert.match(sessionSource, /AriMessage\.success\(t\("已批准 \{\{tool\}\}", \{ tool: normalizedToolName \|\| t\("该工具"\) \}\)\);/);
  assert.match(sessionSource, /step: t\("正在思考…"\)/);
  assert.match(sessionSource, /const normalizedRenderSegments = normalizeAssistantRunSegments\(runMeta\.segments\);/);
  assert.match(sessionSource, /t\("请选择建模软件"\)/);
  assert.match(sessionSource, /t\("请选择源软件和目标软件"\)/);
  assert.match(sessionSource, /setStatus\(t\("检测到多个可用建模软件，请先选择一个软件。"\)\);/);
  assert.match(sessionSource, /setStatus\(t\("检测到跨软件建模需求，请先选择源软件和目标软件。"\)\);/);
  assert.match(sessionSource, /handleConfirmPendingDccSelection/);
  assert.match(sessionSource, /handleCancelPendingDccSelection/);
  assert.match(sessionSource, /label=\{pendingDccSelection\.selectionMode === "cross" \? t\("按该组合继续"\) : t\("使用该软件继续"\)\}/);
  assert.match(sessionSource, /__segment_role: INITIAL_THINKING_SEGMENT_ROLE/);
  assert.match(sessionSource, /__segment_role: "round_description"/);
  assert.match(sessionSource, /const segmentKind = typeof segmentData\.__segment_kind === "string" \? segmentData\.__segment_kind : "";/);
  assert.match(sessionSource, /const looksLikeRecoveredRoundDescription = segmentKind === STREAM_KINDS\.PLANNING\s*&& normalizedIntro\s*&& normalizedStep === translateDesktopText\("正在思考…"\);/s);
  assert.match(sessionSource, /if \(segmentRole === ROUND_DESCRIPTION_SEGMENT_ROLE \|\| looksLikeRecoveredRoundDescription\) \{/);
  assert.match(sessionSource, /className="desk-run-thinking-indicator"/);
  assert.match(sessionSource, /className="desk-run-divider desk-run-divider-static desk-run-stage-divider"/);
  assert.match(sessionSource, /const runningIndicatorText = resolveRunningIndicatorText\(message\.text, runMeta\);/);
  assert.match(sessionSource, /function isGenericFinishedRunSummaryText\(value: string\): boolean \{/);
  assert.match(sessionSource, /function buildPromptContextMessages\(\s*transcriptMessages: MessageItem\[\],\s*runMetaMap: Record<string, AssistantRunMeta>,\s*\): MessageItem\[\] \{/s);
  assert.match(sessionSource, /candidateId\.startsWith\(`\$\{messageId\}-stage-`\)/);
  assert.match(sessionSource, /if \(normalizedMessageId && workflowRootMessageIdSet\.has\(normalizedMessageId\)\) \{\s*return null;\s*\}/s);
  assert.match(sessionSource, /const \[agentContextMessages, setAgentContextMessages\] = useState<MessageItem\[\]>\(\[\]\);/);
  assert.match(sessionSource, /const agentContextMessagesRef = useRef<MessageItem\[\]>\(\[\]\);/);
  assert.match(sessionSource, /setAgentContextMessages\(nextContextMessages\);/);
  assert.match(sessionSource, /setAgentContextMessages\(prunedRetryContextMessages\);/);
  assert.match(sessionSource, /const recoveredText = resolveRecoveredAssistantMessageText\(nextMessages, recoveredMessageId, recoveredMeta\);/);
  assert.match(sessionSource, /messages: filterWorkflowStageContextMessages\(messagesRef\.current\),/);
  assert.match(sessionSource, /messages: agentContextMessagesRef\.current,/);
  assert.match(sessionSource, /runMetaMap: assistantRunMetaMapRef\.current,/);
  assert.match(sessionSource, /workflowIdOverride\?: string;/);
  assert.match(sessionSource, /workflowStageIndex\?: number;/);
  assert.match(sessionSource, /control\?: "continue" \| "done";/);
  assert.match(sessionSource, /const currentWorkflowPhaseCursor = workflowPhaseCursorRef\.current;/);
  assert.match(sessionSource, /workflowStageIndex: shouldResumeWorkflowStage \? currentWorkflowPhaseCursor\?\.currentStageIndex : undefined,/);
  assert.match(sessionSource, /workflowIdOverride: currentWorkflowPhaseCursor\?\.workflowId,/);
  assert.match(sessionSource, /t\("正在执行阶段 \{\{current\}\}\/\{\{total\}\}：\{\{title\}\}"/);
  assert.match(sessionSource, /let currentStageAttempt = 0;/);
  assert.match(sessionSource, /const responseControl = String\(response\.control \|\| ""\)\.trim\(\)\.toLowerCase\(\) === "done"/);
  assert.match(sessionSource, /const completionDecision = hasWorkflowStages\s*\?\s*resolveWorkflowStageCompletionDecision\(/s);
  assert.match(sessionSource, /const effectiveResponseControl = completionDecision\.control;/);
  assert.match(sessionSource, /const effectiveResponseDisplayMessage = completionDecision\.displayMessage;/);
  assert.match(sessionSource, /if \(hasWorkflowStages && effectiveResponseControl !== "done"\) \{/);
  assert.match(sessionSource, /t\("阶段 \{\{current\}\}\/\{\{total\}\} 尚未完成：\{\{reason\}\}"/);
  assert.match(sessionSource, /t\("阶段 \{\{current\}\}\/\{\{total\}\} 尚未完成，继续当前阶段…"/);
  assert.match(sessionSource, /t\("阶段 \{\{current\}\}\/\{\{total\}\} 已完成，继续下一阶段…"/);
  assert.match(sessionSource, /currentStageIndex \+= 1;/);
  assert.match(sessionSource, /appendAssistantRunSegment\(streamMessageId, \{\s*key: `workflow-stage-summary-\$\{Date\.now\(\)\}-\$\{currentStageIndex \+ 1\}`,/s);
  assert.match(sessionSource, /const responseDisplayMessage = sanitizeWorkflowStageDisplayMessage\(/);
  assert.match(sessionSource, /upsertAssistantMessageBeforeAnchorById/);
  assert.match(sessionSource, /nextContextMessages = upsertAssistantMessageBeforeAnchorById\(\s*nextContextMessages,\s*stageContextMessageId,\s*effectiveResponseDisplayMessage,\s*streamMessageId,\s*\);/s);
  assert.match(sessionSource, /filterWorkflowStageContextMessages/);
  assert.doesNotMatch(sessionSource, /setMessages\(\(prev\) => upsertAssistantMessageBeforeAnchorById\(\s*prev,\s*stageContextMessageId,\s*effectiveResponseDisplayMessage,\s*streamMessageId,\s*\)\);/s);
  assert.match(sessionSource, /workflow_stage_summary_message: sanitizeWorkflowStageDisplayMessage\(/);
  assert.match(sessionSource, /return normalizedFallbackSummary\s*\|\|\s*normalizedPayloadSummary\s*\|\|\s*normalizedExistingSummary\s*\|\|\s*translateDesktopText\("执行完成"\);/s);
  assert.doesNotMatch(sessionSource, /finishAssistantRunMessage\(streamMessageId, "finished", t\("执行过程已完成。"\)\);/);
  assert.match(sessionSource, /translateDesktopText\("（已等待约 \{\{seconds\}\} 秒）", \{ seconds: waitedSeconds \}\)/);
  assert.match(sessionSource, /value=\{runningIndicatorText\}/);
  assert.match(sessionSource, /label=\{t\("本次批准"\)\}/);
  assert.match(sessionSource, /label=\{t\("会话内批准"\)\}/);
  assert.match(sessionSource, /label=\{t\("拒绝"\)\}/);
  assert.match(sessionSource, /String\(group\.title \|\| ""\)\.trim\(\) \? \(/);
  assert.match(sessionSource, /function isTerminalTool\(/);
  assert.match(sessionSource, /function isEditTool\(/);
  assert.match(sessionSource, /toolName === "todo_write"/);
  assert.match(sessionSource, /function isCreateTool\(/);
  assert.match(sessionSource, /toolName === "mkdir"/);
  assert.match(sessionSource, /function isBrowseTool\(/);
  assert.match(sessionSource, /toolName === "todo_read"/);
  assert.match(sessionSource, /function parseJsonRecord\(/);
  assert.match(sessionSource, /const todoWriteCount = Math\.max\(/);
  assert.match(sessionSource, /const contentPreview = truncateRunText\(String\(resultData\.content_preview \|\| ""\)\.trim\(\), 64000\);/);
  assert.match(sessionSource, /const detail = diffPreview\s*\|\|\s*contentPreview/);
  assert.match(sessionSource, /edit_diff_preview: diffPreview/);
  assert.match(sessionSource, /edit_content_preview: contentPreview/);
  assert.match(sessionSource, /function renderRunSegmentBodyContent\(/);
  assert.match(sessionSource, /interface StructuredRunSegmentViewModel/);
  assert.match(sessionSource, /interface StructuredRunSegmentShellProps/);
  assert.match(sessionSource, /function StructuredRunSegmentShell\(/);
  assert.match(sessionSource, /function resolveStructuredRunSegmentViewModel\(/);
  assert.match(sessionSource, /<ChatMarkdown/);
  assert.match(sessionSource, /className=\{`desk-run-step-body \$\{runningClass\}`\.trim\(\)\}/);
  assert.match(sessionSource, /className="desk-run-segment-static-step"/);
  assert.match(sessionSource, /\{renderRunSegmentBodyContent\(segment\.text, segment\.status === "running" \? "desk-run-step-running" : ""\)\}/);
  assert.match(sessionSource, /const shouldRenderPlainBrowseDetail = segmentStepType === "browse";/);
  assert.match(sessionSource, /className="desk-run-segment-detail desk-run-segment-detail-plain"/);
  assert.match(sessionSource, /translateDesktopText\("已执行命令 \{\{command\}\}"/);
  assert.match(sessionSource, /terminal_command: command \|\| "\((?:unknown)\)"/);
  assert.match(sessionSource, /type: "terminal"/);
  assert.match(sessionSource, /label: translateDesktopText\("已执行命令"\)/);
  assert.match(sessionSource, /translateDesktopText\("文件创建"\)/);
  assert.match(sessionSource, /translateDesktopText\("已创建 \{\{path\}\}"/);
  assert.match(sessionSource, /translateDesktopText\("已编辑 \{\{file\}\} \+\{\{added\}\} -\{\{removed\}\}"/);
  assert.match(sessionSource, /translateDesktopText\("正在浏览 0 个文件,0 个搜索"\)/);
  assert.match(sessionSource, /translateDesktopText\("已浏览 0 个文件,0 个搜索"\)/);
  assert.match(sessionSource, /step: translateDesktopText\("未定义步骤"\)/);
  assert.match(sessionSource, /const canExpand = Boolean\(detail\);/);
  assert.match(sessionSource, /className="desk-run-segment-detail-summary"/);
  assert.match(sessionSource, /function resolveStructuredRunSegmentTitleClassName\(/);
  assert.match(sessionSource, /const titleClassName = resolveStructuredRunSegmentTitleClassName\(titleTone\);/);
  assert.match(sessionSource, /className=\{titleClassName\}/);
  assert.match(sessionSource, /className="desk-run-segment-detail-row"/);
  assert.match(sessionSource, /data-expandable="true"/);
  assert.match(sessionSource, /data-expandable="false"/);
  assert.match(sessionSource, /<AriContainer[\s\S]*className="desk-run-segment-detail-row"[\s\S]*role="button"[\s\S]*tabIndex=\{0\}[\s\S]*padding=\{0\}/s);
  assert.match(sessionSource, /className="desk-run-segment-detail-panel"/);
  assert.match(sessionSource, /className="desk-run-segment-detail desk-run-segment-detail-plain"/);
  assert.match(sessionSource, /className="desk-run-segment-detail-shell"/);
  assert.match(sessionSource, /<AriContainer className="desk-run-segment" padding=\{0\}>/);
  assert.match(sessionSource, /<StructuredRunSegmentShell/);
  assert.match(sessionSource, /<AriCode/);
  assert.match(sessionSource, /showLanguageTag=\{false\}/);
  assert.match(sessionSource, /fontSize="sm"/);
  assert.match(sessionSource, /renderStructuredRunSegmentFileLink\(richMeta\.filePath, onCopyFilePath\)/);
  assert.match(sessionSource, /title=\{filePath\}/);
  assert.match(sessionSource, /resolveStructuredRunSegmentTitleClassName\(/);
  assert.match(sessionSource, /structuredViewModel = resolveStructuredRunSegmentViewModel\(segment, richMeta, onCopyFilePath\)/);
  assert.match(sessionSource, /path=\{detailCodePath\}/);
  assert.match(sessionSource, /addedCount=\{detailCodeAddedCount\}/);
  assert.match(sessionSource, /removedCount=\{detailCodeRemovedCount\}/);
  assert.match(sessionSource, /diffLines=\{detailCodeDiffLines\}/);
  assert.match(sessionSource, /customLineNumbers=\{detailCodeCustomLineNumbers\}/);
  assert.match(sessionSource, /resolveRunSegmentDiffLines\(/);
  assert.match(sessionSource, /const contextRadius = 2;/);
  assert.match(sessionSource, /const buildLineNumberRanges = \(/);
  assert.match(sessionSource, /lineNumber: hasUnifiedHunkHeader \? targetLineNumber : undefined/);
  assert.match(sessionSource, /lineNumber: hasUnifiedHunkHeader \? sourceLineNumber : undefined/);
  assert.match(sessionSource, /const diffDetailPayload = richMeta\.type === "edit"/);
  assert.match(sessionSource, /type: "approval"/);
  assert.match(sessionSource, /const RUN_SEGMENT_SESSION_APPROVED_PATTERNS = buildRunSegmentTemplatePatterns\(/);
  assert.match(sessionSource, /const RUN_SEGMENT_APPROVED_ONCE_PATTERNS = buildRunSegmentTemplatePatterns\(/);
  assert.match(sessionSource, /const RUN_SEGMENT_REJECTED_PATTERNS = buildRunSegmentTemplatePatterns\(/);
  assert.match(sessionSource, /desk-run-segment-detail-title is-rejected/);
  assert.match(sessionSource, /buildRunSegmentGroups/);
  assert.match(sessionSource, /className="desk-run-group"/);
  assert.match(sessionSource, /className="desk-run-group-steps"/);
  assert.match(sessionSource, /const prunedRetryTail = pruneAssistantRetryTail\(messages, assistantMessageIndex\);/);
  assert.match(sessionSource, /setMessages\(prunedRetryTail\.messages\);/);
  assert.match(sessionSource, /isGeminiProviderNotImplementedError/);
  assert.match(sessionSource, /applySessionAiSelection\("codex"\);/);
  assert.match(sessionSource, /replaceAssistantMessageId: String\(assistantMessage\.id \|\| ""\)\.trim\(\) \|\| undefined,/);
  assert.match(sessionSource, /const prunedRetryContextMessages = buildPromptContextMessages\(\s*prunedRetryTail\.messages,\s*nextPrunedRunMetaMap,\s*\);/s);
  assert.match(sessionSource, /displayMessages: prunedRetryTail\.messages,/);
  assert.match(sessionSource, /contextMessages: prunedRetryContextMessages,/);
  assert.match(sessionSource, /className="desk-msg-hover-toolbar"/);
  assert.match(sessionSource, /content=\{t\("编辑"\)\}/);
  assert.match(sessionSource, /content=\{t\("重试"\)\}/);
  assert.doesNotMatch(sessionSource, /trigger="manual"/);
  assert.doesNotMatch(sessionSource, /hoveredRetryTooltipMessageId/);
  assert.match(sessionSource, /content=\{t\("复制"\)\}/);
  assert.match(sessionSource, /icon="edit"/);
  assert.match(sessionSource, /icon="refresh"/);
  assert.match(sessionSource, /icon="content_copy"/);
  assert.match(sessionSource, /buildAssistantFailureSummary/);
  assert.match(sessionSource, /className="desk-msg-user-surface"/);
  assert.match(sessionSource, /className="desk-msg-assistant-surface"/);
  assert.match(sessionSource, /className="desk-run-failure-card"/);
  assert.match(sessionSource, /if \(nextSkillIds\.length > 0\) \{\s*setExecutionSelection\(buildSkillExecutionSelection\(nextSkillIds\)\);/s);
  // 描述：
  //
  //   - 样式层应提供弹窗列表与选中态样式，确保与设计图一致的列表结构。
  assert.match(styleSource, /\.desk-session-strategy-modal-body/);
  assert.match(styleSource, /\.desk-session-strategy-list/);
  assert.match(styleSource, /\.desk-session-strategy-item/);
  assert.match(styleSource, /\.desk-session-strategy-item\.is-active/);
  assert.match(styleSource, /\.desk-prompt-toolbar-select/);
  assert.match(styleSource, /\.desk-prompt-toolbar-select-provider/);
  assert.match(styleSource, /\.desk-prompt-toolbar-select-strategy/);
  assert.match(styleSource, /\.desk-msg-hover-toolbar/);
  assert.match(styleSource, /\.desk-msg\.assistant \.desk-msg-hover-toolbar/);
  assert.match(styleSource, /\.desk-msg:hover \.desk-msg-hover-toolbar/);
  assert.match(styleSource, /\.desk-msg \[class\^="desk-"\],\s*\.desk-msg \[class\*=" desk-"\] \{[\s\S]*border-radius:\s*0 !important;/);
  assert.match(styleSource, /\.desk-msg-user-surface/);
  assert.match(styleSource, /\.desk-msg-user-surface \{[^}]*border:\s*var\(--desk-border-width\)\s+solid\s+var\(--desk-panel-border-color\);[^}]*\}/);
  assert.match(styleSource, /\.desk-msg-user-surface \{[^}]*background:\s*var\(--z-color-bg-tertiary\);[^}]*\}/);
  assert.match(styleSource, /\.desk-msg-user-surface \{[^}]*box-shadow:\s*none;[^}]*\}/);
  assert.doesNotMatch(styleSource, /\.desk-msg-user-surface \{[^}]*var\(--z-color-primary\)[^}]*\}/);
  assert.match(styleSource, /\.desk-msg-assistant-surface/);
  assert.match(styleSource, /\.desk-run-failure-card/);
  assert.match(styleSource, /\.desk-run-summary-failed/);
  assert.match(styleSource, /\.desk-run-segment-detail-row/);
  assert.match(styleSource, /\.desk-run-step \{[\s\S]*font-size:\s*var\(--desk-run-step-font-size\);[\s\S]*line-height:\s*var\(--desk-run-step-line-height\);/);
  assert.match(styleSource, /\.desk-run-step-body \{[\s\S]*font-size:\s*var\(--desk-run-step-font-size\);[\s\S]*line-height:\s*var\(--desk-run-step-line-height\);[\s\S]*color:\s*var\(--desk-run-text-primary\);/);
  assert.match(styleSource, /\.desk-run-step-body \.desk-md-text-block \{[\s\S]*gap:\s*var\(--z-inset-xs\);/);
  assert.match(styleSource, /\.desk-run-step-rich \{[\s\S]*align-items:\s*baseline;/);
  assert.match(styleSource, /\.desk-run-step-rich \{[\s\S]*padding:\s*var\(--z-inset-sm\);/);
  assert.match(styleSource, /\.desk-run-step-file-link \{[\s\S]*max-inline-size:\s*min\(100%,\s*calc\(var\(--z-inset\)\s*\*\s*24\)\);/);
  assert.match(styleSource, /\.desk-run-step-file-link \{[\s\S]*text-overflow:\s*ellipsis;/);
  assert.match(styleSource, /\.desk-run-step-file-link \{[\s\S]*white-space:\s*nowrap;/);
  assert.match(styleSource, /\.desk-run-segment \{[\s\S]*padding:\s*0;/);
  assert.match(styleSource, /\.desk-run-segment-detail-shell \{[\s\S]*padding-left:\s*var\(--z-inset\)\s*!important;/);
  assert.match(styleSource, /\.desk-run-segment-detail-row \{[\s\S]*font:\s*inherit;/);
  assert.match(styleSource, /\.desk-run-segment-detail-row \{[\s\S]*grid-template-columns:\s*var\(--desk-run-step-prefix-min-inline-size\)\s+minmax\(0,\s*1fr\)\s+auto;/);
  assert.match(styleSource, /\.desk-run-segment-detail-row \{[\s\S]*cursor:\s*default;/);
  assert.match(styleSource, /\.desk-run-segment-detail-row\[data-expandable="true"\] \{[\s\S]*cursor:\s*pointer;/);
  assert.match(styleSource, /\.desk-run-segment-detail-title \{/);
  assert.match(styleSource, /\.desk-run-segment-detail-title\.is-rejected \{/);
  assert.match(styleSource, /\.desk-run-segment-detail-title\.is-muted \{/);
  assert.match(styleSource, /\.desk-run-segment-detail-summary \{/);
  assert.match(styleSource, /\.desk-run-segment-detail-summary-text \{/);
  assert.match(styleSource, /\.desk-run-segment-static-step \{[\s\S]*font:\s*inherit;/);
  assert.match(styleSource, /\.desk-run-segment-detail-panel/);
  assert.match(styleSource, /\.desk-run-segment-detail-panel \{[\s\S]*border-radius:\s*0;/);
  assert.match(styleSource, /\.desk-run-segment-detail \{[\s\S]*min-width:\s*0;/);
  assert.match(styleSource, /\.desk-run-segment-detail-row\[data-expandable="true"\]:hover \.desk-run-segment-detail-arrow/);
  assert.match(styleSource, /\.desk-run-group/);
  assert.match(styleSource, /\.desk-run-group-steps/);
  assert.match(styleSource, /\.desk-run-thinking-indicator/);
  assert.match(styleSource, /\.desk-run-segment-static-step/);
  assert.match(styleSource, /\.desk-run-segment-detail-code \{[\s\S]*padding-right:\s*var\(--z-inset-sm\);[\s\S]*padding-bottom:\s*var\(--z-inset-sm\);/);
  assert.match(styleSource, /\.desk-run-segment-detail-plain \{[\s\S]*padding-right:\s*var\(--z-inset-sm\);[\s\S]*padding-bottom:\s*var\(--z-inset-sm\);[\s\S]*border-radius:\s*0;/);
});
