// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"context"
	"fmt"

	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/entitysql"

	"git.zodileap.com/entity/account_v1/internal"
)

const AccountTag = "account"

// Account  is an struct of the database
type Account struct {
	*internal.Dialect
	tracker entity.Tracker
	// Agents 智能体基础信息
	Agents *agententityBuilder
	// AgentAccesss 用户智能体授权
	AgentAccesss *agentaccessentityBuilder
	// Users 平台用户
	Users *userentityBuilder
}

type accountEntityFlag interface {
	isAccountEntity()
}

func (e *AgentEntity) isAccountEntity()       {}
func (e *AgentAccessEntity) isAccountEntity() {}
func (e *UserEntity) isAccountEntity()        {}

// NewAccount creates a new Account instance.
func NewAccount() (*Account, error) {
	dialect, err := internal.NewDialect(AccountTag)
	if err != nil {
		return nil, err
	}
	account := &Account{
		Dialect: dialect,
		tracker: &entity.Tracking{},
	}
	account.init()
	return account, nil
}

// Close closes the database.
func (d *Account) Close() error {
	return d.Driver.Close()
}

// Save saves all changes to the database.
func (d *Account) Save(ctx context.Context) error {
	tx, err := d.Dialect.MayTx(ctx)
	if err != nil {
		return err
	}
	if err := func() error {
		for _, m := range d.tracker.Mutators() {
			if err := m.Exec(ctx, tx); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return entitysql.Rollback(tx, err)
	}
	return tx.Commit()
}

// Remove will remove the entity from the database. The changes will be saved when Save is called.
func (d *Account) Remove(e accountEntityFlag) error {
	switch e.(type) {
	case *AgentEntity:
		d.Agents.Remove(e.(*AgentEntity))
	case *AgentAccessEntity:
		d.AgentAccesss.Remove(e.(*AgentAccessEntity))
	case *UserEntity:
		d.Users.Remove(e.(*UserEntity))
	default:
		return fmt.Errorf("database Account does not support entity type %T", e)
	}
	return nil
}

func (d *Account) init() {
	agententityConfig := newAgentEntityConfig(d.Dialect)
	agentaccessentityConfig := newAgentAccessEntityConfig(d.Dialect)
	userentityConfig := newUserEntityConfig(d.Dialect)

	d.Agents = newAgentEntityBuilder(agententityConfig, d.tracker)
	d.tracker.Add(d.Agents)

	d.AgentAccesss = newAgentAccessEntityBuilder(agentaccessentityConfig, d.tracker)
	d.tracker.Add(d.AgentAccesss)

	d.Users = newUserEntityBuilder(userentityConfig, d.tracker)
	d.tracker.Add(d.Users)
}
