// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"git.zodileap.com/entity/account_v1/internal"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

type agententityRelation struct {
	Config   internal.EntityConfig
	relation entitysql.RelationDesc
	children []rel
}

func newAgententityRelation(config internal.EntityConfig, desc entitysql.RelationDesc) *agententityRelation {
	return &agententityRelation{
		Config:   config,
		relation: desc,
		children: []rel{},
	}
}

func (r *agententityRelation) Where(predicates ...entitysql.PredicateFunc) *agententityRelation {
	r.relation.Predicates = append(r.relation.Predicates, predicates...)
	return r
}

func (r *agententityRelation) Include(rels ...agententityRel) *agententityRelation {
	// Create a slice of type Rel with the same length as r.children
	newRels := make([]rel, len(rels))
	for i, r := range rels {
		// Convert each agententityRel to Rel and store it in the new slice
		newRels[i] = rel(r)
	}
	r.children = append(r.children, newRels...)
	return r
}

func (r *agententityRelation) Desc() (entitysql.RelationDesc, []rel, internal.EntityConfig) {
	return r.relation, r.children, r.Config
}

func (r *agententityRelation) reset() {
	for _, child := range r.children {
		child.reset()
	}
	r.relation.Reset()
	r.children = []rel{}
}
