// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"fmt"
	"time"

	"git.zodileap.com/entity/account_v1/agent"
	"git.zodileap.com/entity/account_v1/internal"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// 智能体基础信息
type AgentEntity struct {
	internal.Entity `json:"-"`
	config          *agententityConfig
	Id              *agent_Id        `json:"id"`                   // Id 主键Id
	Code            *agent_Code      `json:"code"`                 // Code 智能体编码
	Name            *agent_Name      `json:"name"`                 // Name 智能体名称
	Version         *agent_Version   `json:"version"`              // Version 版本
	Status          *agent_Status    `json:"status"`               // Status 状态
	Remark          *agent_Remark    `json:"remark"`               // Remark 备注
	CreatedAt       *agent_CreatedAt `json:"created_at"`           // CreatedAt 创建数据时间
	LastAt          *agent_LastAt    `json:"last_at"`              // LastAt 更新数据时间
	DeletedAt       *agent_DeletedAt `json:"deleted_at,omitempty"` // DeletedAt 删除数据时间（逻辑删除）
}

// agententityConfig holds the configuration for the AgentEntity.
type agententityConfig struct {
	internal.EntityConfig
	*internal.Dialect
	*entity.Mutation
	*agententityMutations
	name string
}

func newAgentEntityConfig(c *internal.Dialect) *agententityConfig {
	return &agententityConfig{
		Dialect:              c,
		agententityMutations: newAgentEntityMutations(),
		name:                 "agent",
	}
}

// New creates a new AgentEntity, but does not add tracking.
func (c *agententityConfig) New() internal.Entity {
	b := entity.NewMutation(entity.Detached)
	e := &AgentEntity{
		config: &agententityConfig{
			Mutation:             b,
			Dialect:              c.Dialect,
			agententityMutations: c.agententityMutations,
		},
	}
	e.setState(entity.Detached)
	e.Id = newAgent_Id(e.config)
	e.Code = newAgent_Code(e.config)
	e.Name = newAgent_Name(e.config)
	e.Version = newAgent_Version(e.config)
	e.Status = newAgent_Status(e.config)
	e.Remark = newAgent_Remark(e.config)
	e.CreatedAt = newAgent_CreatedAt(e.config)
	e.LastAt = newAgent_LastAt(e.config)
	e.DeletedAt = newAgent_DeletedAt(e.config)
	return e
}

func (c *agententityConfig) Desc() internal.EntityConfigDesc {
	return internal.EntityConfigDesc{
		Name: c.name,
	}
}

// String implements the fmt.Stringer interface.
func (e *AgentEntity) String() string {
	return fmt.Sprintf("{ Id: %v, Code: %v, Name: %v, Version: %v, Status: %v, Remark: %v, CreatedAt: %v, LastAt: %v, DeletedAt: %v}",
		e.Id,
		e.Code,
		e.Name,
		e.Version,
		e.Status,
		e.Remark,
		e.CreatedAt,
		e.LastAt,
		e.DeletedAt,
	)
}

// State returns the state of the AgentEntity.
func (e *AgentEntity) State() entity.EntityState {
	return e.config.State()
}

// remove removes the AgentEntity from the database.
func (e *AgentEntity) remove() error {
	return e.setState(entity.Deleted)
}

// create creates a new AgentEntity and adds tracking.
func (e *AgentEntity) create(code string, name string, options ...func(*AgentEntity)) (*AgentEntity, error) {
	e.setState(entity.Added)
	e.Code.Set(code)
	e.Name.Set(name)
	for _, option := range options {
		option(e)
	}
	return e, nil
}

// setUnchanged sets the state of the AgentEntity to unchanged.
func (e *AgentEntity) setUnchanged() error {
	return e.setState(entity.Unchanged)
}

// setState sets the state of the AgentEntity.
func (e *AgentEntity) setState(state entity.EntityState) error {
	return e.config.agententityMutations.SetEntityState(e, state)
}

// scan scans the database for the AgentEntity.
func (e *AgentEntity) scan(fields []entitysql.ScannerField) []any {
	if len(fields) == 0 {
		args := make([]any, len(agent.Columns))
		for i, c := range agent.Columns {
			switch c.String() {
			case agent.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case agent.FieldCode.Name.String():
				v := e.Code
				v.Set(*new(string))
				args[i] = v
			case agent.FieldName.Name.String():
				v := e.Name
				v.Set(*new(string))
				args[i] = v
			case agent.FieldVersion.Name.String():
				v := e.Version
				v.Set(*new(string))
				args[i] = v
			case agent.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case agent.FieldRemark.Name.String():
				v := e.Remark
				v.Set(*new(string))
				args[i] = v
			case agent.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	} else {
		args := make([]any, len(fields))
		for i := range fields {
			switch fields[i].String() {
			case agent.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case agent.FieldCode.Name.String():
				v := e.Code
				v.Set(*new(string))
				args[i] = v
			case agent.FieldName.Name.String():
				v := e.Name
				v.Set(*new(string))
				args[i] = v
			case agent.FieldVersion.Name.String():
				v := e.Version
				v.Set(*new(string))
				args[i] = v
			case agent.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case agent.FieldRemark.Name.String():
				v := e.Remark
				v.Set(*new(string))
				args[i] = v
			case agent.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	}
}

func (e *AgentEntity) createRel(buidler *entitysql.ScannerBuilder, scanner *internal.QueryScanner) {
	switch scanner.Config.Desc().Name {
	}
}

func mergeAgentEntity(es []*AgentEntity, e *AgentEntity) []*AgentEntity {
	if e == nil {
		return es
	}
	if len(es) == 0 {
		es = append(es, e)
	} else {
		v := es[len(es)-1]

		if v.Id.Get() == e.Id.Get() {
		} else {
			es = append(es, e)
		}
	}
	return es
}
