// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"context"
	"time"

	"git.zodileap.com/entity/account_v1/agent"
	"git.zodileap.com/entity/account_v1/internal"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// agententityBuilder is a builder for the AgentEntity entity.
//
// The builder is used to create, update, and delete AgentEntity entities.
type agententityBuilder struct {
	config    *agententityConfig
	tracker   entity.Tracker
	Id        agent.PredId        // Id 主键Id
	Code      agent.PredCode      // Code 智能体编码
	Name      agent.PredName      // Name 智能体名称
	Version   agent.PredVersion   // Version 版本
	Status    agent.PredStatus    // Status 状态
	Remark    agent.PredRemark    // Remark 备注
	CreatedAt agent.PredCreatedAt // CreatedAt 创建数据时间
	LastAt    agent.PredLastAt    // LastAt 更新数据时间
	DeletedAt agent.PredDeletedAt // DeletedAt 删除数据时间（逻辑删除）
	// ById configures the query to sort results based on the 'id' field of the entity.
	// Sorting entities in ascending order by default.
	ById agent.ById
	// ByCode configures the query to sort results based on the 'code' field of the entity.
	// Sorting entities in ascending order by default.
	ByCode agent.ByCode
	// ByName configures the query to sort results based on the 'name' field of the entity.
	// Sorting entities in ascending order by default.
	ByName agent.ByName
	// ByVersion configures the query to sort results based on the 'version' field of the entity.
	// Sorting entities in ascending order by default.
	ByVersion agent.ByVersion
	// ByStatus configures the query to sort results based on the 'status' field of the entity.
	// Sorting entities in ascending order by default.
	ByStatus agent.ByStatus
	// ByRemark configures the query to sort results based on the 'remark' field of the entity.
	// Sorting entities in ascending order by default.
	ByRemark agent.ByRemark
	// ByCreatedAt configures the query to sort results based on the 'created_at' field of the entity.
	// Sorting entities in ascending order by default.
	ByCreatedAt agent.ByCreatedAt
	// ByLastAt configures the query to sort results based on the 'last_at' field of the entity.
	// Sorting entities in ascending order by default.
	ByLastAt agent.ByLastAt
	// ByDeletedAt configures the query to sort results based on the 'deleted_at' field of the entity.
	// Sorting entities in ascending order by default.
	ByDeletedAt agent.ByDeletedAt
}

// newAgentEntityBuilder creates a new AgentEntityBuilder .
func newAgentEntityBuilder(c *agententityConfig, t entity.Tracker) *agententityBuilder {
	return &agententityBuilder{
		config:  c,
		tracker: t,
	}
}

// Create creates a new UserEntity，and add it to the tracker.
// Required parameters are fields that have no default value but are required,
// and options are fields that can be left empty by calling WithFieldName.
func (b *agententityBuilder) Create(code string, name string, options ...func(*AgentEntity)) (*AgentEntity, error) {
	e := b.config.New()
	switch t := e.(type) {
	case *AgentEntity:
		return t.create(code, name, options...)
	default:
		return nil, entity.Err_0100030006
	}
}

func (b *agententityBuilder) Remove(e *AgentEntity) error {
	if e.config.Mutation == nil {
		return nil
	}
	return e.remove()
}

// First returns the first AgentEntity.
func (s *agententityBuilder) First(ctx context.Context) (*AgentEntity, error) {
	query := s.initQuery()
	return query.First(ctx)
}

func (s *agententityBuilder) ToList(ctx context.Context) ([]*AgentEntity, error) {
	query := s.initQuery()
	return query.ToList(ctx)
}

func (s *agententityBuilder) Include(rels ...agententityRel) *AgentEntityQuery {
	query := s.initQuery()
	return query.Include(rels...)
}

func (s *agententityBuilder) Order(o ...agent.OrderTerm) *AgentEntityQuery {
	query := s.initQuery()
	return query.Order(o...)
}

func (s *agententityBuilder) Where(conditions ...entitysql.PredicateFunc) *AgentEntityQuery {
	query := s.initQuery()
	return query.Where(conditions...)
}

// WithId sets the "id" field of the AgentEntity.
func (s *agententityBuilder) WithId(id int64) func(*AgentEntity) {
	return func(e *AgentEntity) {
		e.Id.Set(id)
	}
}

// WithVersion sets the "version" field of the AgentEntity.
func (s *agententityBuilder) WithVersion(version string) func(*AgentEntity) {
	return func(e *AgentEntity) {
		e.Version.Set(version)
	}
}

// WithStatus sets the "status" field of the AgentEntity.
func (s *agententityBuilder) WithStatus(status int16) func(*AgentEntity) {
	return func(e *AgentEntity) {
		e.Status.Set(status)
	}
}

// WithRemark sets the "remark" field of the AgentEntity.
func (s *agententityBuilder) WithRemark(remark string) func(*AgentEntity) {
	return func(e *AgentEntity) {
		e.Remark.Set(remark)
	}
}

// WithCreatedAt sets the "created_at" field of the AgentEntity.
func (s *agententityBuilder) WithCreatedAt(createdat time.Time) func(*AgentEntity) {
	return func(e *AgentEntity) {
		e.CreatedAt.Set(createdat)
	}
}

// WithLastAt sets the "last_at" field of the AgentEntity.
func (s *agententityBuilder) WithLastAt(lastat time.Time) func(*AgentEntity) {
	return func(e *AgentEntity) {
		e.LastAt.Set(lastat)
	}
}

// WithDeletedAt sets the "deleted_at" field of the AgentEntity.
func (s *agententityBuilder) WithDeletedAt(deletedat time.Time) func(*AgentEntity) {
	return func(e *AgentEntity) {
		e.DeletedAt.Set(deletedat)
	}
}

// Exec executes all the agententityMutations for the AgentEntity.
func (s *agententityBuilder) Exec(ctx context.Context, tx dialect.Tx) error {
	if len(s.config.agententityMutations.Addeds) > 0 {
		e := s.config.agententityMutations.Get(entity.Added)
		n := newAgentEntityCreate(s.config.Dialect, e...)
		if err := n.create(ctx, tx); err != nil {
			return err
		}
	}
	if len(s.config.agententityMutations.Modifieds) > 0 {
		e := s.config.agententityMutations.Get(entity.Modified)
		n := newAgentEntityUpdate(s.config.Dialect, e...)
		if err := n.update(ctx, tx); err != nil {
			return err
		}
	}
	if len(s.config.agententityMutations.Deleteds) > 0 {
		e := s.config.agententityMutations.Get(entity.Deleted)
		n := newAgentEntityDelete(s.config.Dialect, e...)
		if err := n.delete(ctx, tx); err != nil {
			return err
		}
	}
	return nil
}

func (s *agententityBuilder) initQuery() *AgentEntityQuery {
	return newAgentEntityQuery(s.config.Dialect, s.tracker, s.config.agententityMutations)
}

// agententityMutations is a collection of AgentEntity mutation.
type agententityMutations struct {
	Detacheds  map[string]*AgentEntity
	Unchangeds map[string]*AgentEntity
	Deleteds   map[string]*AgentEntity
	Modifieds  map[string]*AgentEntity
	Addeds     map[string]*AgentEntity
}

// newAgentEntityMutations creates a new mutations.
func newAgentEntityMutations() *agententityMutations {
	return &agententityMutations{
		Detacheds:  make(map[string]*AgentEntity),
		Unchangeds: make(map[string]*AgentEntity),
		Deleteds:   make(map[string]*AgentEntity),
		Modifieds:  make(map[string]*AgentEntity),
		Addeds:     make(map[string]*AgentEntity),
	}
}

// Get returns all the AgentEntity in the specified state.
func (ms *agententityMutations) Get(state entity.EntityState) []*AgentEntity {
	switch state {
	case entity.Detached:
		s := make([]*AgentEntity, 0, len(ms.Detacheds))
		for _, m := range ms.Detacheds {
			s = append(s, m)
		}
		return s
	case entity.Unchanged:
		s := make([]*AgentEntity, 0, len(ms.Unchangeds))
		for _, m := range ms.Unchangeds {
			s = append(s, m)
		}
		return s
	case entity.Deleted:
		s := make([]*AgentEntity, 0, len(ms.Deleteds))
		for _, m := range ms.Deleteds {
			s = append(s, m)
		}
		return s
	case entity.Modified:
		s := make([]*AgentEntity, 0, len(ms.Modifieds))
		for _, m := range ms.Modifieds {
			s = append(s, m)
		}
		return s
	case entity.Added:
		s := make([]*AgentEntity, 0, len(ms.Addeds))
		for _, m := range ms.Addeds {
			s = append(s, m)
		}
		return s
	}
	return nil
}

// SetEntityState sets the state of the entity.
func (ms *agententityMutations) SetEntityState(e *AgentEntity, state entity.EntityState) error {
	m := e.config.Mutation
	ms.set(e, state)
	if err := internal.SetEntityState(m, state); err != nil {
		return err
	}
	return nil
}

// ChangeEntityState attempts to set the desired entity state,
// but will not do so if the conditions are not met.
func (ms *agententityMutations) ChangeEntityState(m *entity.Mutation, state entity.EntityState) {
	e := ms.getEntity(m)
	ms.set(e, state)
	if err := internal.SetEntityState(m, state); err != nil {
		return
	}
}

// getEntity returns the entity in the specified state.
func (ms *agententityMutations) getEntity(m *entity.Mutation) *AgentEntity {
	key := m.Key()
	switch m.State() {
	case entity.Detached:
		return ms.Detacheds[key]
	case entity.Unchanged:
		return ms.Unchangeds[key]
	case entity.Deleted:
		return ms.Deleteds[key]
	case entity.Modified:
		return ms.Modifieds[key]
	case entity.Added:
		return ms.Addeds[key]
	}
	return nil
}

// Set sets the entity in the specified state.
func (ms *agententityMutations) set(e *AgentEntity, state entity.EntityState) {
	m := e.config.Mutation
	key := m.Key()
	switch m.State() {
	case entity.Detached:
		delete(ms.Detacheds, key)
	case entity.Unchanged:
		delete(ms.Unchangeds, key)
	case entity.Deleted:
		delete(ms.Deleteds, key)
	case entity.Modified:
		delete(ms.Modifieds, key)
	case entity.Added:
		delete(ms.Addeds, key)
	}
	if state >= 0 {
		switch state {
		case entity.Detached:
			ms.Detacheds[key] = e
		case entity.Unchanged:
			ms.Unchangeds[key] = e
		case entity.Deleted:
			ms.Deleteds[key] = e
		case entity.Modified:
			ms.Modifieds[key] = e
		case entity.Added:
			ms.Addeds[key] = e
		}
	}
}
