// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"time"

	"git.zodileap.com/entity/account_v1/user_identity"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/field"
)

// userIdentity_Id is Id field
type userIdentity_Id struct {
	field.IntStorage[int64]
	config *useridentityentityConfig
}

// newuserIdentity_Id creates a new userIdentity_Id
func newUserIdentity_Id(c *useridentityentityConfig) *userIdentity_Id {
	t := &userIdentity_Id{}
	t.config = c
	return t
}

// Set sets the value of Id field
func (t *userIdentity_Id) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldId.Name.String())
	}
}

// Get gets the value of Id field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *userIdentity_Id) Get() int64 {
	return *t.IntStorage.Get()
}

// userIdentity_UserId is UserId field
type userIdentity_UserId struct {
	field.StringStorage[string]
	config *useridentityentityConfig
}

// newuserIdentity_UserId creates a new userIdentity_UserId
func newUserIdentity_UserId(c *useridentityentityConfig) *userIdentity_UserId {
	t := &userIdentity_UserId{}
	t.config = c
	return t
}

// Set sets the value of UserId field
func (t *userIdentity_UserId) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldUserId.Name.String())
	}
}

// Get gets the value of UserId field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *userIdentity_UserId) Get() string {
	return *t.StringStorage.Get()
}

// userIdentity_IdentityType is IdentityType field
type userIdentity_IdentityType struct {
	field.StringStorage[string]
	config *useridentityentityConfig
}

// newuserIdentity_IdentityType creates a new userIdentity_IdentityType
func newUserIdentity_IdentityType(c *useridentityentityConfig) *userIdentity_IdentityType {
	t := &userIdentity_IdentityType{}
	t.config = c
	return t
}

// Set sets the value of IdentityType field
func (t *userIdentity_IdentityType) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldIdentityType.Name.String())
	}
}

// Get gets the value of IdentityType field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *userIdentity_IdentityType) Get() string {
	return *t.StringStorage.Get()
}

// userIdentity_ScopeCode is ScopeCode field
type userIdentity_ScopeCode struct {
	field.StringStorage[string]
	config *useridentityentityConfig
}

// newuserIdentity_ScopeCode creates a new userIdentity_ScopeCode
func newUserIdentity_ScopeCode(c *useridentityentityConfig) *userIdentity_ScopeCode {
	t := &userIdentity_ScopeCode{}
	t.config = c
	return t
}

// Set sets the value of ScopeCode field
func (t *userIdentity_ScopeCode) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldScopeCode.Name.String())
	}
}

// Get gets the value of ScopeCode field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *userIdentity_ScopeCode) Get() string {
	return *t.StringStorage.Get()
}

// userIdentity_ScopeName is ScopeName field
type userIdentity_ScopeName struct {
	field.StringStorage[string]
	config *useridentityentityConfig
}

// newuserIdentity_ScopeName creates a new userIdentity_ScopeName
func newUserIdentity_ScopeName(c *useridentityentityConfig) *userIdentity_ScopeName {
	t := &userIdentity_ScopeName{}
	t.config = c
	return t
}

// Set sets the value of ScopeName field
func (t *userIdentity_ScopeName) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldScopeName.Name.String())
	}
}

// Get gets the value of ScopeName field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *userIdentity_ScopeName) Get() string {
	return *t.StringStorage.Get()
}

// userIdentity_RoleCodes is RoleCodes field
type userIdentity_RoleCodes struct {
	field.StringStorage[string]
	config *useridentityentityConfig
}

// newuserIdentity_RoleCodes creates a new userIdentity_RoleCodes
func newUserIdentity_RoleCodes(c *useridentityentityConfig) *userIdentity_RoleCodes {
	t := &userIdentity_RoleCodes{}
	t.config = c
	return t
}

// Set sets the value of RoleCodes field
func (t *userIdentity_RoleCodes) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldRoleCodes.Name.String())
	}
}

// Get gets the value of RoleCodes field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userIdentity_RoleCodes) Get() *string {
	return t.StringStorage.Get()
}

// userIdentity_Status is Status field
type userIdentity_Status struct {
	field.IntStorage[int16]
	config *useridentityentityConfig
}

// newuserIdentity_Status creates a new userIdentity_Status
func newUserIdentity_Status(c *useridentityentityConfig) *userIdentity_Status {
	t := &userIdentity_Status{}
	t.config = c
	return t
}

// Set sets the value of Status field
func (t *userIdentity_Status) Set(v int16) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldStatus.Name.String())
	}
}

// Get gets the value of Status field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userIdentity_Status) Get() *int16 {
	return t.IntStorage.Get()
}

// userIdentity_CreatedAt is CreatedAt field
type userIdentity_CreatedAt struct {
	field.TimestampStorage[time.Time]
	config *useridentityentityConfig
}

// newuserIdentity_CreatedAt creates a new userIdentity_CreatedAt
func newUserIdentity_CreatedAt(c *useridentityentityConfig) *userIdentity_CreatedAt {
	t := &userIdentity_CreatedAt{}
	t.config = c
	return t
}

// Set sets the value of CreatedAt field
func (t *userIdentity_CreatedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldCreatedAt.Name.String())
	}
}

// Get gets the value of CreatedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userIdentity_CreatedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// userIdentity_LastAt is LastAt field
type userIdentity_LastAt struct {
	field.TimestampStorage[time.Time]
	config *useridentityentityConfig
}

// newuserIdentity_LastAt creates a new userIdentity_LastAt
func newUserIdentity_LastAt(c *useridentityentityConfig) *userIdentity_LastAt {
	t := &userIdentity_LastAt{}
	t.config = c
	return t
}

// Set sets the value of LastAt field
func (t *userIdentity_LastAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldLastAt.Name.String())
	}
}

// Get gets the value of LastAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userIdentity_LastAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// userIdentity_DeletedAt is DeletedAt field
type userIdentity_DeletedAt struct {
	field.TimestampStorage[time.Time]
	config *useridentityentityConfig
}

// newuserIdentity_DeletedAt creates a new userIdentity_DeletedAt
func newUserIdentity_DeletedAt(c *useridentityentityConfig) *userIdentity_DeletedAt {
	t := &userIdentity_DeletedAt{}
	t.config = c
	return t
}

// Set sets the value of DeletedAt field
func (t *userIdentity_DeletedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.useridentityentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_identity.FieldDeletedAt.Name.String())
	}
}

// Get gets the value of DeletedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userIdentity_DeletedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}
