// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"context"

	"git.zodileap.com/entity/account_v1/internal"
	"git.zodileap.com/entity/account_v1/user_identity"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// UserIdentityEntityDelete is the delete action for the UserIdentityEntity.
type UserIdentityEntityDelete struct {
	config     *internal.Dialect
	es         []*UserIdentityEntity
	predicates []entitysql.PredicateFunc
}

// newUserIdentityEntityDelete creates a new UserIdentityEntityDelete.
func newUserIdentityEntityDelete(c *internal.Dialect, es ...*UserIdentityEntity) *UserIdentityEntityDelete {
	return &UserIdentityEntityDelete{
		config: c,
		es:     es,
	}
}

// Where adds a predicate to the delete action.
func (o *UserIdentityEntityDelete) Where(predicates ...entitysql.PredicateFunc) *UserIdentityEntityDelete {
	o.predicates = append(o.predicates, predicates...)
	return o
}

func (o *UserIdentityEntityDelete) delete(ctx context.Context, tx dialect.Tx) error {
	return o.sqlDelete(ctx, tx)
}

func (o *UserIdentityEntityDelete) sqlDelete(ctx context.Context, tx dialect.Tx) error {
	var (
		spec, err = o.deleteSpec()
		affected  = int64(0)
	)
	if err != nil {
		return err
	}
	spec.Affected = &affected
	if err := entitysql.NewDelete(ctx, tx, spec); err != nil {
		return err
	}
	for _, e := range o.es {
		if err := e.setState(entity.Detached); err != nil {
			return err
		}
	}
	return nil
}

func (o *UserIdentityEntityDelete) deleteSpec() (*entitysql.DeleteSpec, error) {
	spec := entitysql.NewDeleteSpec(user_identity.Entity)
	if ps := o.predicates; len(ps) > 0 {
		spec.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	predId := &user_identity.PredId{}
	if o.predicates == nil {
		o.predicates = make([]entitysql.PredicateFunc, 0, len(o.es))
	}
	for i, e := range o.es {
		if i >= 1 {
			o.predicates = append(o.predicates, entitysql.Or)
		}
		o.predicates = append(o.predicates, predId.EQ(e.Id.Get()))
	}
	if ps := o.predicates; len(ps) > 0 {
		spec.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	return spec, nil
}
