// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"context"

	"git.zodileap.com/entity/account_v1/internal"
	"git.zodileap.com/entity/account_v1/user_info"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// UserEntityUpdate is the update action for the UserEntity.
type UserEntityUpdate struct {
	config     *internal.Dialect
	ctx        *entitysql.QueryContext
	tracker    entity.Tracker
	es         []*UserEntity
	predicates [][]entitysql.PredicateFunc
	sets       []map[string]entitysql.CaseSpec
	total      int
	batchIndex []int
}

// newUserEntityUpdate creates a new UserEntityUpdate.
func newUserEntityUpdate(c *internal.Dialect, es ...*UserEntity) *UserEntityUpdate {
	return &UserEntityUpdate{
		config:     c,
		ctx:        &entitysql.QueryContext{},
		es:         es,
		predicates: [][]entitysql.PredicateFunc{},
		batchIndex: []int{0},
	}
}

func (o *UserEntityUpdate) update(ctx context.Context, tx dialect.Tx) error {
	return o.sqlUpdate(ctx, tx)
}

func (o *UserEntityUpdate) sqlUpdate(ctx context.Context, tx dialect.Tx) error {
	var (
		spec, err = o.updateSpec()
		res       = o.es
		cursor    = 0
	)
	if err != nil {
		return err
	}
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := res[cursor]
		cursor++
		args := e.scan(fields)
		if err := rows.Scan(args...); err != nil {
			return err
		} else {
			res = append(res, e)
			return e.setUnchanged()
		}
	}
	return entitysql.NewUpdate(ctx, tx, spec)
}

func (o *UserEntityUpdate) updateSpec() (*entitysql.UpdateSpec, error) {
	spec := entitysql.NewUpdateSpec(user_info.Entity, user_info.Columns)
	if len(o.predicates) != len(o.sets) {
		return nil, entity.Err_0100030005
	}
	if err := o.setEntity(spec); err != nil {
		return nil, err
	}
	o.mergeArgs(spec)
	return spec, nil
}

// setEntity 用于在updateSpec中设置[]*UserEntity的配置，
// 一般来说这个setEntity里的entity都是通过状态追踪，自动添加的。
func (o *UserEntityUpdate) setEntity(spec *entitysql.UpdateSpec) error {
	predId := &user_info.PredId{}
	num := 0
	for i, e := range o.es {
		fields := e.config.Mutation.Fields()
		if len(fields) == 0 {
			return entity.Err_0100030002.Sprintf(e.config.Tag)
		}
		o.predicates = append(o.predicates, []entitysql.PredicateFunc{})
		o.sets = append(o.sets, map[string]entitysql.CaseSpec{})
		// 因为判断过predicates和set长度，所以这里默认等长
		index := len(o.predicates) - 1
		if i > 0 {
			o.predicates[index] = append(o.predicates[index], entitysql.Or, predId.EQ(e.Id.Get()))
		} else {
			o.predicates[index] = append(o.predicates[index], predId.EQ(e.Id.Get()))
		}
		num++
		for _, f := range fields {
			switch f {
			case user_info.FieldId.Name.String():
				v, err := e.Id.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldId.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Id.SqlFormatParam()
				o.sets[index][user_info.FieldId.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldName.Name.String():
				v, err := e.Name.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldName.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Name.SqlFormatParam()
				o.sets[index][user_info.FieldName.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldEmail.Name.String():
				v, err := e.Email.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldEmail.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Email.SqlFormatParam()
				o.sets[index][user_info.FieldEmail.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldPhone.Name.String():
				v, err := e.Phone.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldPhone.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Phone.SqlFormatParam()
				o.sets[index][user_info.FieldPhone.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldPassword.Name.String():
				v, err := e.Password.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldPassword.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Password.SqlFormatParam()
				o.sets[index][user_info.FieldPassword.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldStatus.Name.String():
				v, err := e.Status.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldStatus.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Status.SqlFormatParam()
				o.sets[index][user_info.FieldStatus.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldCreatedAt.Name.String():
				v, err := e.CreatedAt.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldCreatedAt.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.CreatedAt.SqlFormatParam()
				o.sets[index][user_info.FieldCreatedAt.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldLastAt.Name.String():
				v, err := e.LastAt.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldLastAt.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.LastAt.SqlFormatParam()
				o.sets[index][user_info.FieldLastAt.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			case user_info.FieldDeletedAt.Name.String():
				v, err := e.DeletedAt.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(user_info.FieldDeletedAt.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.DeletedAt.SqlFormatParam()
				o.sets[index][user_info.FieldDeletedAt.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predId.EQ(e.Id.Get()),
				}
				num++
			}
		}
		batchSize := *(entity.GetConfig().BatchSize)
		if (o.total+num)/batchSize > len(o.batchIndex) {
			o.batchIndex = append(o.batchIndex, len(o.predicates))
		} else {
			o.batchIndex[len(o.batchIndex)-1] = len(o.predicates)
		}
		o.total += num
	}
	return nil
}

func (o *UserEntityUpdate) mergeArgs(spec *entitysql.UpdateSpec) {
	for i, end := range o.batchIndex {
		var begin int
		if i == 0 {
			begin = 0
		} else {
			begin = o.batchIndex[i-1]
		}
		pred := []entitysql.PredicateFunc{}
		set := map[string][]entitysql.CaseSpec{}
		for _, ps := range o.predicates[begin:end] {
			pred = append(pred, ps...)
		}
		for _, ss := range o.sets[begin:end] {
			for k, v := range ss {
				set[k] = append(set[k], v)
			}
		}
		spec.Predicate = append(spec.Predicate, func(p *entitysql.Predicate) {
			for _, f := range pred {
				f(p)
			}
		})
		spec.Sets = append(spec.Sets, set)
	}
}
