// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"time"

	"git.zodileap.com/entity/account_v1/user_info"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/field"
)

// userInfo_Id is Id field
type userInfo_Id struct {
	field.StringStorage[string]
	config *userentityConfig
}

// newuserInfo_Id creates a new userInfo_Id
func newUserInfo_Id(c *userentityConfig) *userInfo_Id {
	t := &userInfo_Id{}
	t.config = c
	return t
}

// Set sets the value of Id field
func (t *userInfo_Id) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldId.Name.String())
	}
}

// Get gets the value of Id field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *userInfo_Id) Get() string {
	return *t.StringStorage.Get()
}

// userInfo_Name is Name field
type userInfo_Name struct {
	field.StringStorage[string]
	config *userentityConfig
}

// newuserInfo_Name creates a new userInfo_Name
func newUserInfo_Name(c *userentityConfig) *userInfo_Name {
	t := &userInfo_Name{}
	t.config = c
	return t
}

// Set sets the value of Name field
func (t *userInfo_Name) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldName.Name.String())
	}
}

// Get gets the value of Name field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *userInfo_Name) Get() string {
	return *t.StringStorage.Get()
}

// userInfo_Email is Email field
type userInfo_Email struct {
	field.StringStorage[string]
	config *userentityConfig
}

// newuserInfo_Email creates a new userInfo_Email
func newUserInfo_Email(c *userentityConfig) *userInfo_Email {
	t := &userInfo_Email{}
	t.config = c
	return t
}

// Set sets the value of Email field
func (t *userInfo_Email) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldEmail.Name.String())
	}
}

// Get gets the value of Email field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userInfo_Email) Get() *string {
	return t.StringStorage.Get()
}

// userInfo_Phone is Phone field
type userInfo_Phone struct {
	field.StringStorage[string]
	config *userentityConfig
}

// newuserInfo_Phone creates a new userInfo_Phone
func newUserInfo_Phone(c *userentityConfig) *userInfo_Phone {
	t := &userInfo_Phone{}
	t.config = c
	return t
}

// Set sets the value of Phone field
func (t *userInfo_Phone) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldPhone.Name.String())
	}
}

// Get gets the value of Phone field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userInfo_Phone) Get() *string {
	return t.StringStorage.Get()
}

// userInfo_Password is Password field
type userInfo_Password struct {
	field.StringStorage[string]
	config *userentityConfig
}

// newuserInfo_Password creates a new userInfo_Password
func newUserInfo_Password(c *userentityConfig) *userInfo_Password {
	t := &userInfo_Password{}
	t.config = c
	return t
}

// Set sets the value of Password field
func (t *userInfo_Password) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldPassword.Name.String())
	}
}

// Get gets the value of Password field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userInfo_Password) Get() *string {
	return t.StringStorage.Get()
}

// userInfo_Status is Status field
type userInfo_Status struct {
	field.IntStorage[int16]
	config *userentityConfig
}

// newuserInfo_Status creates a new userInfo_Status
func newUserInfo_Status(c *userentityConfig) *userInfo_Status {
	t := &userInfo_Status{}
	t.config = c
	return t
}

// Set sets the value of Status field
func (t *userInfo_Status) Set(v int16) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldStatus.Name.String())
	}
}

// Get gets the value of Status field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userInfo_Status) Get() *int16 {
	return t.IntStorage.Get()
}

// userInfo_CreatedAt is CreatedAt field
type userInfo_CreatedAt struct {
	field.TimestampStorage[time.Time]
	config *userentityConfig
}

// newuserInfo_CreatedAt creates a new userInfo_CreatedAt
func newUserInfo_CreatedAt(c *userentityConfig) *userInfo_CreatedAt {
	t := &userInfo_CreatedAt{}
	t.config = c
	return t
}

// Set sets the value of CreatedAt field
func (t *userInfo_CreatedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldCreatedAt.Name.String())
	}
}

// Get gets the value of CreatedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userInfo_CreatedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// userInfo_LastAt is LastAt field
type userInfo_LastAt struct {
	field.TimestampStorage[time.Time]
	config *userentityConfig
}

// newuserInfo_LastAt creates a new userInfo_LastAt
func newUserInfo_LastAt(c *userentityConfig) *userInfo_LastAt {
	t := &userInfo_LastAt{}
	t.config = c
	return t
}

// Set sets the value of LastAt field
func (t *userInfo_LastAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldLastAt.Name.String())
	}
}

// Get gets the value of LastAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userInfo_LastAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// userInfo_DeletedAt is DeletedAt field
type userInfo_DeletedAt struct {
	field.TimestampStorage[time.Time]
	config *userentityConfig
}

// newuserInfo_DeletedAt creates a new userInfo_DeletedAt
func newUserInfo_DeletedAt(c *userentityConfig) *userInfo_DeletedAt {
	t := &userInfo_DeletedAt{}
	t.config = c
	return t
}

// Set sets the value of DeletedAt field
func (t *userInfo_DeletedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.userentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(user_info.FieldDeletedAt.Name.String())
	}
}

// Get gets the value of DeletedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *userInfo_DeletedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}
