// Code generated by taurus_go/entity, DO NOT EDIT.

package account

import (
	"git.zodileap.com/entity/account_v1/internal"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

type rel interface {
	Desc() (entitysql.RelationDesc, []rel, internal.EntityConfig)
	reset()
}

type agententityRel interface {
	rel
}

type agentaccessentityRel interface {
	rel
}

type userentityRel interface {
	rel
}
