// Code generated by taurus_go/entity, DO NOT EDIT.

package model_task

import (
	"time"

	"github.com/zodileap/taurus_go/entity/entitysql"
)

type PredId struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredId) EQ(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldId.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredId) NEQ(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldId.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredId) GT(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldId.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredId) GTE(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldId.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredId) LT(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldId.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredId) LTE(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldId.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredId) In(ids ...int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		p.In(FieldId.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredId) NotIn(ids ...int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		p.NotIn(FieldId.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredId) Like(id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldId.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

type PredUserId struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredUserId) EQ(user_id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldUserId.Name.String(), p.Builder.FindAs(Entity), user_id)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredUserId) NEQ(user_id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldUserId.Name.String(), p.Builder.FindAs(Entity), user_id)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredUserId) GT(user_id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldUserId.Name.String(), p.Builder.FindAs(Entity), user_id)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredUserId) GTE(user_id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldUserId.Name.String(), p.Builder.FindAs(Entity), user_id)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredUserId) LT(user_id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldUserId.Name.String(), p.Builder.FindAs(Entity), user_id)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredUserId) LTE(user_id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldUserId.Name.String(), p.Builder.FindAs(Entity), user_id)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredUserId) In(user_ids ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(user_ids))
		for i := range v {
			v[i] = user_ids[i]
		}
		p.In(FieldUserId.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredUserId) NotIn(user_ids ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(user_ids))
		for i := range v {
			v[i] = user_ids[i]
		}
		p.NotIn(FieldUserId.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredUserId) Like(user_id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldUserId.Name.String(), p.Builder.FindAs(Entity), user_id)
	}
}

type PredPrompt struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredPrompt) EQ(prompt string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), prompt)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredPrompt) NEQ(prompt string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), prompt)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredPrompt) GT(prompt string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), prompt)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredPrompt) GTE(prompt string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), prompt)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredPrompt) LT(prompt string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), prompt)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredPrompt) LTE(prompt string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), prompt)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredPrompt) In(prompts ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(prompts))
		for i := range v {
			v[i] = prompts[i]
		}
		p.In(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredPrompt) NotIn(prompts ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(prompts))
		for i := range v {
			v[i] = prompts[i]
		}
		p.NotIn(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredPrompt) Like(prompt string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldPrompt.Name.String(), p.Builder.FindAs(Entity), prompt)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredPrompt) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldPrompt.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredPrompt) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldPrompt.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredStatus struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredStatus) EQ(status int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldStatus.Name.String(), p.Builder.FindAs(Entity), status)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredStatus) NEQ(status int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldStatus.Name.String(), p.Builder.FindAs(Entity), status)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredStatus) GT(status int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldStatus.Name.String(), p.Builder.FindAs(Entity), status)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredStatus) GTE(status int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldStatus.Name.String(), p.Builder.FindAs(Entity), status)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredStatus) LT(status int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldStatus.Name.String(), p.Builder.FindAs(Entity), status)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredStatus) LTE(status int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldStatus.Name.String(), p.Builder.FindAs(Entity), status)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredStatus) In(statuss ...int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(statuss))
		for i := range v {
			v[i] = statuss[i]
		}
		p.In(FieldStatus.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredStatus) NotIn(statuss ...int16) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(statuss))
		for i := range v {
			v[i] = statuss[i]
		}
		p.NotIn(FieldStatus.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredStatus) Like(status string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldStatus.Name.String(), p.Builder.FindAs(Entity), status)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredStatus) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldStatus.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredStatus) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldStatus.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredResultPath struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredResultPath) EQ(result_path string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), result_path)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredResultPath) NEQ(result_path string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), result_path)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredResultPath) GT(result_path string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), result_path)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredResultPath) GTE(result_path string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), result_path)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredResultPath) LT(result_path string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), result_path)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredResultPath) LTE(result_path string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), result_path)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredResultPath) In(result_paths ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(result_paths))
		for i := range v {
			v[i] = result_paths[i]
		}
		p.In(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredResultPath) NotIn(result_paths ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(result_paths))
		for i := range v {
			v[i] = result_paths[i]
		}
		p.NotIn(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredResultPath) Like(result_path string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldResultPath.Name.String(), p.Builder.FindAs(Entity), result_path)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredResultPath) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldResultPath.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredResultPath) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldResultPath.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredCreatedAt struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredCreatedAt) EQ(created_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), created_at)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredCreatedAt) NEQ(created_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), created_at)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredCreatedAt) GT(created_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), created_at)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredCreatedAt) GTE(created_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), created_at)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredCreatedAt) LT(created_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), created_at)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredCreatedAt) LTE(created_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), created_at)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredCreatedAt) In(created_ats ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(created_ats))
		for i := range v {
			v[i] = created_ats[i]
		}
		p.In(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredCreatedAt) NotIn(created_ats ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(created_ats))
		for i := range v {
			v[i] = created_ats[i]
		}
		p.NotIn(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredCreatedAt) Like(created_at string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity), created_at)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredCreatedAt) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredCreatedAt) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldCreatedAt.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredLastAt struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredLastAt) EQ(last_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), last_at)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredLastAt) NEQ(last_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), last_at)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredLastAt) GT(last_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), last_at)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredLastAt) GTE(last_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), last_at)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredLastAt) LT(last_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), last_at)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredLastAt) LTE(last_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), last_at)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredLastAt) In(last_ats ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(last_ats))
		for i := range v {
			v[i] = last_ats[i]
		}
		p.In(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredLastAt) NotIn(last_ats ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(last_ats))
		for i := range v {
			v[i] = last_ats[i]
		}
		p.NotIn(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredLastAt) Like(last_at string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldLastAt.Name.String(), p.Builder.FindAs(Entity), last_at)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredLastAt) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldLastAt.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredLastAt) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldLastAt.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredDeletedAt struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredDeletedAt) EQ(deleted_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), deleted_at)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredDeletedAt) NEQ(deleted_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), deleted_at)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredDeletedAt) GT(deleted_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), deleted_at)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredDeletedAt) GTE(deleted_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), deleted_at)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredDeletedAt) LT(deleted_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), deleted_at)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredDeletedAt) LTE(deleted_at time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), deleted_at)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredDeletedAt) In(deleted_ats ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(deleted_ats))
		for i := range v {
			v[i] = deleted_ats[i]
		}
		p.In(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredDeletedAt) NotIn(deleted_ats ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(deleted_ats))
		for i := range v {
			v[i] = deleted_ats[i]
		}
		p.NotIn(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredDeletedAt) Like(deleted_at string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity), deleted_at)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredDeletedAt) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredDeletedAt) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldDeletedAt.Name.String(), p.Builder.FindAs(Entity))
	}
}
