// Code generated by taurus_go/entity, DO NOT EDIT.

package agent_session

import "github.com/zodileap/taurus_go/entity/entitysql"

type OrderOption func(*entitysql.Order)

func ByPrimary(o *entitysql.Order) {
	(&ById{}).Apply(o)
}

type OrderTerm interface {
	Apply(*entitysql.Order)
}

type ById struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ById) Apply(o *entitysql.Order) {
	o.SetColumn(FieldId.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ById) Desc() *ById {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ById) Asc() *ById {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ById) NullsFirst() *ById {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ById) NullsLast() *ById {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByUserId struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByUserId) Apply(o *entitysql.Order) {
	o.SetColumn(FieldUserId.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByUserId) Desc() *ByUserId {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByUserId) Asc() *ByUserId {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByUserId) NullsFirst() *ByUserId {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByUserId) NullsLast() *ByUserId {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByAgentCode struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByAgentCode) Apply(o *entitysql.Order) {
	o.SetColumn(FieldAgentCode.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByAgentCode) Desc() *ByAgentCode {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByAgentCode) Asc() *ByAgentCode {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByAgentCode) NullsFirst() *ByAgentCode {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByAgentCode) NullsLast() *ByAgentCode {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByStatus struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByStatus) Apply(o *entitysql.Order) {
	o.SetColumn(FieldStatus.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByStatus) Desc() *ByStatus {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByStatus) Asc() *ByStatus {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByStatus) NullsFirst() *ByStatus {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByStatus) NullsLast() *ByStatus {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByCreatedAt struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByCreatedAt) Apply(o *entitysql.Order) {
	o.SetColumn(FieldCreatedAt.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByCreatedAt) Desc() *ByCreatedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByCreatedAt) Asc() *ByCreatedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByCreatedAt) NullsFirst() *ByCreatedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByCreatedAt) NullsLast() *ByCreatedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByLastAt struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByLastAt) Apply(o *entitysql.Order) {
	o.SetColumn(FieldLastAt.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByLastAt) Desc() *ByLastAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByLastAt) Asc() *ByLastAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByLastAt) NullsFirst() *ByLastAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByLastAt) NullsLast() *ByLastAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByDeletedAt struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByDeletedAt) Apply(o *entitysql.Order) {
	o.SetColumn(FieldDeletedAt.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByDeletedAt) Desc() *ByDeletedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByDeletedAt) Asc() *ByDeletedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByDeletedAt) NullsFirst() *ByDeletedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByDeletedAt) NullsLast() *ByDeletedAt {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}
