// Code generated by taurus_go/entity, DO NOT EDIT.

package billing

import (
	"context"
	"fmt"

	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/entitysql"

	"git.zodileap.com/entity/billing_v1/internal"
)

const BillingTag = "billing"

// Billing  is an struct of the database
type Billing struct {
	*internal.Dialect
	tracker entity.Tracker
	// OrderInfos 订单信息
	OrderInfos *orderinfoentityBuilder
	// OrderItems 订单项
	OrderItems *orderitementityBuilder
	// Subscriptions 订阅信息
	Subscriptions *subscriptionentityBuilder
}

type billingEntityFlag interface {
	isBillingEntity()
}

func (e *OrderInfoEntity) isBillingEntity()    {}
func (e *OrderItemEntity) isBillingEntity()    {}
func (e *SubscriptionEntity) isBillingEntity() {}

// NewBilling creates a new Billing instance.
func NewBilling() (*Billing, error) {
	dialect, err := internal.NewDialect(BillingTag)
	if err != nil {
		return nil, err
	}
	billing := &Billing{
		Dialect: dialect,
		tracker: &entity.Tracking{},
	}
	billing.init()
	return billing, nil
}

// Close closes the database.
func (d *Billing) Close() error {
	return d.Driver.Close()
}

// Save saves all changes to the database.
func (d *Billing) Save(ctx context.Context) error {
	tx, err := d.Dialect.MayTx(ctx)
	if err != nil {
		return err
	}
	if err := func() error {
		for _, m := range d.tracker.Mutators() {
			if err := m.Exec(ctx, tx); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return entitysql.Rollback(tx, err)
	}
	return tx.Commit()
}

// Remove will remove the entity from the database. The changes will be saved when Save is called.
func (d *Billing) Remove(e billingEntityFlag) error {
	switch e.(type) {
	case *OrderInfoEntity:
		d.OrderInfos.Remove(e.(*OrderInfoEntity))
	case *OrderItemEntity:
		d.OrderItems.Remove(e.(*OrderItemEntity))
	case *SubscriptionEntity:
		d.Subscriptions.Remove(e.(*SubscriptionEntity))
	default:
		return fmt.Errorf("database Billing does not support entity type %T", e)
	}
	return nil
}

func (d *Billing) init() {
	orderinfoentityConfig := newOrderInfoEntityConfig(d.Dialect)
	orderitementityConfig := newOrderItemEntityConfig(d.Dialect)
	subscriptionentityConfig := newSubscriptionEntityConfig(d.Dialect)

	d.OrderInfos = newOrderInfoEntityBuilder(orderinfoentityConfig, d.tracker)
	d.tracker.Add(d.OrderInfos)

	d.OrderItems = newOrderItemEntityBuilder(orderitementityConfig, d.tracker)
	d.tracker.Add(d.OrderItems)

	d.Subscriptions = newSubscriptionEntityBuilder(subscriptionentityConfig, d.tracker)
	d.tracker.Add(d.Subscriptions)
}
