// Code generated by taurus_go/entity, DO NOT EDIT.

package billing

import (
	"time"

	"git.zodileap.com/entity/billing_v1/order_item"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/field"
)

// orderItem_Id is Id field
type orderItem_Id struct {
	field.IntStorage[int64]
	config *orderitementityConfig
}

// neworderItem_Id creates a new orderItem_Id
func newOrderItem_Id(c *orderitementityConfig) *orderItem_Id {
	t := &orderItem_Id{}
	t.config = c
	return t
}

// Set sets the value of Id field
func (t *orderItem_Id) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldId.Name.String())
	}
}

// Get gets the value of Id field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *orderItem_Id) Get() int64 {
	return *t.IntStorage.Get()
}

// orderItem_OrderId is OrderId field
type orderItem_OrderId struct {
	field.IntStorage[int64]
	config *orderitementityConfig
}

// neworderItem_OrderId creates a new orderItem_OrderId
func newOrderItem_OrderId(c *orderitementityConfig) *orderItem_OrderId {
	t := &orderItem_OrderId{}
	t.config = c
	return t
}

// Set sets the value of OrderId field
func (t *orderItem_OrderId) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldOrderId.Name.String())
	}
}

// Get gets the value of OrderId field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *orderItem_OrderId) Get() int64 {
	return *t.IntStorage.Get()
}

// orderItem_AgentCode is AgentCode field
type orderItem_AgentCode struct {
	field.StringStorage[string]
	config *orderitementityConfig
}

// neworderItem_AgentCode creates a new orderItem_AgentCode
func newOrderItem_AgentCode(c *orderitementityConfig) *orderItem_AgentCode {
	t := &orderItem_AgentCode{}
	t.config = c
	return t
}

// Set sets the value of AgentCode field
func (t *orderItem_AgentCode) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldAgentCode.Name.String())
	}
}

// Get gets the value of AgentCode field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *orderItem_AgentCode) Get() string {
	return *t.StringStorage.Get()
}

// orderItem_Quantity is Quantity field
type orderItem_Quantity struct {
	field.IntStorage[int32]
	config *orderitementityConfig
}

// neworderItem_Quantity creates a new orderItem_Quantity
func newOrderItem_Quantity(c *orderitementityConfig) *orderItem_Quantity {
	t := &orderItem_Quantity{}
	t.config = c
	return t
}

// Set sets the value of Quantity field
func (t *orderItem_Quantity) Set(v int32) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldQuantity.Name.String())
	}
}

// Get gets the value of Quantity field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *orderItem_Quantity) Get() *int32 {
	return t.IntStorage.Get()
}

// orderItem_ItemAmount is ItemAmount field
type orderItem_ItemAmount struct {
	field.IntStorage[int64]
	config *orderitementityConfig
}

// neworderItem_ItemAmount creates a new orderItem_ItemAmount
func newOrderItem_ItemAmount(c *orderitementityConfig) *orderItem_ItemAmount {
	t := &orderItem_ItemAmount{}
	t.config = c
	return t
}

// Set sets the value of ItemAmount field
func (t *orderItem_ItemAmount) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldItemAmount.Name.String())
	}
}

// Get gets the value of ItemAmount field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *orderItem_ItemAmount) Get() *int64 {
	return t.IntStorage.Get()
}

// orderItem_CreatedAt is CreatedAt field
type orderItem_CreatedAt struct {
	field.TimestampStorage[time.Time]
	config *orderitementityConfig
}

// neworderItem_CreatedAt creates a new orderItem_CreatedAt
func newOrderItem_CreatedAt(c *orderitementityConfig) *orderItem_CreatedAt {
	t := &orderItem_CreatedAt{}
	t.config = c
	return t
}

// Set sets the value of CreatedAt field
func (t *orderItem_CreatedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldCreatedAt.Name.String())
	}
}

// Get gets the value of CreatedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *orderItem_CreatedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// orderItem_LastAt is LastAt field
type orderItem_LastAt struct {
	field.TimestampStorage[time.Time]
	config *orderitementityConfig
}

// neworderItem_LastAt creates a new orderItem_LastAt
func newOrderItem_LastAt(c *orderitementityConfig) *orderItem_LastAt {
	t := &orderItem_LastAt{}
	t.config = c
	return t
}

// Set sets the value of LastAt field
func (t *orderItem_LastAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldLastAt.Name.String())
	}
}

// Get gets the value of LastAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *orderItem_LastAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// orderItem_DeletedAt is DeletedAt field
type orderItem_DeletedAt struct {
	field.TimestampStorage[time.Time]
	config *orderitementityConfig
}

// neworderItem_DeletedAt creates a new orderItem_DeletedAt
func newOrderItem_DeletedAt(c *orderitementityConfig) *orderItem_DeletedAt {
	t := &orderItem_DeletedAt{}
	t.config = c
	return t
}

// Set sets the value of DeletedAt field
func (t *orderItem_DeletedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.orderitementityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(order_item.FieldDeletedAt.Name.String())
	}
}

// Get gets the value of DeletedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *orderItem_DeletedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}
