// Code generated by taurus_go/entity, DO NOT EDIT.

package enterprise_role

import (
	"github.com/zodileap/taurus_go/entity/entitysql"
)

const (
	Entity = "enterprise_role"
)

var (
	FieldId = entitysql.Field{
		Name:     "id",
		Primary:  1,
		Default:  true,
		Required: true,
	}
	FieldEnterpriseId = entitysql.Field{
		Name:     "enterprise_id",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldCode = entitysql.Field{
		Name:     "code",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldName = entitysql.Field{
		Name:     "name",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldStatus = entitysql.Field{
		Name:     "status",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldRemark = entitysql.Field{
		Name:     "remark",
		Primary:  0,
		Default:  false,
		Required: false,
	}
	FieldCreatedAt = entitysql.Field{
		Name:     "created_at",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldLastAt = entitysql.Field{
		Name:     "last_at",
		Primary:  0,
		Default:  true,
		Required: false,
	}
	FieldDeletedAt = entitysql.Field{
		Name:     "deleted_at",
		Primary:  0,
		Default:  true,
		Required: false,
	}
)

var (
	Columns = []entitysql.FieldName{
		FieldId.Name,
		FieldEnterpriseId.Name,
		FieldCode.Name,
		FieldName.Name,
		FieldStatus.Name,
		FieldRemark.Name,
		FieldCreatedAt.Name,
		FieldLastAt.Name,
		FieldDeletedAt.Name,
	}
)
