// Code generated by taurus_go/entity, DO NOT EDIT.

package agentcode

import (
	"context"

	entity "git.zodileap.com/entity/agent_code_v1"
	tentity "github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/tlog"

	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
)

const dbName = "agent_code"
const componentAssetEntityName = "component_asset"
const frameworkAssetEntityName = "framework_asset"
const moduleAssetEntityName = "module_asset"

type AgentCodeDB struct {
	*entity.AgentCode
}

// 初始化agent_code数据库
func InitAgentCodeDB(sqlConsole bool) (*AgentCodeDB, error) {
	config := tentity.Config{
		SqlConsole: &sqlConsole,
	}
	tentity.SetConfig(config)

	db, err := entity.NewAgentCode()
	if err != nil {
		return nil, zerr.Err_1004002001.New().Sprintf(err.Error())
	}
	return &AgentCodeDB{db}, nil
}

// 保存改变到数据库。
func (db *AgentCodeDB) Save(ctx context.Context) error {
	err := db.AgentCode.Save(ctx)
	if err == context.DeadlineExceeded {
		// 处理超时错误
		tlog.Print("超时")
	}
	if err != nil {
		return AgentCodeSaveErr(err)
	}
	return nil
}

// 关闭数据库。每次使用完数据库后都需要调用该方法关闭数据库。
func (db *AgentCodeDB) Close() {
	db.AgentCode.Close()
}

// DBOpCfg 数据库操作的相关参数
type DBOpCfg struct {
	Context    *context.Context // 数据库操作的上下文，可以设置超时时间等。
	KeepOpen   bool             // 是否保持数据库连接，如果为 true，则数据库连接不会在函数执行后关闭。
	Instance   *AgentCodeDB     // 数据库连接实例。
	SqlConsole bool             // 是否打印SQL语句。
}

func NewDBOpCfg() *DBOpCfg {
	return &DBOpCfg{}
}

type ComponentAssetDTO struct {
	ComponentAsset *ComponentAssetEntity
	DB             *AgentCodeDB
}

func NewComponentAssetDTO(e *entity.ComponentAssetEntity, db *AgentCodeDB) *ComponentAssetDTO {
	var instance *ComponentAssetEntity
	if e != nil {
		instance = newComponentAssetEntity(e)
	}
	return &ComponentAssetDTO{
		ComponentAsset: instance,
		DB:             db,
	}
}

type ComponentAssetsDTO struct {
	ComponentAssets []*ComponentAssetEntity
	DB              *AgentCodeDB
}

func NewComponentAssetsDTO(es []*entity.ComponentAssetEntity, db *AgentCodeDB) *ComponentAssetsDTO {
	instance := make([]*ComponentAssetEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newComponentAssetEntity(e))
	}
	return &ComponentAssetsDTO{
		ComponentAssets: instance,
		DB:              db,
	}
}

type FrameworkAssetDTO struct {
	FrameworkAsset *FrameworkAssetEntity
	DB             *AgentCodeDB
}

func NewFrameworkAssetDTO(e *entity.FrameworkAssetEntity, db *AgentCodeDB) *FrameworkAssetDTO {
	var instance *FrameworkAssetEntity
	if e != nil {
		instance = newFrameworkAssetEntity(e)
	}
	return &FrameworkAssetDTO{
		FrameworkAsset: instance,
		DB:             db,
	}
}

type FrameworkAssetsDTO struct {
	FrameworkAssets []*FrameworkAssetEntity
	DB              *AgentCodeDB
}

func NewFrameworkAssetsDTO(es []*entity.FrameworkAssetEntity, db *AgentCodeDB) *FrameworkAssetsDTO {
	instance := make([]*FrameworkAssetEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newFrameworkAssetEntity(e))
	}
	return &FrameworkAssetsDTO{
		FrameworkAssets: instance,
		DB:              db,
	}
}

type ModuleAssetDTO struct {
	ModuleAsset *ModuleAssetEntity
	DB          *AgentCodeDB
}

func NewModuleAssetDTO(e *entity.ModuleAssetEntity, db *AgentCodeDB) *ModuleAssetDTO {
	var instance *ModuleAssetEntity
	if e != nil {
		instance = newModuleAssetEntity(e)
	}
	return &ModuleAssetDTO{
		ModuleAsset: instance,
		DB:          db,
	}
}

type ModuleAssetsDTO struct {
	ModuleAssets []*ModuleAssetEntity
	DB           *AgentCodeDB
}

func NewModuleAssetsDTO(es []*entity.ModuleAssetEntity, db *AgentCodeDB) *ModuleAssetsDTO {
	instance := make([]*ModuleAssetEntity, 0, len(es))
	for _, e := range es {
		instance = append(instance, newModuleAssetEntity(e))
	}
	return &ModuleAssetsDTO{
		ModuleAssets: instance,
		DB:           db,
	}
}
