// Code generated by taurus_go/entity, DO NOT EDIT.

package agentcode

import (
	"context"

	entity "git.zodileap.com/entity/agent_code_v1"
	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
	zspecs "git.zodileap.com/taurus/zodileap_go_zspecs"
)

// ComponentAsset 用于操作component_asset表的仓储实现
type ComponentAsset struct {
}

// NewComponentAsset 创建新的ComponentAssetRepository实例
func NewComponentAsset() *ComponentAsset {
	return &ComponentAsset{}
}

// InitDB 初始化数据库
func (r *ComponentAsset) InitDB(config *DBOpCfg) error {
	if err := WithInitDB(config); err != nil {
		return zerr.Must(err)
	}
	return nil
}

// Create 创建一条记录
func (r *ComponentAsset) Create(config *DBOpCfg, param ComponentAssetCreate) (*ComponentAssetDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ComponentAssetDTO, error) {
		if err := r.createRemove(param); err != nil {
			return nil, zerr.Must(err)
		}

		e, err := r.createComponentAsset(config, db, param)
		if err != nil {
			return nil, zerr.Must(err)
		}
		if err = db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createComponentAssetDTO(config.KeepOpen, e, db)
	})
}

// CreateList 创建多条记录
func (r *ComponentAsset) CreateList(config *DBOpCfg, params []ComponentAssetCreate) (*ComponentAssetsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ComponentAssetsDTO, error) {
		var es []*entity.ComponentAssetEntity
		for _, param := range params {
			if err := r.createRemove(param); err != nil {
				return nil, zerr.Must(err)
			}
			e, err := r.createComponentAsset(config, db, param)
			if err != nil {
				return nil, zerr.Must(err)
			}
			es = append(es, e)
		}
		if err := db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createComponentAssetsDTO(config.KeepOpen, es, db)
	})
}

// Get 获取单条记录
func (r *ComponentAsset) Get(config *DBOpCfg, query ComponentAssetQuery, includeDelete bool) (*ComponentAssetDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ComponentAssetDTO, error) {
		q := db.ComponentAssets.Where()
		if _, err := r.queryComponentAsset(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		e, err := q.Single(nctx)
		if err != nil {
			return nil, AgentCodeComponentAssetErr.Query(err)
		}
		return r.createComponentAssetDTO(config.KeepOpen, e, db)
	})
}

// GetList 获取多条记录
func (r *ComponentAsset) GetList(config *DBOpCfg, query ComponentAssetQuery, includeDelete bool) (*ComponentAssetsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ComponentAssetsDTO, error) {
		q := db.ComponentAssets.Where()
		if _, err := r.queryComponentAsset(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		es, err := q.ToList(nctx)
		if err != nil {
			return nil, AgentCodeComponentAssetErr.Query(err)
		}
		return r.createComponentAssetsDTO(config.KeepOpen, es, db)
	})
}

// Update 更新记录
func (r *ComponentAsset) Update(config *DBOpCfg, e *ComponentAssetEntity, params ComponentAssetUpdate) error {
	if err := params.Validate(); err != nil {
		return zerr.Must(err)
	}
	if params.OwnerId != nil {
		e.SetOwnerId(*params.OwnerId)
	}
	if params.Name != nil {
		e.SetName(*params.Name)
	}
	if params.Path != nil {
		e.SetPath(*params.Path)
	}
	if params.Version != nil {
		e.SetVersion(*params.Version)
	}
	if params.Status != nil {
		e.SetStatus(*params.Status)
	}
	if params.Remark != nil {
		e.SetRemark(*params.Remark)
	}
	return nil
}

// Delete 逻辑删除 - 设置 DeletedAt 字段
func (r *ComponentAsset) Delete(config *DBOpCfg, e *ComponentAssetEntity) error {
	e.SetDeletedAt(zspecs.CreateDeletedAt())
	return nil
}

// Remove 物理删除 - 从数据库真实删除记录
func (r *ComponentAsset) Remove(config *DBOpCfg, e *ComponentAssetEntity) error {
	return config.Instance.Remove(e.entity)
}

// Save 保存更改 - 用于在获取记录并修改后执行数据库保存操作
func (r *ComponentAsset) Save(config *DBOpCfg) error {
	return WithSave(config, "component_asset")
}

// remove 在新建前删除已经被标记为删除的记录
func (r *ComponentAsset) createRemove(param ComponentAssetCreate) error {
	return nil
}

// FrameworkAsset 用于操作framework_asset表的仓储实现
type FrameworkAsset struct {
}

// NewFrameworkAsset 创建新的FrameworkAssetRepository实例
func NewFrameworkAsset() *FrameworkAsset {
	return &FrameworkAsset{}
}

// InitDB 初始化数据库
func (r *FrameworkAsset) InitDB(config *DBOpCfg) error {
	if err := WithInitDB(config); err != nil {
		return zerr.Must(err)
	}
	return nil
}

// Create 创建一条记录
func (r *FrameworkAsset) Create(config *DBOpCfg, param FrameworkAssetCreate) (*FrameworkAssetDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*FrameworkAssetDTO, error) {
		if err := r.createRemove(param); err != nil {
			return nil, zerr.Must(err)
		}

		e, err := r.createFrameworkAsset(config, db, param)
		if err != nil {
			return nil, zerr.Must(err)
		}
		if err = db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createFrameworkAssetDTO(config.KeepOpen, e, db)
	})
}

// CreateList 创建多条记录
func (r *FrameworkAsset) CreateList(config *DBOpCfg, params []FrameworkAssetCreate) (*FrameworkAssetsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*FrameworkAssetsDTO, error) {
		var es []*entity.FrameworkAssetEntity
		for _, param := range params {
			if err := r.createRemove(param); err != nil {
				return nil, zerr.Must(err)
			}
			e, err := r.createFrameworkAsset(config, db, param)
			if err != nil {
				return nil, zerr.Must(err)
			}
			es = append(es, e)
		}
		if err := db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createFrameworkAssetsDTO(config.KeepOpen, es, db)
	})
}

// Get 获取单条记录
func (r *FrameworkAsset) Get(config *DBOpCfg, query FrameworkAssetQuery, includeDelete bool) (*FrameworkAssetDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*FrameworkAssetDTO, error) {
		q := db.FrameworkAssets.Where()
		if _, err := r.queryFrameworkAsset(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		e, err := q.Single(nctx)
		if err != nil {
			return nil, AgentCodeFrameworkAssetErr.Query(err)
		}
		return r.createFrameworkAssetDTO(config.KeepOpen, e, db)
	})
}

// GetList 获取多条记录
func (r *FrameworkAsset) GetList(config *DBOpCfg, query FrameworkAssetQuery, includeDelete bool) (*FrameworkAssetsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*FrameworkAssetsDTO, error) {
		q := db.FrameworkAssets.Where()
		if _, err := r.queryFrameworkAsset(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		es, err := q.ToList(nctx)
		if err != nil {
			return nil, AgentCodeFrameworkAssetErr.Query(err)
		}
		return r.createFrameworkAssetsDTO(config.KeepOpen, es, db)
	})
}

// Update 更新记录
func (r *FrameworkAsset) Update(config *DBOpCfg, e *FrameworkAssetEntity, params FrameworkAssetUpdate) error {
	if err := params.Validate(); err != nil {
		return zerr.Must(err)
	}
	if params.OwnerId != nil {
		e.SetOwnerId(*params.OwnerId)
	}
	if params.Name != nil {
		e.SetName(*params.Name)
	}
	if params.GitUrl != nil {
		e.SetGitUrl(*params.GitUrl)
	}
	if params.Version != nil {
		e.SetVersion(*params.Version)
	}
	if params.Status != nil {
		e.SetStatus(*params.Status)
	}
	if params.Remark != nil {
		e.SetRemark(*params.Remark)
	}
	return nil
}

// Delete 逻辑删除 - 设置 DeletedAt 字段
func (r *FrameworkAsset) Delete(config *DBOpCfg, e *FrameworkAssetEntity) error {
	e.SetDeletedAt(zspecs.CreateDeletedAt())
	return nil
}

// Remove 物理删除 - 从数据库真实删除记录
func (r *FrameworkAsset) Remove(config *DBOpCfg, e *FrameworkAssetEntity) error {
	return config.Instance.Remove(e.entity)
}

// Save 保存更改 - 用于在获取记录并修改后执行数据库保存操作
func (r *FrameworkAsset) Save(config *DBOpCfg) error {
	return WithSave(config, "framework_asset")
}

// remove 在新建前删除已经被标记为删除的记录
func (r *FrameworkAsset) createRemove(param FrameworkAssetCreate) error {
	return nil
}

// ModuleAsset 用于操作module_asset表的仓储实现
type ModuleAsset struct {
}

// NewModuleAsset 创建新的ModuleAssetRepository实例
func NewModuleAsset() *ModuleAsset {
	return &ModuleAsset{}
}

// InitDB 初始化数据库
func (r *ModuleAsset) InitDB(config *DBOpCfg) error {
	if err := WithInitDB(config); err != nil {
		return zerr.Must(err)
	}
	return nil
}

// Create 创建一条记录
func (r *ModuleAsset) Create(config *DBOpCfg, param ModuleAssetCreate) (*ModuleAssetDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ModuleAssetDTO, error) {
		if err := r.createRemove(param); err != nil {
			return nil, zerr.Must(err)
		}

		e, err := r.createModuleAsset(config, db, param)
		if err != nil {
			return nil, zerr.Must(err)
		}
		if err = db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createModuleAssetDTO(config.KeepOpen, e, db)
	})
}

// CreateList 创建多条记录
func (r *ModuleAsset) CreateList(config *DBOpCfg, params []ModuleAssetCreate) (*ModuleAssetsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ModuleAssetsDTO, error) {
		var es []*entity.ModuleAssetEntity
		for _, param := range params {
			if err := r.createRemove(param); err != nil {
				return nil, zerr.Must(err)
			}
			e, err := r.createModuleAsset(config, db, param)
			if err != nil {
				return nil, zerr.Must(err)
			}
			es = append(es, e)
		}
		if err := db.Save(nctx); err != nil {
			return nil, zerr.Must(err)
		}
		return r.createModuleAssetsDTO(config.KeepOpen, es, db)
	})
}

// Get 获取单条记录
func (r *ModuleAsset) Get(config *DBOpCfg, query ModuleAssetQuery, includeDelete bool) (*ModuleAssetDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ModuleAssetDTO, error) {
		q := db.ModuleAssets.Where()
		if _, err := r.queryModuleAsset(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		e, err := q.Single(nctx)
		if err != nil {
			return nil, AgentCodeModuleAssetErr.Query(err)
		}
		return r.createModuleAssetDTO(config.KeepOpen, e, db)
	})
}

// GetList 获取多条记录
func (r *ModuleAsset) GetList(config *DBOpCfg, query ModuleAssetQuery, includeDelete bool) (*ModuleAssetsDTO, error) {
	return WithDB(config, func(nctx context.Context, db *AgentCodeDB) (*ModuleAssetsDTO, error) {
		q := db.ModuleAssets.Where()
		if _, err := r.queryModuleAsset(db, q, query, includeDelete); err != nil {
			return nil, zerr.Must(err)
		}
		es, err := q.ToList(nctx)
		if err != nil {
			return nil, AgentCodeModuleAssetErr.Query(err)
		}
		return r.createModuleAssetsDTO(config.KeepOpen, es, db)
	})
}

// Update 更新记录
func (r *ModuleAsset) Update(config *DBOpCfg, e *ModuleAssetEntity, params ModuleAssetUpdate) error {
	if err := params.Validate(); err != nil {
		return zerr.Must(err)
	}
	if params.OwnerId != nil {
		e.SetOwnerId(*params.OwnerId)
	}
	if params.Name != nil {
		e.SetName(*params.Name)
	}
	if params.Path != nil {
		e.SetPath(*params.Path)
	}
	if params.Version != nil {
		e.SetVersion(*params.Version)
	}
	if params.Status != nil {
		e.SetStatus(*params.Status)
	}
	if params.Remark != nil {
		e.SetRemark(*params.Remark)
	}
	return nil
}

// Delete 逻辑删除 - 设置 DeletedAt 字段
func (r *ModuleAsset) Delete(config *DBOpCfg, e *ModuleAssetEntity) error {
	e.SetDeletedAt(zspecs.CreateDeletedAt())
	return nil
}

// Remove 物理删除 - 从数据库真实删除记录
func (r *ModuleAsset) Remove(config *DBOpCfg, e *ModuleAssetEntity) error {
	return config.Instance.Remove(e.entity)
}

// Save 保存更改 - 用于在获取记录并修改后执行数据库保存操作
func (r *ModuleAsset) Save(config *DBOpCfg) error {
	return WithSave(config, "module_asset")
}

// remove 在新建前删除已经被标记为删除的记录
func (r *ModuleAsset) createRemove(param ModuleAssetCreate) error {
	return nil
}
