// Code generated by taurus_go/entity, DO NOT EDIT.

package runtime

import (
	"fmt"
	"time"

	"git.zodileap.com/entity/runtime_v1/agent_session"
	"git.zodileap.com/entity/runtime_v1/internal"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// 智能体会话
type AgentSessionEntity struct {
	internal.Entity `json:"-"`
	config          *agentsessionentityConfig
	Id              *agentSession_Id        `json:"id"`                   // Id 主键Id
	UserId          *agentSession_UserId    `json:"user_id"`              // UserId 用户Id
	AgentCode       *agentSession_AgentCode `json:"agent_code"`           // AgentCode 智能体编码
	Status          *agentSession_Status    `json:"status"`               // Status 状态
	CreatedAt       *agentSession_CreatedAt `json:"created_at"`           // CreatedAt 创建数据时间
	LastAt          *agentSession_LastAt    `json:"last_at"`              // LastAt 更新数据时间
	DeletedAt       *agentSession_DeletedAt `json:"deleted_at,omitempty"` // DeletedAt 删除数据时间（逻辑删除）
}

// agentsessionentityConfig holds the configuration for the AgentSessionEntity.
type agentsessionentityConfig struct {
	internal.EntityConfig
	*internal.Dialect
	*entity.Mutation
	*agentsessionentityMutations
	name string
}

func newAgentSessionEntityConfig(c *internal.Dialect) *agentsessionentityConfig {
	return &agentsessionentityConfig{
		Dialect:                     c,
		agentsessionentityMutations: newAgentSessionEntityMutations(),
		name:                        "agent_session",
	}
}

// New creates a new AgentSessionEntity, but does not add tracking.
func (c *agentsessionentityConfig) New() internal.Entity {
	b := entity.NewMutation(entity.Detached)
	e := &AgentSessionEntity{
		config: &agentsessionentityConfig{
			Mutation:                    b,
			Dialect:                     c.Dialect,
			agentsessionentityMutations: c.agentsessionentityMutations,
		},
	}
	e.setState(entity.Detached)
	e.Id = newAgentSession_Id(e.config)
	e.UserId = newAgentSession_UserId(e.config)
	e.AgentCode = newAgentSession_AgentCode(e.config)
	e.Status = newAgentSession_Status(e.config)
	e.CreatedAt = newAgentSession_CreatedAt(e.config)
	e.LastAt = newAgentSession_LastAt(e.config)
	e.DeletedAt = newAgentSession_DeletedAt(e.config)
	return e
}

func (c *agentsessionentityConfig) Desc() internal.EntityConfigDesc {
	return internal.EntityConfigDesc{
		Name: c.name,
	}
}

// String implements the fmt.Stringer interface.
func (e *AgentSessionEntity) String() string {
	return fmt.Sprintf("{ Id: %v, UserId: %v, AgentCode: %v, Status: %v, CreatedAt: %v, LastAt: %v, DeletedAt: %v}",
		e.Id,
		e.UserId,
		e.AgentCode,
		e.Status,
		e.CreatedAt,
		e.LastAt,
		e.DeletedAt,
	)
}

// State returns the state of the AgentSessionEntity.
func (e *AgentSessionEntity) State() entity.EntityState {
	return e.config.State()
}

// remove removes the AgentSessionEntity from the database.
func (e *AgentSessionEntity) remove() error {
	return e.setState(entity.Deleted)
}

// create creates a new AgentSessionEntity and adds tracking.
func (e *AgentSessionEntity) create(user_id string, agent_code string, options ...func(*AgentSessionEntity)) (*AgentSessionEntity, error) {
	e.setState(entity.Added)
	e.UserId.Set(user_id)
	e.AgentCode.Set(agent_code)
	for _, option := range options {
		option(e)
	}
	return e, nil
}

// setUnchanged sets the state of the AgentSessionEntity to unchanged.
func (e *AgentSessionEntity) setUnchanged() error {
	return e.setState(entity.Unchanged)
}

// setState sets the state of the AgentSessionEntity.
func (e *AgentSessionEntity) setState(state entity.EntityState) error {
	return e.config.agentsessionentityMutations.SetEntityState(e, state)
}

// scan scans the database for the AgentSessionEntity.
func (e *AgentSessionEntity) scan(fields []entitysql.ScannerField) []any {
	if len(fields) == 0 {
		args := make([]any, len(agent_session.Columns))
		for i, c := range agent_session.Columns {
			switch c.String() {
			case agent_session.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case agent_session.FieldUserId.Name.String():
				v := e.UserId
				v.Set(*new(string))
				args[i] = v
			case agent_session.FieldAgentCode.Name.String():
				v := e.AgentCode
				v.Set(*new(string))
				args[i] = v
			case agent_session.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case agent_session.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent_session.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent_session.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	} else {
		args := make([]any, len(fields))
		for i := range fields {
			switch fields[i].String() {
			case agent_session.FieldId.Name.String():
				v := e.Id
				v.Set(*new(int64))
				args[i] = v
			case agent_session.FieldUserId.Name.String():
				v := e.UserId
				v.Set(*new(string))
				args[i] = v
			case agent_session.FieldAgentCode.Name.String():
				v := e.AgentCode
				v.Set(*new(string))
				args[i] = v
			case agent_session.FieldStatus.Name.String():
				v := e.Status
				v.Set(*new(int16))
				args[i] = v
			case agent_session.FieldCreatedAt.Name.String():
				v := e.CreatedAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent_session.FieldLastAt.Name.String():
				v := e.LastAt
				v.Set(*new(time.Time))
				args[i] = v
			case agent_session.FieldDeletedAt.Name.String():
				v := e.DeletedAt
				v.Set(*new(time.Time))
				args[i] = v
			}
		}
		return args
	}
}

func (e *AgentSessionEntity) createRel(buidler *entitysql.ScannerBuilder, scanner *internal.QueryScanner) {
	switch scanner.Config.Desc().Name {
	}
}

func mergeAgentSessionEntity(es []*AgentSessionEntity, e *AgentSessionEntity) []*AgentSessionEntity {
	if e == nil {
		return es
	}
	if len(es) == 0 {
		es = append(es, e)
	} else {
		v := es[len(es)-1]

		if v.Id.Get() == e.Id.Get() {
		} else {
			es = append(es, e)
		}
	}
	return es
}
