// Code generated by taurus_go/entity, DO NOT EDIT.

package runtime

import (
	"time"

	"git.zodileap.com/entity/runtime_v1/preview_endpoint"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/field"
)

// previewEndpoint_Id is Id field
type previewEndpoint_Id struct {
	field.IntStorage[int64]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_Id creates a new previewEndpoint_Id
func newPreviewEndpoint_Id(c *previewendpointentityConfig) *previewEndpoint_Id {
	t := &previewEndpoint_Id{}
	t.config = c
	return t
}

// Set sets the value of Id field
func (t *previewEndpoint_Id) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldId.Name.String())
	}
}

// Get gets the value of Id field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *previewEndpoint_Id) Get() int64 {
	return *t.IntStorage.Get()
}

// previewEndpoint_SandboxId is SandboxId field
type previewEndpoint_SandboxId struct {
	field.IntStorage[int64]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_SandboxId creates a new previewEndpoint_SandboxId
func newPreviewEndpoint_SandboxId(c *previewendpointentityConfig) *previewEndpoint_SandboxId {
	t := &previewEndpoint_SandboxId{}
	t.config = c
	return t
}

// Set sets the value of SandboxId field
func (t *previewEndpoint_SandboxId) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldSandboxId.Name.String())
	}
}

// Get gets the value of SandboxId field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *previewEndpoint_SandboxId) Get() int64 {
	return *t.IntStorage.Get()
}

// previewEndpoint_Url is Url field
type previewEndpoint_Url struct {
	field.StringStorage[string]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_Url creates a new previewEndpoint_Url
func newPreviewEndpoint_Url(c *previewendpointentityConfig) *previewEndpoint_Url {
	t := &previewEndpoint_Url{}
	t.config = c
	return t
}

// Set sets the value of Url field
func (t *previewEndpoint_Url) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldUrl.Name.String())
	}
}

// Get gets the value of Url field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *previewEndpoint_Url) Get() string {
	return *t.StringStorage.Get()
}

// previewEndpoint_Status is Status field
type previewEndpoint_Status struct {
	field.IntStorage[int16]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_Status creates a new previewEndpoint_Status
func newPreviewEndpoint_Status(c *previewendpointentityConfig) *previewEndpoint_Status {
	t := &previewEndpoint_Status{}
	t.config = c
	return t
}

// Set sets the value of Status field
func (t *previewEndpoint_Status) Set(v int16) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldStatus.Name.String())
	}
}

// Get gets the value of Status field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *previewEndpoint_Status) Get() *int16 {
	return t.IntStorage.Get()
}

// previewEndpoint_Expiration is Expiration field
type previewEndpoint_Expiration struct {
	field.IntStorage[int32]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_Expiration creates a new previewEndpoint_Expiration
func newPreviewEndpoint_Expiration(c *previewendpointentityConfig) *previewEndpoint_Expiration {
	t := &previewEndpoint_Expiration{}
	t.config = c
	return t
}

// Set sets the value of Expiration field
func (t *previewEndpoint_Expiration) Set(v int32) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldExpiration.Name.String())
	}
}

// Get gets the value of Expiration field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *previewEndpoint_Expiration) Get() *int32 {
	return t.IntStorage.Get()
}

// previewEndpoint_CreatedAt is CreatedAt field
type previewEndpoint_CreatedAt struct {
	field.TimestampStorage[time.Time]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_CreatedAt creates a new previewEndpoint_CreatedAt
func newPreviewEndpoint_CreatedAt(c *previewendpointentityConfig) *previewEndpoint_CreatedAt {
	t := &previewEndpoint_CreatedAt{}
	t.config = c
	return t
}

// Set sets the value of CreatedAt field
func (t *previewEndpoint_CreatedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldCreatedAt.Name.String())
	}
}

// Get gets the value of CreatedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *previewEndpoint_CreatedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// previewEndpoint_LastAt is LastAt field
type previewEndpoint_LastAt struct {
	field.TimestampStorage[time.Time]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_LastAt creates a new previewEndpoint_LastAt
func newPreviewEndpoint_LastAt(c *previewendpointentityConfig) *previewEndpoint_LastAt {
	t := &previewEndpoint_LastAt{}
	t.config = c
	return t
}

// Set sets the value of LastAt field
func (t *previewEndpoint_LastAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldLastAt.Name.String())
	}
}

// Get gets the value of LastAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *previewEndpoint_LastAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// previewEndpoint_DeletedAt is DeletedAt field
type previewEndpoint_DeletedAt struct {
	field.TimestampStorage[time.Time]
	config *previewendpointentityConfig
}

// newpreviewEndpoint_DeletedAt creates a new previewEndpoint_DeletedAt
func newPreviewEndpoint_DeletedAt(c *previewendpointentityConfig) *previewEndpoint_DeletedAt {
	t := &previewEndpoint_DeletedAt{}
	t.config = c
	return t
}

// Set sets the value of DeletedAt field
func (t *previewEndpoint_DeletedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.previewendpointentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(preview_endpoint.FieldDeletedAt.Name.String())
	}
}

// Get gets the value of DeletedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *previewEndpoint_DeletedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}
