// Code generated by taurus_go/entity, DO NOT EDIT.

package runtime

import (
	"time"

	"git.zodileap.com/entity/runtime_v1/sandbox_instance"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/field"
)

// sandboxInstance_Id is Id field
type sandboxInstance_Id struct {
	field.IntStorage[int64]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_Id creates a new sandboxInstance_Id
func newSandboxInstance_Id(c *sandboxinstanceentityConfig) *sandboxInstance_Id {
	t := &sandboxInstance_Id{}
	t.config = c
	return t
}

// Set sets the value of Id field
func (t *sandboxInstance_Id) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldId.Name.String())
	}
}

// Get gets the value of Id field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *sandboxInstance_Id) Get() int64 {
	return *t.IntStorage.Get()
}

// sandboxInstance_SessionId is SessionId field
type sandboxInstance_SessionId struct {
	field.IntStorage[int64]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_SessionId creates a new sandboxInstance_SessionId
func newSandboxInstance_SessionId(c *sandboxinstanceentityConfig) *sandboxInstance_SessionId {
	t := &sandboxInstance_SessionId{}
	t.config = c
	return t
}

// Set sets the value of SessionId field
func (t *sandboxInstance_SessionId) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldSessionId.Name.String())
	}
}

// Get gets the value of SessionId field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.
func (t *sandboxInstance_SessionId) Get() int64 {
	return *t.IntStorage.Get()
}

// sandboxInstance_ContainerId is ContainerId field
type sandboxInstance_ContainerId struct {
	field.StringStorage[string]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_ContainerId creates a new sandboxInstance_ContainerId
func newSandboxInstance_ContainerId(c *sandboxinstanceentityConfig) *sandboxInstance_ContainerId {
	t := &sandboxInstance_ContainerId{}
	t.config = c
	return t
}

// Set sets the value of ContainerId field
func (t *sandboxInstance_ContainerId) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldContainerId.Name.String())
	}
}

// Get gets the value of ContainerId field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *sandboxInstance_ContainerId) Get() *string {
	return t.StringStorage.Get()
}

// sandboxInstance_PreviewUrl is PreviewUrl field
type sandboxInstance_PreviewUrl struct {
	field.StringStorage[string]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_PreviewUrl creates a new sandboxInstance_PreviewUrl
func newSandboxInstance_PreviewUrl(c *sandboxinstanceentityConfig) *sandboxInstance_PreviewUrl {
	t := &sandboxInstance_PreviewUrl{}
	t.config = c
	return t
}

// Set sets the value of PreviewUrl field
func (t *sandboxInstance_PreviewUrl) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldPreviewUrl.Name.String())
	}
}

// Get gets the value of PreviewUrl field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *sandboxInstance_PreviewUrl) Get() *string {
	return t.StringStorage.Get()
}

// sandboxInstance_Status is Status field
type sandboxInstance_Status struct {
	field.IntStorage[int16]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_Status creates a new sandboxInstance_Status
func newSandboxInstance_Status(c *sandboxinstanceentityConfig) *sandboxInstance_Status {
	t := &sandboxInstance_Status{}
	t.config = c
	return t
}

// Set sets the value of Status field
func (t *sandboxInstance_Status) Set(v int16) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldStatus.Name.String())
	}
}

// Get gets the value of Status field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *sandboxInstance_Status) Get() *int16 {
	return t.IntStorage.Get()
}

// sandboxInstance_CreatedAt is CreatedAt field
type sandboxInstance_CreatedAt struct {
	field.TimestampStorage[time.Time]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_CreatedAt creates a new sandboxInstance_CreatedAt
func newSandboxInstance_CreatedAt(c *sandboxinstanceentityConfig) *sandboxInstance_CreatedAt {
	t := &sandboxInstance_CreatedAt{}
	t.config = c
	return t
}

// Set sets the value of CreatedAt field
func (t *sandboxInstance_CreatedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldCreatedAt.Name.String())
	}
}

// Get gets the value of CreatedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *sandboxInstance_CreatedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// sandboxInstance_LastAt is LastAt field
type sandboxInstance_LastAt struct {
	field.TimestampStorage[time.Time]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_LastAt creates a new sandboxInstance_LastAt
func newSandboxInstance_LastAt(c *sandboxinstanceentityConfig) *sandboxInstance_LastAt {
	t := &sandboxInstance_LastAt{}
	t.config = c
	return t
}

// Set sets the value of LastAt field
func (t *sandboxInstance_LastAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldLastAt.Name.String())
	}
}

// Get gets the value of LastAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *sandboxInstance_LastAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}

// sandboxInstance_DeletedAt is DeletedAt field
type sandboxInstance_DeletedAt struct {
	field.TimestampStorage[time.Time]
	config *sandboxinstanceentityConfig
}

// newsandboxInstance_DeletedAt creates a new sandboxInstance_DeletedAt
func newSandboxInstance_DeletedAt(c *sandboxinstanceentityConfig) *sandboxInstance_DeletedAt {
	t := &sandboxInstance_DeletedAt{}
	t.config = c
	return t
}

// Set sets the value of DeletedAt field
func (t *sandboxInstance_DeletedAt) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.sandboxinstanceentityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(sandbox_instance.FieldDeletedAt.Name.String())
	}
}

// Get gets the value of DeletedAt field
//
// If the field is required, it returns the value type; otherwise, it returns a pointer type.

func (t *sandboxInstance_DeletedAt) Get() *time.Time {
	return t.TimestampStorage.Get()
}
