// Code generated by taurus_go/entity, DO NOT EDIT.

package runtime

import (
	"context"

	"git.zodileap.com/entity/runtime_v1/internal"
	"git.zodileap.com/entity/runtime_v1/sandbox_instance"
	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// SandboxInstanceEntityQuery is the query action for the SandboxInstanceEntity.
type SandboxInstanceEntityQuery struct {
	config       *sandboxinstanceentityConfig
	ctx          *entitysql.QueryContext
	predicates   []entitysql.PredicateFunc
	rels         []sandboxinstanceentityRel
	order        []sandbox_instance.OrderTerm
	scanner      []*internal.QueryScanner
	scannerTotal int
}

// First returns the first result of the query.
func (o *SandboxInstanceEntityQuery) First(ctx context.Context) (*SandboxInstanceEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// newSandboxInstanceEntityQuery creates a new SandboxInstanceEntityQuery.
func newSandboxInstanceEntityQuery(c *internal.Dialect, t entity.Tracker, ms *sandboxinstanceentityMutations) *SandboxInstanceEntityQuery {
	return &SandboxInstanceEntityQuery{
		config: &sandboxinstanceentityConfig{
			Dialect:                        c,
			sandboxinstanceentityMutations: ms,
		},
		ctx:          &entitysql.QueryContext{},
		predicates:   []entitysql.PredicateFunc{},
		rels:         []sandboxinstanceentityRel{},
		order:        []sandbox_instance.OrderTerm{},
		scanner:      []*internal.QueryScanner{},
		scannerTotal: 0,
	}
}

func (o *SandboxInstanceEntityQuery) Where(predicates ...entitysql.PredicateFunc) *SandboxInstanceEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *SandboxInstanceEntityQuery) Limit(limit int) *SandboxInstanceEntityQuery {
	o.ctx.Limit = &limit
	return o
}

func (o *SandboxInstanceEntityQuery) Order(term ...sandbox_instance.OrderTerm) *SandboxInstanceEntityQuery {
	o.order = append(o.order, term...)
	return o
}

func (o *SandboxInstanceEntityQuery) Include(rels ...sandboxinstanceentityRel) *SandboxInstanceEntityQuery {
	o.rels = append(o.rels, rels...)
	return o
}

// ToList returns the list of results of the query.
func (o *SandboxInstanceEntityQuery) ToList(ctx context.Context) ([]*SandboxInstanceEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *SandboxInstanceEntityQuery) Single(ctx context.Context) (*SandboxInstanceEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *SandboxInstanceEntityQuery) sqlSingle(ctx context.Context) (*SandboxInstanceEntity, error) {
	var (
		spec = o.querySpec()
		res  *SandboxInstanceEntity
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *SandboxInstanceEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan(fields)...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}
			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = e
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	if res != nil {
		if err := res.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		r.reset()
	}
	return res, nil
}

func (o *SandboxInstanceEntityQuery) sqlAll(ctx context.Context) ([]*SandboxInstanceEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*SandboxInstanceEntity{}
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *SandboxInstanceEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan([]entitysql.ScannerField{})...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}

			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = mergeSandboxInstanceEntity(res, e)
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		rel := r
		rel.reset()
	}
	return res, nil
}

func (o *SandboxInstanceEntityQuery) querySpec() *entitysql.QuerySpec {
	s := entitysql.NewQuerySpec(sandbox_instance.Entity, sandbox_instance.Columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s = entitysql.NewQuerySpec(sandbox_instance.Entity, fields)
	}
	for i := range s.Entity.Columns {
		switch sandbox_instance.Columns[i] {
		case sandbox_instance.FieldId.Name:
			var a *sandboxInstance_Id = new(sandboxInstance_Id)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldId.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case sandbox_instance.FieldSessionId.Name:
			var a *sandboxInstance_SessionId = new(sandboxInstance_SessionId)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldSessionId.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case sandbox_instance.FieldContainerId.Name:
			var a *sandboxInstance_ContainerId = new(sandboxInstance_ContainerId)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldContainerId.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case sandbox_instance.FieldPreviewUrl.Name:
			var a *sandboxInstance_PreviewUrl = new(sandboxInstance_PreviewUrl)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldPreviewUrl.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case sandbox_instance.FieldStatus.Name:
			var a *sandboxInstance_Status = new(sandboxInstance_Status)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldStatus.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case sandbox_instance.FieldCreatedAt.Name:
			var a *sandboxInstance_CreatedAt = new(sandboxInstance_CreatedAt)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldCreatedAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case sandbox_instance.FieldLastAt.Name:
			var a *sandboxInstance_LastAt = new(sandboxInstance_LastAt)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldLastAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case sandbox_instance.FieldDeletedAt.Name:
			var a *sandboxInstance_DeletedAt = new(sandboxInstance_DeletedAt)
			fieldSpace := entitysql.NewFieldSpec(sandbox_instance.FieldDeletedAt.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		}
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	if rs := o.rels; len(rs) > 0 {
		s.Rels = make([]entitysql.Relation, 0, len(rs))
		s.Orders = append(s.Orders, sandbox_instance.ByPrimary)
		for _, r := range rs {
			rel := r
			s.Rels = append(s.Rels, func(s *entitysql.Selector) {
				o.scanner = o.addRels(s, s.Table(), rel, o.scanner)
			})
		}
	}
	for _, o := range o.order {
		s.Orders = append(s.Orders, func(order *entitysql.Order) {
			o.Apply(order)
		})
	}
	return s
}

func (o *SandboxInstanceEntityQuery) addRels(s *entitysql.Selector, t *entitysql.SelectTable, rel rel, scanner []*internal.QueryScanner) []*internal.QueryScanner {
	desc, children, config := rel.Desc()
	join := entitysql.AddRelBySelector(s, t, desc)
	_, tableNum := join.GetAs()
	qs := internal.QueryScanner{Config: config, Children: []*internal.QueryScanner{}, TableNum: tableNum}
	scanner = append(scanner, &qs)
	o.scannerTotal++
	if len(children) > 0 {
		for _, c := range children {
			qs.Children = o.addRels(s, join, c, qs.Children)
		}
	}
	return scanner
}
