// Code generated by taurus_go/entity, DO NOT EDIT.

package runtime

import (
	"git.zodileap.com/entity/runtime_v1/internal"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

type sandboxinstanceentityRelation struct {
	Config   internal.EntityConfig
	relation entitysql.RelationDesc
	children []rel
}

func newSandboxinstanceentityRelation(config internal.EntityConfig, desc entitysql.RelationDesc) *sandboxinstanceentityRelation {
	return &sandboxinstanceentityRelation{
		Config:   config,
		relation: desc,
		children: []rel{},
	}
}

func (r *sandboxinstanceentityRelation) Where(predicates ...entitysql.PredicateFunc) *sandboxinstanceentityRelation {
	r.relation.Predicates = append(r.relation.Predicates, predicates...)
	return r
}

func (r *sandboxinstanceentityRelation) Include(rels ...sandboxinstanceentityRel) *sandboxinstanceentityRelation {
	// Create a slice of type Rel with the same length as r.children
	newRels := make([]rel, len(rels))
	for i, r := range rels {
		// Convert each sandboxinstanceentityRel to Rel and store it in the new slice
		newRels[i] = rel(r)
	}
	r.children = append(r.children, newRels...)
	return r
}

func (r *sandboxinstanceentityRelation) Desc() (entitysql.RelationDesc, []rel, internal.EntityConfig) {
	return r.relation, r.children, r.Config
}

func (r *sandboxinstanceentityRelation) reset() {
	for _, child := range r.children {
		child.reset()
	}
	r.relation.Reset()
	r.children = []rel{}
}
