// Code generated by taurus_go/entity, DO NOT EDIT.

package service

import (
	enterprise "git.zodileap.com/entity/enterprise_v1/instance"
	specs "git.zodileap.com/gemini/libra_enterprise/specs/v1"
	zerr "git.zodileap.com/taurus/zodileap_go_zerr"
)

type BaseEnterprise struct {
	Enterprise *enterprise.Enterprise
}

// 初始化企业信息的基础服务实例
func NewBaseEnterprise() *BaseEnterprise {
	return &BaseEnterprise{
		Enterprise: enterprise.NewEnterprise(),
	}
}

// 创建单条企业信息
func (s *BaseEnterprise) Create(req enterprise.EnterpriseCreate) (*enterprise.EnterpriseEntity, error) {
	return WithService(
		&enterprise.EnterpriseEntity{},
		func(resp *enterprise.EnterpriseEntity) (*enterprise.EnterpriseEntity, error) {
			dto, err := s.Enterprise.Create(
				enterprise.NewDBOpCfg(),
				req,
			)
			if err != nil {
				return nil, zerr.Must(err)
			}
			if dto == nil {
				return nil, zerr.Err_1003002001.New("BaseEnterprise", "enterprise", "enterprise")
			}
			if dto.Enterprise == nil {
				return nil, zerr.Err_1003002002.New("Enterprise")
			}
			return dto.Enterprise, nil
		},
	)
}

// 创建多条企业信息
func (s *BaseEnterprise) CreateList(req []enterprise.EnterpriseCreate) (specs.EnterpriseCreateListResp, error) {
	return WithService(
		specs.EnterpriseCreateListResp{},
		func(resp specs.EnterpriseCreateListResp) (specs.EnterpriseCreateListResp, error) {
			dto, err := s.Enterprise.CreateList(
				enterprise.NewDBOpCfg(),
				req,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterprise", "enterprise", "enterprise")
			}
			if len(dto.Enterprises) == 0 {
				return resp, zerr.Err_1003002002.New("Enterprise")
			}
			for _, Enterprise := range dto.Enterprises {
				if Enterprise == nil {
					return resp, zerr.Err_1003002002.New("Enterprise").Sprintf()
				}
				resp.List = append(resp.List, Enterprise)
			}
			return resp, nil
		},
	)
}

// 更新企业信息
func (s BaseEnterprise) Update(req specs.EnterpriseUpdateReq) (specs.EnterpriseUpdateResp, error) {
	return WithService(
		specs.EnterpriseUpdateResp{},
		func(resp specs.EnterpriseUpdateResp) (specs.EnterpriseUpdateResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true

			dto, err := s.Enterprise.GetList(
				cfg,
				req.Query,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterprise", "enterprise", "enterprise")
			}
			if len(dto.Enterprises) == 0 {
				return resp, zerr.Err_1003002002.New("Enterprise")
			}
			for _, enterprise := range dto.Enterprises {
				if err := s.Enterprise.Update(
					cfg,
					enterprise,
					req.Update,
				); err != nil {
					return resp, zerr.Must(err)
				}
				resp.List = append(resp.List, enterprise)
			}

			if err := s.Enterprise.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}
			return resp, nil
		},
	)
}

// 更新多个企业信息
func (s BaseEnterprise) UpdateList(req specs.EnterpriseUpdateListReq) (specs.EnterpriseUpdateListResp, error) {
	return WithService(
		specs.EnterpriseUpdateListResp{},
		func(resp specs.EnterpriseUpdateListResp) (specs.EnterpriseUpdateListResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true

			for _, item := range req.List {
				dto, err := s.Enterprise.GetList(
					cfg,
					item.Query,
					false,
				)
				if err != nil {
					return resp, zerr.Must(err)
				}
				if dto == nil {
					return resp, zerr.Err_1003002001.New("BaseEnterprise", "enterprise", "enterprise")
				}
				if len(dto.Enterprises) == 0 {
					return resp, zerr.Err_1003002002.New("Enterprise")
				}
				for _, enterprise := range dto.Enterprises {
					if err := s.Enterprise.Update(
						cfg,
						enterprise,
						item.Update,
					); err != nil {
						return resp, zerr.Must(err)
					}
					resp.List = append(resp.List, enterprise)
				}
			}

			if err := s.Enterprise.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}
			return resp, nil
		},
	)
}

// 获取单条企业信息
func (s *BaseEnterprise) Get(req enterprise.EnterpriseQuery) (*enterprise.EnterpriseEntity, error) {
	return WithService(
		&enterprise.EnterpriseEntity{},
		func(resp *enterprise.EnterpriseEntity) (*enterprise.EnterpriseEntity, error) {
			dto, err := s.Enterprise.Get(
				enterprise.NewDBOpCfg(),
				req,
				false,
			)
			if err != nil {
				return nil, zerr.Must(err)
			}
			if dto == nil {
				return nil, nil
			}
			if dto.Enterprise == nil {
				return nil, nil
			}
			return dto.Enterprise, nil
		},
	)
}

// 获取多条企业信息
func (s *BaseEnterprise) GetList(req enterprise.EnterpriseQuery) (specs.EnterpriseGetListResp, error) {
	return WithService(
		specs.EnterpriseGetListResp{},
		func(resp specs.EnterpriseGetListResp) (specs.EnterpriseGetListResp, error) {
			dto, err := s.Enterprise.GetList(
				enterprise.NewDBOpCfg(),
				req,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, nil
			}
			if len(dto.Enterprises) == 0 {
				return resp, nil
			}
			for _, Enterprise := range dto.Enterprises {
				if Enterprise == nil {
					continue
				}
				resp.List = append(resp.List, Enterprise)
			}
			return resp, nil
		},
	)
}

// 删除企业信息
func (s *BaseEnterprise) Delete(req specs.EnterpriseDeleteReq) (specs.EnterpriseDeleteResp, error) {
	return WithService(
		specs.EnterpriseDeleteResp{},
		func(resp specs.EnterpriseDeleteResp) (specs.EnterpriseDeleteResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true
			query := req.Query
			dto, err := s.Enterprise.GetList(
				cfg,
				query,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterprise", "enterprise", "enterprise")
			}
			for _, enterprise := range dto.Enterprises {
				var err error
				if req.Remove {
					err = s.Enterprise.Remove(
						cfg,
						enterprise,
					)
				} else {
					err = s.Enterprise.Delete(
						cfg,
						enterprise,
					)
				}
				if err != nil {
					return resp, zerr.Must(err)
				}
			}
			if err := s.Enterprise.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}

			resp.Success = true
			return resp, nil
		},
	)
}

type BaseEnterpriseMember struct {
	EnterpriseMember *enterprise.EnterpriseMember
}

// 初始化企业成员的基础服务实例
func NewBaseEnterpriseMember() *BaseEnterpriseMember {
	return &BaseEnterpriseMember{
		EnterpriseMember: enterprise.NewEnterpriseMember(),
	}
}

// 创建单条企业成员
func (s *BaseEnterpriseMember) Create(req enterprise.EnterpriseMemberCreate) (*enterprise.EnterpriseMemberEntity, error) {
	return WithService(
		&enterprise.EnterpriseMemberEntity{},
		func(resp *enterprise.EnterpriseMemberEntity) (*enterprise.EnterpriseMemberEntity, error) {
			dto, err := s.EnterpriseMember.Create(
				enterprise.NewDBOpCfg(),
				req,
			)
			if err != nil {
				return nil, zerr.Must(err)
			}
			if dto == nil {
				return nil, zerr.Err_1003002001.New("BaseEnterpriseMember", "enterprise", "enterprise")
			}
			if dto.EnterpriseMember == nil {
				return nil, zerr.Err_1003002002.New("EnterpriseMember")
			}
			return dto.EnterpriseMember, nil
		},
	)
}

// 创建多条企业成员
func (s *BaseEnterpriseMember) CreateList(req []enterprise.EnterpriseMemberCreate) (specs.EnterpriseMemberCreateListResp, error) {
	return WithService(
		specs.EnterpriseMemberCreateListResp{},
		func(resp specs.EnterpriseMemberCreateListResp) (specs.EnterpriseMemberCreateListResp, error) {
			dto, err := s.EnterpriseMember.CreateList(
				enterprise.NewDBOpCfg(),
				req,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterpriseMember", "enterprise", "enterprise")
			}
			if len(dto.EnterpriseMembers) == 0 {
				return resp, zerr.Err_1003002002.New("EnterpriseMember")
			}
			for _, EnterpriseMember := range dto.EnterpriseMembers {
				if EnterpriseMember == nil {
					return resp, zerr.Err_1003002002.New("EnterpriseMember").Sprintf()
				}
				resp.List = append(resp.List, EnterpriseMember)
			}
			return resp, nil
		},
	)
}

// 更新企业成员
func (s BaseEnterpriseMember) Update(req specs.EnterpriseMemberUpdateReq) (specs.EnterpriseMemberUpdateResp, error) {
	return WithService(
		specs.EnterpriseMemberUpdateResp{},
		func(resp specs.EnterpriseMemberUpdateResp) (specs.EnterpriseMemberUpdateResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true

			dto, err := s.EnterpriseMember.GetList(
				cfg,
				req.Query,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterpriseMember", "enterprise", "enterprise")
			}
			if len(dto.EnterpriseMembers) == 0 {
				return resp, zerr.Err_1003002002.New("EnterpriseMember")
			}
			for _, enterpriseMember := range dto.EnterpriseMembers {
				if err := s.EnterpriseMember.Update(
					cfg,
					enterpriseMember,
					req.Update,
				); err != nil {
					return resp, zerr.Must(err)
				}
				resp.List = append(resp.List, enterpriseMember)
			}

			if err := s.EnterpriseMember.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}
			return resp, nil
		},
	)
}

// 更新多个企业成员
func (s BaseEnterpriseMember) UpdateList(req specs.EnterpriseMemberUpdateListReq) (specs.EnterpriseMemberUpdateListResp, error) {
	return WithService(
		specs.EnterpriseMemberUpdateListResp{},
		func(resp specs.EnterpriseMemberUpdateListResp) (specs.EnterpriseMemberUpdateListResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true

			for _, item := range req.List {
				dto, err := s.EnterpriseMember.GetList(
					cfg,
					item.Query,
					false,
				)
				if err != nil {
					return resp, zerr.Must(err)
				}
				if dto == nil {
					return resp, zerr.Err_1003002001.New("BaseEnterpriseMember", "enterprise", "enterprise")
				}
				if len(dto.EnterpriseMembers) == 0 {
					return resp, zerr.Err_1003002002.New("EnterpriseMember")
				}
				for _, enterpriseMember := range dto.EnterpriseMembers {
					if err := s.EnterpriseMember.Update(
						cfg,
						enterpriseMember,
						item.Update,
					); err != nil {
						return resp, zerr.Must(err)
					}
					resp.List = append(resp.List, enterpriseMember)
				}
			}

			if err := s.EnterpriseMember.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}
			return resp, nil
		},
	)
}

// 获取单条企业成员
func (s *BaseEnterpriseMember) Get(req enterprise.EnterpriseMemberQuery) (*enterprise.EnterpriseMemberEntity, error) {
	return WithService(
		&enterprise.EnterpriseMemberEntity{},
		func(resp *enterprise.EnterpriseMemberEntity) (*enterprise.EnterpriseMemberEntity, error) {
			dto, err := s.EnterpriseMember.Get(
				enterprise.NewDBOpCfg(),
				req,
				false,
			)
			if err != nil {
				return nil, zerr.Must(err)
			}
			if dto == nil {
				return nil, nil
			}
			if dto.EnterpriseMember == nil {
				return nil, nil
			}
			return dto.EnterpriseMember, nil
		},
	)
}

// 获取多条企业成员
func (s *BaseEnterpriseMember) GetList(req enterprise.EnterpriseMemberQuery) (specs.EnterpriseMemberGetListResp, error) {
	return WithService(
		specs.EnterpriseMemberGetListResp{},
		func(resp specs.EnterpriseMemberGetListResp) (specs.EnterpriseMemberGetListResp, error) {
			dto, err := s.EnterpriseMember.GetList(
				enterprise.NewDBOpCfg(),
				req,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, nil
			}
			if len(dto.EnterpriseMembers) == 0 {
				return resp, nil
			}
			for _, EnterpriseMember := range dto.EnterpriseMembers {
				if EnterpriseMember == nil {
					continue
				}
				resp.List = append(resp.List, EnterpriseMember)
			}
			return resp, nil
		},
	)
}

// 删除企业成员
func (s *BaseEnterpriseMember) Delete(req specs.EnterpriseMemberDeleteReq) (specs.EnterpriseMemberDeleteResp, error) {
	return WithService(
		specs.EnterpriseMemberDeleteResp{},
		func(resp specs.EnterpriseMemberDeleteResp) (specs.EnterpriseMemberDeleteResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true
			query := req.Query
			dto, err := s.EnterpriseMember.GetList(
				cfg,
				query,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterpriseMember", "enterprise", "enterprise")
			}
			for _, enterpriseMember := range dto.EnterpriseMembers {
				var err error
				if req.Remove {
					err = s.EnterpriseMember.Remove(
						cfg,
						enterpriseMember,
					)
				} else {
					err = s.EnterpriseMember.Delete(
						cfg,
						enterpriseMember,
					)
				}
				if err != nil {
					return resp, zerr.Must(err)
				}
			}
			if err := s.EnterpriseMember.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}

			resp.Success = true
			return resp, nil
		},
	)
}

type BaseEnterpriseRole struct {
	EnterpriseRole *enterprise.EnterpriseRole
}

// 初始化企业角色的基础服务实例
func NewBaseEnterpriseRole() *BaseEnterpriseRole {
	return &BaseEnterpriseRole{
		EnterpriseRole: enterprise.NewEnterpriseRole(),
	}
}

// 创建单条企业角色
func (s *BaseEnterpriseRole) Create(req enterprise.EnterpriseRoleCreate) (*enterprise.EnterpriseRoleEntity, error) {
	return WithService(
		&enterprise.EnterpriseRoleEntity{},
		func(resp *enterprise.EnterpriseRoleEntity) (*enterprise.EnterpriseRoleEntity, error) {
			dto, err := s.EnterpriseRole.Create(
				enterprise.NewDBOpCfg(),
				req,
			)
			if err != nil {
				return nil, zerr.Must(err)
			}
			if dto == nil {
				return nil, zerr.Err_1003002001.New("BaseEnterpriseRole", "enterprise", "enterprise")
			}
			if dto.EnterpriseRole == nil {
				return nil, zerr.Err_1003002002.New("EnterpriseRole")
			}
			return dto.EnterpriseRole, nil
		},
	)
}

// 创建多条企业角色
func (s *BaseEnterpriseRole) CreateList(req []enterprise.EnterpriseRoleCreate) (specs.EnterpriseRoleCreateListResp, error) {
	return WithService(
		specs.EnterpriseRoleCreateListResp{},
		func(resp specs.EnterpriseRoleCreateListResp) (specs.EnterpriseRoleCreateListResp, error) {
			dto, err := s.EnterpriseRole.CreateList(
				enterprise.NewDBOpCfg(),
				req,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterpriseRole", "enterprise", "enterprise")
			}
			if len(dto.EnterpriseRoles) == 0 {
				return resp, zerr.Err_1003002002.New("EnterpriseRole")
			}
			for _, EnterpriseRole := range dto.EnterpriseRoles {
				if EnterpriseRole == nil {
					return resp, zerr.Err_1003002002.New("EnterpriseRole").Sprintf()
				}
				resp.List = append(resp.List, EnterpriseRole)
			}
			return resp, nil
		},
	)
}

// 更新企业角色
func (s BaseEnterpriseRole) Update(req specs.EnterpriseRoleUpdateReq) (specs.EnterpriseRoleUpdateResp, error) {
	return WithService(
		specs.EnterpriseRoleUpdateResp{},
		func(resp specs.EnterpriseRoleUpdateResp) (specs.EnterpriseRoleUpdateResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true

			dto, err := s.EnterpriseRole.GetList(
				cfg,
				req.Query,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterpriseRole", "enterprise", "enterprise")
			}
			if len(dto.EnterpriseRoles) == 0 {
				return resp, zerr.Err_1003002002.New("EnterpriseRole")
			}
			for _, enterpriseRole := range dto.EnterpriseRoles {
				if err := s.EnterpriseRole.Update(
					cfg,
					enterpriseRole,
					req.Update,
				); err != nil {
					return resp, zerr.Must(err)
				}
				resp.List = append(resp.List, enterpriseRole)
			}

			if err := s.EnterpriseRole.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}
			return resp, nil
		},
	)
}

// 更新多个企业角色
func (s BaseEnterpriseRole) UpdateList(req specs.EnterpriseRoleUpdateListReq) (specs.EnterpriseRoleUpdateListResp, error) {
	return WithService(
		specs.EnterpriseRoleUpdateListResp{},
		func(resp specs.EnterpriseRoleUpdateListResp) (specs.EnterpriseRoleUpdateListResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true

			for _, item := range req.List {
				dto, err := s.EnterpriseRole.GetList(
					cfg,
					item.Query,
					false,
				)
				if err != nil {
					return resp, zerr.Must(err)
				}
				if dto == nil {
					return resp, zerr.Err_1003002001.New("BaseEnterpriseRole", "enterprise", "enterprise")
				}
				if len(dto.EnterpriseRoles) == 0 {
					return resp, zerr.Err_1003002002.New("EnterpriseRole")
				}
				for _, enterpriseRole := range dto.EnterpriseRoles {
					if err := s.EnterpriseRole.Update(
						cfg,
						enterpriseRole,
						item.Update,
					); err != nil {
						return resp, zerr.Must(err)
					}
					resp.List = append(resp.List, enterpriseRole)
				}
			}

			if err := s.EnterpriseRole.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}
			return resp, nil
		},
	)
}

// 获取单条企业角色
func (s *BaseEnterpriseRole) Get(req enterprise.EnterpriseRoleQuery) (*enterprise.EnterpriseRoleEntity, error) {
	return WithService(
		&enterprise.EnterpriseRoleEntity{},
		func(resp *enterprise.EnterpriseRoleEntity) (*enterprise.EnterpriseRoleEntity, error) {
			dto, err := s.EnterpriseRole.Get(
				enterprise.NewDBOpCfg(),
				req,
				false,
			)
			if err != nil {
				return nil, zerr.Must(err)
			}
			if dto == nil {
				return nil, nil
			}
			if dto.EnterpriseRole == nil {
				return nil, nil
			}
			return dto.EnterpriseRole, nil
		},
	)
}

// 获取多条企业角色
func (s *BaseEnterpriseRole) GetList(req enterprise.EnterpriseRoleQuery) (specs.EnterpriseRoleGetListResp, error) {
	return WithService(
		specs.EnterpriseRoleGetListResp{},
		func(resp specs.EnterpriseRoleGetListResp) (specs.EnterpriseRoleGetListResp, error) {
			dto, err := s.EnterpriseRole.GetList(
				enterprise.NewDBOpCfg(),
				req,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, nil
			}
			if len(dto.EnterpriseRoles) == 0 {
				return resp, nil
			}
			for _, EnterpriseRole := range dto.EnterpriseRoles {
				if EnterpriseRole == nil {
					continue
				}
				resp.List = append(resp.List, EnterpriseRole)
			}
			return resp, nil
		},
	)
}

// 删除企业角色
func (s *BaseEnterpriseRole) Delete(req specs.EnterpriseRoleDeleteReq) (specs.EnterpriseRoleDeleteResp, error) {
	return WithService(
		specs.EnterpriseRoleDeleteResp{},
		func(resp specs.EnterpriseRoleDeleteResp) (specs.EnterpriseRoleDeleteResp, error) {
			cfg := enterprise.NewDBOpCfg()
			cfg.KeepOpen = true
			query := req.Query
			dto, err := s.EnterpriseRole.GetList(
				cfg,
				query,
				false,
			)
			if err != nil {
				return resp, zerr.Must(err)
			}
			if dto == nil {
				return resp, zerr.Err_1003002001.New("BaseEnterpriseRole", "enterprise", "enterprise")
			}
			for _, enterpriseRole := range dto.EnterpriseRoles {
				var err error
				if req.Remove {
					err = s.EnterpriseRole.Remove(
						cfg,
						enterpriseRole,
					)
				} else {
					err = s.EnterpriseRole.Delete(
						cfg,
						enterpriseRole,
					)
				}
				if err != nil {
					return resp, zerr.Must(err)
				}
			}
			if err := s.EnterpriseRole.Save(cfg); err != nil {
				return resp, zerr.Must(err)
			}

			resp.Success = true
			return resp, nil
		},
	)
}
